conan-io/conan

- README.md
> Readme: add mention of cmake, fix spelling, add OS X config example

- .gitignore
- pyinstaller.py
Support for binaries creation.
> Pyinstaller

- conans/client/cmake.py
- conans/test/cmake_test.py
cast settings check inside CMake to str to avoid partial settings exceptions. Should fix #42
> Fix problem with CMake when removing settings values

- conans/client/generators.py
- conans/paths.py
This adds a generator for qmake projects. It works flawlessly with the timer example project. 
I believe all the flags are right, but I'm not sure whether deps.sharedlinkflags should be set to QMAKE_CXXFLAGS or QMAKE_LFLAGS.
> Add qmake generator

- conans/client/command.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/package_copier.py
- conans/client/remote_manager.py
- conans/test/integration/copy_packages_test.py
- conans/test/integration/install_selected_packages_test.py
- conans/test/package_copier_test.py
- conans/util/files.py
> Copy packages and download packages

- conans/client/installer.py
- conans/client/packager.py
- conans/test/command/export_test.py
- conans/test/integration/complete_test.py
- conans/test/integration/diamond_test.py
- conans/test/utils/cpp_test_files.py
I made test fail by introducing errors, and patch in source().
Then, assigning correct value to build_folder before calling build() fixes it.
Also, added package_folder before package() method, just in case the user wants to do something with it
Fix #96
> modified value prior to build(), included tests source() with patches

- conans/client/generators/cmake.py
> fixes#126 adding SYSTEM to cmake include_directories

- conans/client/generators/cmake.py
This should fix current problems with releases 0.7 and 0.7.1 regarding compiler checks. (#138, #139, #141), and could be minor 0.7.2
Tested in Win, not yet in linux, but for your consideration about the approach.
> Converting macros to functions and loading CONAN_COMPILER from conaninfo

- conans/client/command.py
- conans/test/command/user_test.py
Even the problem is in conan-package-tools, just to make sure that the problem is not here.
cc/ @SteffenL
> new test to check that password with spaces are ok, quotes can be scaped

- conans/client/generators/cmake.py
This probably fixes the issue raised in https://github.com/conan-io/docs/issues/40, and also an alternative solution to https://github.com/conan-io/conan/pull/156
> conanbuildinfo.cmake looking for conainfo.txt in its own directory

- conans/client/detect.py
Tested manually in Win, for VS(different versions), gcc, clang, using env CC and CXX vars for defining compiler. 
This doesn't mean that I have been able to build with clang in windows (Trying the Mingw make, but doesn't work yet, ld not able to find libstdc++?). But the detection, which is covered by this PR, works.
> Fix #154, also improvements in output, refactors, and minor bug

- conans/client/deps_builder.py
This probably fixes it, tests passing, but lets launch CI. @lasote did your problematic projects had diamonds?
> fixes problem with lib order in diamonds

- conans/client/remote_manager.py
- conans/server/test/service/service_test.py
- conans/test/command/export_test.py
- conans/test/tgz_md5_test.py
- conans/test/upload_test.py
- conans/test/utils/cpp_test_files.py
- conans/util/files.py
> remote_manager: Add the file mode to compressed tarfiles

- conans/client/generators/__init__.py
- conans/client/loader.py
- conans/test/integration/custom_generator_test.py
Dynamically loaded generators, as packages!
Tested with premake: check https://github.com/conan-io/conan/issues/85, and https://github.com/memsharded/conan-premake
> implements support for #67

- conans/client/file_copier.py
- conans/test/files_test.py
I've created an issue for this PR : #240
Basically I created a test and made FileCopier follow symbolic links
> Added walking through linked dirs too

- setup.py
> setup: Read requirements as a text file

- conans/client/generators/qbs.py
> Crash on QBS generator 

- conans/tools.py
Tested (manually) from consuming package. Will use it in TBB as soon as it is released.
> utility for msvc tools environmnet. Fix #273

- conans/client/generators/__init__.py
- conans/client/generators/cmake.py
- conans/client/generators/visualstudio.py
- conans/client/generators/xcode.py
- conans/client/installer.py
- conans/model/build_info.py
- conans/model/conan_generator.py
- conans/test/model/build_info_test.py
Here is a fix to #295.
Is that ok ?
I did not add the package version, but it may be done quickly.
> Added package name in Generator model (used in CMake generator)

- conans/client/command.py
- conans/client/deps_builder.py
- conans/client/loader.py
- conans/client/manager.py
- conans/model/conan_file.py
- conans/model/info.py
- conans/model/options.py
- conans/model/requires.py
- conans/model/scope.py
- conans/test/conanfile_loader_test.py
- conans/test/conanfile_tools_test.py
- conans/test/create_package_test.py
- conans/test/integration/conan_scopes_test.py
- conans/test/model/options_test.py
- conans/test/model/order_libs_test.py
- conans/test/model/transitive_reqs_test.py
DRAFT. It passes tests, and works as expected, but probably the implementation can be improved. Had to make some workarounds over some current implementation issues.
Please feedback
> Feature/scopes, Fix #80

- conans/client/detect.py
Very simple, to solve issue #323 reported by @coding3d
> adding i686 arch => x86

- conans/client/runner.py
- conans/test/runner_test.py
This should solve issue #314 .
Added some tests, the original problem is that that part was not tested as in testing we are actually using TestRunner. Forced usage of ConanRunner in conanfile to cover this code, which is most used in production
> honor cwd in self.run()

- conans/client/command.py
- conans/client/paths.py
- conans/client/proxy.py
- conans/client/rest/uploader_downloader.py
- conans/client/short_paths_conf.py
- conans/paths.py
- conans/server/store/file_manager.py
- conans/test/integration/conan_short_path_references_test.py
- conans/test/tools.py
- conans/tools.py
- conans/util/files.py
Should help with #311 and #256
> short paths for configured references

- conans/client/rest/auth_manager.py
- conans/client/rest/multipart_decode.py
- conans/server/rest/bottle_plugins/jwt_authentication.py
- conans/server/service/authorize.py
This would improve the issue https://github.com/conan-io/conan/issues/355
> changed unathorized msg to forbidden

- conans/client/command.py
- conans/client/new.py
- conans/test/command/new_test.py
This will be a fix for issue https://github.com/conan-io/conan/issues/357
> fixed error with non alphanumeric in conan new

- conans/client/conf/__init__.py
- conans/client/migrations.py
- conans/model/config_dict.py
- conans/test/model/other_settings_test.py
> exceptions and thread for mingw, None values valid if not defined

- conans/__init__.py
- conans/client/command.py
- conans/test/integration/only_source_test.py
This will solve the issue: https://github.com/conan-io/conan/issues/302
> automatic export on test_package command

- conans/model/info.py
This should solve issue: https://github.com/conan-io/conan/issues/366
> fixed crash in search remote print output

- conans/client/deps_builder.py
- conans/model/conan_file.py
- conans/model/config_dict.py
- conans/model/options.py
- conans/test/command/info_test.py
- conans/test/model/transitive_reqs_test.py
This removes the counter_config hack for header_only options
> config_settings and config_options

- conans/__init__.py
- conans/client/conf/__init__.py
- conans/client/migrations.py
This addresses https://github.com/conan-io/conan/issues/409
Includes migration
> added new apple-clang 8

- conans/requirements.txt
Pointed out by @tivek in issue #412
> removed cfgparse dependency

- conans/requirements.txt
> Updated Boto and Request

- conans/client/conf/__init__.py
- conans/model/config_dict.py
This should adresss issue #406
> added gcc 6.2, settings msg points to settings.yml

- conans/client/command.py
- conans/test/command/export_path_test.py
This should solve issue https://github.com/conan-io/conan/issues/411, problems with exporting with ``--path=../xxxx`` and also ``exports=../source``
> fixed problem with export path

- conans/client/deps_builder.py
- conans/client/installer.py
- conans/client/packager.py
- conans/errors.py
- conans/test/conanfile_exception_test.py
- conans/test/integration/conanfile_errors_test.py
This should address issue #429 for most conanfile errors.
> capturing traceback for offending line report

- conans/client/remover.py
- conans/server/store/file_manager.py
- conans/test/command/remove_empty_dirs_test.py
- conans/test/tools_test.py
- conans/util/files.py
Should solve issue https://github.com/conan-io/conan/issues/443
> fixed very slow remove empty dirs

- conans/client/loader.py
- conans/client/new.py
- conans/model/options.py
- conans/test/command/info_options_test.py
- conans/test/command/install_test.py
> allow prefixed and not prefixed options

- conans/client/loader.py
- conans/client/manager.py
- conans/model/config_dict.py
- conans/test/command/export_test.py
- conans/test/update_settings_yml_test.py
> allow conan export to load only class, not object with settings

- conans/client/command.py
- conans/client/output.py
> changing colors with envvars

- conans/client/proxy.py
- conans/test/integration/manifest_validation_test.py
Solves issue https://github.com/conan-io/conan/issues/458
> handling missing manifest.txt in recipe and packages

- conans/client/remote_manager.py
- conans/test/broken_download_test.py
Solves https://github.com/conan-io/conan/issues/459
> fixed behavior when transfers fail

- conans/__init__.py
- conans/client/importer.py
- conans/client/installer.py
- conans/client/rest/version_checker.py
- conans/server/conf/__init__.py
- conans/server/rest/bottle_plugins/version_checker.py
- conans/test/command/install_test.py
Also include minors fixes for client-server versions check.
> imports() can copy to absolute paths, and will not be removed

- conans/client/migrations.py
- conans/model/version.py
- conans/test/model/version_test.py
Should fix https://github.com/conan-io/conan/issues/482
> fixing migrations with no settings.yml. Fixing Version parsing and compare

- conans/client/command.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/source.py
- conans/test/command/source_test.py
This runs the source method in the conanfile. It also accepts the -f flag
to force removal and re-running the source method.
> Add conan source command to client

- conans/model/version.py
Extracted Version model from develop  to allow a 0.12.1-dev client operate against current 0.12.0 server without a deprecation message.
> HOTFIX: Better version compare

- conans/client/client_cache.py
- conans/client/command.py
- conans/client/conf/__init__.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/manifest_manager.py
- conans/client/proxy.py
- conans/client/uploader.py
- conans/test/integration/complete_test.py
- conans/test/integration/manifest_validation_test.py
- conans/test/integration/package_command_test.py
- conans/test/upload_test.py
> proposal for manifests capture & verify

- conans/client/deps_builder.py
- conans/model/info.py
- conans/test/integration/half_diamond_test.py
- conans/test/model/transitive_reqs_test.py
> fix indirect requirements for full_requires

- conans/client/remote_manager.py
- conans/client/rest/rest_client.py
- conans/test/download_test.py
- conans/test/upload_test.py
Should fix https://github.com/conan-io/conan/issues/407
> ordering inverse alphabetically upload downloads, so tgz go last

- conans/client/output.py
- conans/test/output_test.py
Should fix https://github.com/conan-io/conan/issues/512
> fixed problem with py3 output rewrite_line

- conans/client/configure_environment.py
- conans/test/compile_helpers_test.py
- conans/tools.py
1. Configure environment should not include -l in LDFLAGS, only in LIBS 
2. Fixed replace…_in_file to work with complex encodings
> Small fixes

- conans/client/generators/virtualenv.py
Need to restore correct PS1 while deactivating virtual env
> restore correct PS1

- conans/client/generators/virtualenv.py
- conans/test/integration/python_diamond_test.py
- conans/test/utils/python_test_files.py
- conans/tools.py
> python packages diamond test

- conans/test/tools_test.py
- conans/tools.py
> Fix replace in file and test

- conans/client/configure_environment.py
- conans/test/compile_helpers_test.py
Should solve https://github.com/conan-io/conan/issues/533
> fixing %CL% env var in windows

- conans/client/command.py
- conans/client/deps_builder.py
- conans/client/output.py
- conans/model/options.py
- conans/model/requires.py
- conans/model/values.py
- conans/test/integration/conflict_diamond_test.py
- conans/test/integration/package_command_test.py
- conans/test/model/transitive_reqs_test.py
- conans/tools.py
- conans/util/env_reader.py
To address issue #521.
Implemented werror for general purpose "abort instead of just warn".
Applied it just for conflicts in the dep tree, though might be used in other contexts too.
> implemented werror for conflicts

- conans/client/output.py
- conans/client/rest/uploader_downloader.py
- conans/test/output_test.py
- conans/tools.py
This should solve issue: https://github.com/conan-io/conan/issues/531
> not use progress bars in file output

- conans/model/scope.py
- conans/test/model/scope_test.py
> Scopes with colon

- conans/search.py
- conans/test/command/search_test.py
> Fixed search options locally

- conans/util/files.py
Related to https://github.com/conan-io/conan/issues/556, could solve it.
cc/ @piponazo
> not necessary to open to os.utime

- conans/client/command.py
- conans/client/manager.py
- conans/test/integration/diamond_test.py
- conans/test/integration/package_command_test.py
To solve #525
It also increments and moves the DiamondTest sleeps, trying to fix those random failures in appveyor CI
> simplify package command, improve error msgs

- conans/client/deps_builder.py
- conans/client/installer.py
- conans/test/integration/private_deps_test.py
This should solve #571
TODO: review status of dev_requires, private, need for build_requires (or not), etc.
> fixed issue with private transitivity

- conans/client/configure_environment.py
- conans/client/output.py
- conans/test/compile_helpers_test.py
- conans/test/integration/profile_test.py
- conans/test/integration/vcvars_env_test.py
Should solve issue https://github.com/conan-io/conan/issues/576
> fixed old command_line for win in ConfigureEnvironment

- conans/client/client_cache.py
- conans/client/installer.py
- conans/client/loader.py
- conans/client/manager.py
- conans/client/proxy.py
- conans/client/remote_manager.py
- conans/client/source.py
- conans/paths.py
- conans/test/path_exists_test.py
- conans/test/path_limit_test.py
- conans/test/upload_test.py
- conans/util/files.py
Not to merge yet, just to pass CI.
To address #581 and #582
> fixing short paths

- conans/client/manager.py
- conans/model/profile.py
- conans/test/integration/profile_test.py
Better error messages in case of bad profile text file format.
> Control error in profiles format

- contributors.txt
As requested by @memsharded, I have added myself to contributors.txt.
> Added myself to contributors.txt

- contributors.txt
I just did here what @memsharded proposed me via email ;)
> Add myself to the contributors list

- contributors.txt
I added my name to contributors.txt, as you asked.
> Added astralien3000 to contributors.txt

- contributors.txt
I added my name to the contributor list, as asked. Thank you for having me on the list!
> Add Jeongseok Lee to contributors.txt

- conans/model/build_info.py
- conans/test/command/build_test.py
- conans/test/requirements.txt
> fixed parsing of conanbuildinfo.txt

- contributors.txt
Added myself to contributors.txt.
> Add Róbert Márki to contributors.txt

- conans/client/client_cache.py
- conans/client/manager.py
- conans/model/profile.py
- conans/test/model/profile_test.py
> Better profiles parsing and error controlled

- conans/test/integration/python_build_test.py
To make sure https://github.com/conan-io/conan/issues/607 works
> ensuring that pythonpath works with source command

- conans/client/generators/virtualenv.py
Related to https://github.com/lasote/conan-mingw-installer/issues/4
> Virtual env with / instead of \ (windows)

- conans/client/proxy.py
- conans/test/integration/install_outdated_test.py
- Renamed test module filename
- Fixed oudated feature
> Fixed oudated feature and recovered tests

- pyinstaller.py
Address https://github.com/conan-io/conan/issues/631
> added import necessary for Qt to pyinstaller

- conans/client/generators/virtualenv.py
Should address https://github.com/conan-io/conan-package-tools/issues/36
> Virtualenv without _CONAN_VENV

- conans/paths.py
This should address: https://github.com/conan-io/conan/issues/644
> workaround to make msys use C:/Users/<user>/ instead of msys

- conans/__init__.py
- conans/client/conf/__init__.py
- conans/client/migrations.py
> Added ppc64

- conans/client/cmake.py
Implements: https://github.com/conan-io/conan/issues/700
> using generator to decide on cmake multi-conf

- conans/util/files.py
Address: https://github.com/conan-io/conan/issues/694
> added normpath to path_exists Win

- conans/tools.py
> Support .tbz2 in tools.unzip

- conans/client/client_cache.py
- conans/client/conf/__init__.py
> Windows line endings for default config and settings

- conans/client/cmake.py
- conans/test/cmake_test.py
> Ability to change CMake generator property

- conans/client/deps_builder.py
- conans/client/loader.py
- conans/client/manager.py
- conans/model/conan_file.py
- conans/test/integration/same_userchannel_test.py
Address https://github.com/conan-io/conan/issues/676
> added user & channel properties to conanfile

- conans/client/command.py
- conans/client/generators/cmake.py
This two bugs were making [my Jenkins job](https://ci.appveyor.com/project/jgsogo/queryset-cpp/build/job/yjkqys90d06hel01) fail.
> [bugfix] Solve two bugfixes on 0.16 version.

- conans/client/client_cache.py
- conans/client/command.py
- conans/client/manager.py
- conans/test/integration/profile_test.py
Address: https://github.com/conan-io/conan/issues/714
> allowing custom paths in profiles

- conans/client/remote_manager.py
- conans/model/manifest.py
- conans/test/integration/python_build_test.py
Addresses: #751 
Plus:
- Minor refactor of ``compress_xxx_files`` common code
- Improved ``FileTreeManifest.create`` so the filter of unwanted files is done **before** the ``md5sum`` computation.
An improvement could be done in the way the the manifests and the files to compress&upload are created/checked, but preferred to solve this quickly and have it into the release if possible for @tru
> fixed issue with python packages upload + refactors

- conans/client/command.py
- conans/client/file_copier.py
- conans/client/importer.py
- conans/client/manager.py
- conans/test/command/imports_test.py
- conans/test/integration/symlinks_test.py
- conans/test/utils/test_files.py
Proposal for #722 
Feedback from @annulen welcome, thanks!
> imports manifests and undo

- conans/client/deps_builder.py
- conans/model/requires.py
- conans/test/integration/conanfile_errors_test.py
Should solve: https://github.com/conan-io/conan/issues/757
Behavior changed: now always an Exception
> no accept duplicated requires

- conans/client/generators/__init__.py
- conans/client/generators/scons.py
- conans/test/generators/scons_test.py
- conans/test/generators_test.py
Suggested usage in SConstruct file:
conan = SConscript('SConscript-conan')
completeEnv = Environment()
completeEnv.MergeFlags(conan['conan'])
completeEnv.Program("foo", "foo.c")
partialEnv = Environment()
partialEnv.MergeFlags(conan['zlib'])
partialEnv.MergeFlags(conan['poco'])
partialEnv.Program("bar", "bar.c")
> Add SCons generator

- conans/client/cmake.py
- conans/client/conf/__init__.py
Address https://github.com/conan-io/conan/issues/778
> support for vs 2017

- conans/client/conf/__init__.py
> Support GCC 6.3

- conans/client/uploader.py
- conans/test/command/upload_test.py
Should fix: https://github.com/conan-io/conan/issues/855
> added error message for upload patterns not matching

- conans/client/command.py
- conans/test/command/remote_test.py
- conans/util/config_parser.py
Should fix: https://github.com/conan-io/conan/issues/853
> fixing input arg verify_ssl

- conans/client/command.py
- conans/test/conan_trace_file_test.py
- conans/test/tools_test.py
Added test about package log file. Wait for CI, not sure about asserting that traces in windows.
> Test package log file

- conans/client/importer.py
- conans/test/command/imports_test.py
- conans/test/command/install_test.py
This should address: https://github.com/conan-io/conan/issues/896
> added environment variables to imports()

- conans/client/installer.py
- conans/client/manager.py
- conans/test/integration/system_reqs_test.py
- conans/test/tools_test.py
- conans/tools.py
#838 and #837
Raises if system requirements tool finish without returning OK and local conan install calling system requiremtns
> System requirements improvements

- conans/client/generators/virtualenv.py
does what it says on the tin.
feedback welcome.
> added powershell support to virtualenv generator

- conans/requirements.txt
> Bump version requirement for requests

- conans/client/command.py
- conans/util/tracer.py
> Fixed bad crash with traces

- conans/util/files.py
> compress level env variable

- conans/client/manager.py
- conans/client/proxy.py
- conans/test/integration/export_sources_test.py
Should address https://github.com/conan-io/conan/issues/943
> fixed problem with copy and exports-sources

- conans/client/command.py
- conans/client/conf/__init__.py
- conans/test/command/config_test.py
> commands to edit config

- conans/client/command.py
- conans/client/generators/virtualenv.py
- conans/client/importer.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/source.py
- conans/model/conan_file.py
- conans/model/env_info.py
- conans/test/integration/conan_env_test.py
- conans/test/integration/profile_test.py
- conans/test/integration/python_build_test.py
- conans/test/model/env_test.py
- conans/test/model/profile_test.py
- conans/tools.py
#940 and little refactor:
- instance methods as simple functions (not using self)
- command parameters refactor (install, info, test_package)
> Conan info with profiles and little command and manager refactor

- conans/test/tools_test.py
- conans/tools.py
> System package tool

- conans/client/installer.py
- conans/model/settings.py
- conans/test/integration/only_source_test.py
Should address: https://github.com/conan-io/conan/issues/959
> new error messages, shorter, with links

- conans/client/conf/__init__.py
- Included gcc-4.1 in default settings.yml
Signed-off-by: Uilian Ries <uilianries@gmail.com>
> #992 Add GCC-4.1 by default

- conans/test/zip_permissions_test.py
- conans/tools.py
#936 Not sure if it works in Windows
> Adjust Zip perms

- conans/client/cmake.py
- conans/test/cmake_test.py
- conans/test/command/export_path_test.py
- conans/test/command/export_test.py
- conans/test/integration/cmake_multi_test.py
- conans/test/utils/cpp_test_files.py
Implements  #759
Provide a fix for #770
> Improvements to CMake class

- conans/client/generators/visualstudio.py
Partially address (at least solve the bug) in https://github.com/conan-io/conan/issues/998
> minor fix in vs generator

- conans/client/runner.py
Should help with https://github.com/conan-io/conan/issues/984.
> Fix encodings in logging

- conans/client/manager.py
- conans/test/command/install_test.py
- conans/test/integration/conan_scopes_test.py
- conans/test/libcxx_setting_test.py
- conans/test/options_caching_test.py
> Not cache for install/info

- conans/client/client_cache.py
- conans/test/put_properties_test.py
> Fixed comments parsing in artifacts.properties

- conans/__init__.py
- conans/client/generators/cmake_common.py
- conans/client/manager.py
- conans/test/command/install_test.py
- conans/test/generators/cmake_test.py
- conans/test/integration/cmake_flags_test.py
- conans/test/integration/conan_scopes_test.py
- conans/test/libcxx_setting_test.py
- conans/test/options_caching_test.py
Issue https://github.com/conan-io/conan/issues/1043. PR for review mainly, could deserve a minor
- Reverting cmake quotes
- New test, showing that no quotes are being added.
The original cause for https://github.com/conan-io/conan/issues/950 is still unknown, I keep working on it.
cc/ @kent-at-multiscale, @tru, @lasote
> Fix cmake quotes regression

- conans/client/installer.py
- conans/test/integration/install_outdated_test.py
Issue https://github.com/conan-io/conan/issues/1053
> fixing the --build outdated --build Pkg regression

- conans/client/export.py
- conans/client/file_copier.py
- conans/test/command/export_test.py
Address: https://github.com/conan-io/conan/issues/810
> adding exclude syntax to exports

- conans/client/generators/cmake_common.py
This is a fix for bug https://github.com/conan-io/conan/issues/1068, maybe can wait for net release.
> fixed wrong conan_c_flags

- conans/__init__.py
- conans/client/command.py
- conans/client/installer.py
- conans/client/manager.py
- conans/test/command/install_test.py
Maybe this is too much for a minor, but IMO is the good solution to the issue https://github.com/conan-io/conan/issues/1053
> improved build_mode

- conans/client/importer.py
- conans/client/manager.py
- conans/test/command/imports_test.py
Address: https://github.com/conan-io/conan/issues/1073
> fixed imports command dest

- conans/client/command.py
- conans/test/integration/manifest_validation_test.py
Address: https://github.com/conan-io/conan/issues/1002
> manifests for test_package

- conans/client/manager.py
- conans/test/command/install_test.py
Address: https://github.com/conan-io/conan/issues/967
> changed cross build msg

- conans/client/command.py
- conans/client/manager.py
- conans/client/remover.py
- conans/client/rest/rest_client.py
- conans/search/search.py
- conans/test/command/remove_test.py
- conans/test/files_test.py
> Use query for removing packages

- conans/requirements_server.txt
- conans/server/conf/__init__.py
- conans/server/conf/default_server_conf.py
- conans/server/server_launcher.py
- conans/test/server/authenticator_plugin_test.py
- conans/test/tools_test.py
> Simple extensions with plugins for authenticators

- conans/client/generators/visualstudio.py
- conans/test/generators/visual_studio_test.py
This PR adds individual fields for each requirement to the generated .props file.
These properties can be used in other visual studio files, e.g. as fixed path variable.
> Extended vs generator

- conans/model/profile.py
- conans/test/model/profile_test.py
> $PROFILE_DIR variable in profiles

- conans/test/integration/install_update_test.py
It should address #949, it doesn't fail as described, so I'd need the feedback from @piponazo
> test that doesn't fail for issue #949

- conans/client/generators/cmake_common.py
- conans/test/integration/cmake_flags_test.py
Should address: https://github.com/conan-io/conan/issues/950
> fixing quoted flags

- conans/model/info.py
- conans/model/options.py
- conans/model/ref.py
- conans/model/version.py
- conans/test/model/info_test.py
- conans/test/model/transitive_reqs_test.py
- conans/test/model/version_test.py
Address https://github.com/conan-io/conan/issues/926
Please @claasd , have a look to check if the ``self.info.requires.patch_mode()`` could be good for you.
> added new version modes, fixed string versions

- conans/client/generators/virtualbuildenv.py
- conans/client/generators/virtualenv.py
- conans/test/integration/conan_env_test.py
> Fixing env variables with spaces

- conans/test/command/export_path_test.py
- conans/test/command/export_test.py
- conans/test/integration/cmake_flags_test.py
- conans/test/integration/cmake_multi_test.py
- conans/test/integration/cmake_targets_test.py
- conans/test/integration/conan_test_test.py
- conans/test/remote/rest_api_test.py
- conans/test/utils/cpp_test_files.py
- conans/test/utils/multi_config.py
Speed up tests in Windows, gain several minutes
> cmake test speeding

- conans/client/generators/visualstudio.py
- conans/test/generators/visual_studio_test.py
not every VS can handle . in names in properties. Replace them with -
> Hotfi as VS has not full XML support

- conans/server/server_launcher.py
- conans/test/server/authenticator_plugin_test.py
Address https://github.com/conan-io/conan/issues/1129
> fixing plugins

- conans/client/configure_build_environment.py
- conans/test/functional/autotools_configure_test.py
Inheriting the flags from cpp_info
> Fixed build environment

- conans/client/command.py
- conans/client/printer.py
- conans/test/command/info_test.py
> Added info --only options

- conans/client/cmake.py
- conans/client/new.py
- conans/test/functional/cmake_test.py
- Added cmake.test() to invoke `make test` or `msvc RUN_TESTS`
- Update `conan new` to use cmake helpers
Signed-off-by: Uilian Ries <uilianries@gmail.com>
> #1148 CMake test helper

- conans/client/command.py
- conans/client/manager.py
- conans/client/new.py
- conans/test/command/package_files_test.py
This would implement: https://github.com/conan-io/conan/issues/1112
~~It might be ready, but conflicting with ongoing work by @lasote, so it could wait until then.~~
Merged with develop, conflicts solved.
> initial proposal for package_files command

- conans/client/conf/__init__.py
- conans/client/migrations.py
Address: https://github.com/conan-io/conan/issues/1157
> adding latest compilers and migration

- conans/client/export.py
- conans/client/importer.py
- conans/client/manifest_manager.py
- conans/client/proxy.py
- conans/client/remote_manager.py
- conans/client/uploader.py
- conans/model/manifest.py
- conans/test/command/upload_test.py
- conans/test/model/manifest_test.py
Address: https://github.com/conan-io/conan/issues/1040
After this, a larger refactor can be done to hide "file_sums", and probably to rename digest => manifest
> fixing upload corrupt bug

- conans/test/util/tools_test.py
- conans/tools.py
Address https://github.com/conan-io/conan/issues/1130
> msvc_command and vcvars improvements

- conans/client/conf/__init__.py
- conans/test/util/tools_test.py
- conans/tools.py
> Custom bash path

- conans/client/cmake.py
- conans/test/functional/cmake_test.py
Address: https://github.com/conan-io/conan/issues/1026
Probably NEEDS a bit more analysis of possible interactions with user defined CXX_FLAGS
> adding MP flag for MSVC parallel builds

- conans/client/grapher.py
Address: https://github.com/conan-io/conan/issues/1166
> improving graph html

- conans/tools.py
Address: https://github.com/conan-io/conan/issues/1197
> fixed hardcoded vs15 version in tools.vcvars

- conans/client/command.py
- conans/client/export.py
- conans/client/manager.py
- conans/test/command/export_test.py
https://github.com/conan-io/conan/issues/1147
> allowing custom filenames for export command

- conans/util/log.py
- Produced double log messages
> Remove log handlers before adding conan one

- conans/model/build_info.py
- conans/test/model/build_info_test.py
Address https://github.com/conan-io/conan/issues/1248
> fixed packages with underscore parsing conanbuildinfo

- conans/test/functional/compile_helpers_test.py
- conans/test/util/tools_test.py
- conans/tools.py
Address https://github.com/conan-io/conan/issues/1253
> fixed vcvars arch setting

- conans/client/conf/__init__.py
- conans/client/linter.py
- conans/test/command/export_linter_test.py
https://github.com/conan-io/conan/issues/1246
> pylintrc env var

- conans/test/functional/path_limit_test.py
Related to https://github.com/conan-io/conan/issues/1229
> new remove test

- conans/util/files.py
Partially Address #1240 
A probable cause of issue reported by @tru in the slack channel.
> Raise on tgzerror

- conans/client/file_copier.py
- conans/client/remote_manager.py
- conans/model/manifest.py
- conans/test/functional/tgz_md5_test.py
- conans/test/integration/symlinks_test.py
This would be the solution to https://github.com/conan-io/conan/issues/1237
But please read my concerns in the issue, regarding possible breaking behavior, and requesting feedback.
> working folder symlinks

- conans/client/deps_builder.py
- conans/test/integration/conanfile_errors_test.py
- conans/test/integration/conanfile_exception_test.py
- conans/test/integration/profile_requires_test.py
- conans/util/files.py
Address: https://github.com/conan-io/conan/issues/1282
As well as fixes the tar error_level issues for Win10
> using env-vars for configure and requirements

- conans/model/options.py
- conans/test/integration/options_caching_test.py
Should address: https://github.com/conan-io/conan/issues/1296
> parsing options with equal in value

- conans/test/command/export_dirty_test.py
- conans/util/files.py
To address: https://github.com/conan-io/conan/issues/856
Ugly, but don't know any other workaround.
> fixing failing removals in window

- conans/client/rest/cacert.py
Address: https://github.com/conan-io/conan/issues/1302
> fix cacert CONAN_USER_HOME

- conans/client/conf/__init__.py
This PR add support for GCC 7.1 in default settings file.
> Add support for GCC 7.1

- conans/client/export.py
- conans/client/file_copier.py
- conans/client/importer.py
- conans/client/loader.py
- conans/client/loader_parse.py
- conans/test/functional/conanfile_loader_test.py
- conans/test/functional/imports_folders_tests.py
- conans/test/functional/imports_tests.py
To improve: https://github.com/conan-io/conan/issues/1316
Implements also: https://github.com/conan-io/conan/issues/1334
> folder option to imports

- conans/requirements_osx.txt
Solves: https://github.com/conan-io/conan-package-tools/issues/68,
> Upgrade SSL osx requirments

- conans/client/new.py
- conans/test/command/new_test.py
Address: https://github.com/conan-io/conan/issues/1356
> fix command new with short package name

- conans/client/command.py
- conans/client/manager.py
- conans/test/command/package_files_test.py
Address https://github.com/conan-io/conan/issues/1361
> adding the recipe hash when package_files

- conans/client/configure_build_environment.py
Complements https://github.com/conan-io/conan/pull/1324 (by @absassi) for issue #1322
> strip trailing slash in AutotoolsEnv configure_dir

- conans/tools.py
Address: https://github.com/conan-io/conan/issues/1326
> ftp download tool

- conans/client/conf/__init__.py
- conans/client/linter.py
- conans/client/packager.py
- conans/test/command/export_linter_test.py
https://github.com/conan-io/conan/issues/1283
> linter discard dynamic fields, also Werr

- conans/__init__.py
- conans/client/remote_registry.py
- conans/test/functional/registry_test.py
NOT to merge, just to pass CI before minor
> new bintray default repos instead of deprecated conan.io

- conans/build_info/command.py
- conans/build_info/conan_build_info.py
- conans/build_info/model.py
- pyinstaller.py
Address: https://github.com/conan-io/conan/issues/1409
Tested in Win, installers should be checked in next release for conan_build_info app
> pyinstaller do conan_build_info

- conans/client/loader_parse.py
- conans/test/generators/custom_generator_test.py
Address https://github.com/conan-io/conan/issues/1421
> user generators with underscore

- conans/client/manager.py
- conans/test/integration/symlinks_test.py
- latest
Address https://github.com/conan-io/conan/issues/1312
> package_file command with symlinks

- conans/tools.py
This lets us use `tools.SystemPackageTool` on our machines.
> Add 'rhel' to the list of distros that use yum

- conans/client/new.py
Address https://github.com/conan-io/conan/issues/1442
> removed shared mgmt in conan new template

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/conan_command_output.py
- conans/test/utils/tools.py
> conan api returns and refactored outputer

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/client/proxy.py
- conans/client/remote_manager.py
- conans/client/uploader.py
- conans/test/command/upload_test.py
Address: https://github.com/conan-io/conan/issues/1207
> make packaeg upload integrity check opt-in

- conans/client/proxy.py
- conans/test/integration/multi_remote_test.py
Address: https://github.com/conan-io/conan/issues/1457
> allowing add_ref before download to predefine remote

- conans/test/functional/settings_constraint_test.py
Address: https://github.com/conan-io/conan/issues/1298
> new test to ensure constraints work for default settings

- conans/client/cmake.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/test/command/build_test.py
- conans/test/integration/cmake_install_package_test.py
https://github.com/conan-io/conan/issues/1343
> cmake.package() and conan build --package_folder

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/test/command/install_test.py
- conans/test/command/test_package_test.py
> smarter test_package version, user, channel management

- conans/client/generators/__init__.py
- conans/test/integration/only_source_test.py
- conans/test/libcxx_setting_test.py
This just fixes a little typo.
It makes me cringe whenever I see it in conan's output. 😆
> Fix a typo in generator output

- conans/client/linter.py
- conans/test/command/export_linter_test.py
> Linter catch em all and build_requires

- conans/client/build_requires.py
- conans/client/generators/cmake.py
- conans/client/generators/cmake_common.py
- conans/client/generators/cmake_multi.py
- conans/client/generators/scons.py
- conans/client/generators/text.py
- conans/client/installer.py
- conans/client/loader.py
- conans/migrations.py
- conans/model/build_info.py
- conans/model/conan_file.py
- conans/model/conan_generator.py
- conans/model/env_info.py
- conans/model/user_info.py
- conans/test/command/build_test.py
- conans/test/functional/user_info_test.py
- conans/test/generators/cmake_test.py
- conans/test/integration/diamond_test.py
- conans/test/model/build_info_test.py
- In txt generator (conanbuildinfo.txt)
- In Cmake generator (simple and multi)
Propagated vars but always scoped to the package. Moved DepsCPPInfo loads to TXTGenerator loads.
#1100
> User info vars

- conans/client/command.py
- conans/client/deps_builder.py
- conans/client/manager.py
- conans/test/command/install_cwd_test.py
- conans/test/integration/alias_test.py
- conans/test/integration/conan_link_test.py
Base for https://github.com/conan-io/conan/issues/798 as well as other "latest version" approaches.
Might help @claasd with https://github.com/conan-io/conan/issues/1373
> conan alias 

- conans/client/proxy.py
Address #1492 - Don't make me think philosophy
> Not found in local cache

- conans/tools.py
See #1509.
I added those functions from `util.files` to `tools` that I think make sense from a conan user's point of view. There will be a separate pull request to the docs repo that adds documentation for them.
> Make some more file utils public

- conans/client/build_requires.py
- conans/client/cmake.py
- conans/client/command.py
- conans/client/migrations.py
- conans/test/command/create_test.py
- conans/test/command/search_test.py
- Also bug with build_requires in test_package project with conan create
> pipotux feedback

- conans/client/rest/uploader_downloader.py
Progress bars are not being displayed in some cases
> displaying bars when length=0

- conans/client/new.py
> Add description to new conanfile.

- conans/client/loader.py
- conans/test/integration/test_package_config_test.py
Address https://github.com/conan-io/conan/issues/1560
> test_package fix so it doesn't remove the package option

- conans/server/conf/default_server_conf.py
> Change comment in server.conf

- conans/client/command.py
- conans/test/command/search_test.py
> Fixed search with wildcard in version

- conans/tools.py
> Accept 100 return code from yum check-update

- conans/client/linter.py
- conans/test/command/export_linter_test.py
> Fixed linter false Warning (self.info)

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/remote_registry.py
- conans/test/command/remote_test.py
> remote update with position

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/printer.py
- conans/client/profile_loader.py
- conans/model/env_info.py
- conans/model/options.py
- conans/model/scope.py
- conans/test/command/profile_test.py
> Profile edit + fixed error printing double messages + fixed profile show

- conans/client/command.py
- conans/client/migrations.py
> Better message and exception managing for very old versions

- conans/model/conan_file.py
Error was misleading, the check is for the lib folder not the package folder.
> Fixed error message : "Package" -> "Lib"

- conans/client/export.py
- conans/test/command/export_test.py
Address https://github.com/conan-io/conan/issues/1589
> removing export_source folder for read-only files

- conans/client/generators/visualstudio.py
https://github.com/conan-io/conan/issues/1606
> remove ExecutablePath assignment in VS generator

- conans/client/file_copier.py
- conans/test/command/export_test.py
Address: https://github.com/conan-io/conan/issues/1586
> fixed file copier

- conans/client/conf/__init__.py
> Add GCC 7.2

- conans/client/new.py
https://github.com/conan-io/conan/issues/1652
> test template import shared .so in linux

- conans/client/manager.py
- conans/test/command/package_files_test.py
- conans/test/functional/profile_loader_test.py
There was a bug in package_files, it didn't check short_paths
> make package_files command work with short_paths too

- conans/client/conan_api.py
- conans/client/conf/__init__.py
- conans/client/rest/cacert.py
- conans/paths.py
> Conan user home and storage path improvements

- conans/test/functional/conanfile_loader_test.py
- conans/test/integration/build_id_test.py
https://github.com/conan-io/conan/issues/1645
> adding new short_paths and create with build_id() tests

- conans/client/manager.py
- conans/model/build_info.py
- conans/test/command/create_test.py
Should address https://github.com/conan-io/conan/issues/1667
> injecting missing require in test_package/conanfile build()

- conans/client/rest/auth_manager.py
To know if the token has expired somehow.
> add log line

- conans/client/export.py
- conans/client/remote_manager.py
- conans/client/rest/rest_client.py
- conans/test/command/upload_complete_test.py
- conans/test/command/upload_test.py
https://github.com/conan-io/conan/issues/1663
> avoiding unnecessary uploads

- conans/client/detect.py
This will better cover https://github.com/conan-io/conan/issues/1417
> using env-var for detection of vs 15

- conans/test/integration/conan_env_test.py
This test illustrate how env-vars are joined with ``os.pathsep`` which works well for PATH and paths in general, but might fail for other kind of env-vars (CXXFLAGS and others). Not sure about the approach, but at least we should consider it.
> checking order of env-vars

- conans/client/conf/__init__.py
- conans/client/generators/cmake.py
- conans/client/generators/qbs.py
- conans/client/generators/qmake.py
- conans/client/generators/text.py
- conans/client/generators/visualstudio.py
- conans/client/importer.py
(and added missing pylintrc to the conan.conf default)
> Rename confusing deps_cpp_info to cpp_info

- conans/tools.py
optionally, if strict flag is given, it raises exception
#1694
> replace_in_file displays a warning if search pattern wasn't found

- conans/client/manager.py
- conans/test/command/build_test.py
- conans/test/command/imports_test.py
- conans/test/command/package_test.py
Address https://github.com/conan-io/conan/issues/1636
> conan package now uses cached options

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/source.py
- conans/test/command/source_test.py
Added cwd parameter and fixed current directory for local source method
> Source local method improvements

- conans/model/settings.py
- conans/test/model/settings_test.py
Partly help with https://github.com/conan-io/conan/issues/1730
> operator 'in' for settings values

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/conf/config_installer.py
- conans/client/remote_registry.py
- conans/test/command/config_install_test.py
- conans/test/functional/cmake_test.py
- conans/test/util/output_test.py
- conans/test/util/tools_test.py
- conans/tools.py
Proposal for ``config install``
Might be a solution for: https://github.com/conan-io/conan/issues/1692
Also, possible solution to: https://github.com/conan-io/conan/issues/1581
> Conan config install command

- conans/client/client_cache.py
- conans/client/conf/__init__.py
- conans/client/installer.py
- conans/paths.py
- conans/test/functional/path_limit_test.py
- conans/util/windows.py
Address https://github.com/conan-io/conan/issues/1662
Includes some refactor of the ugly Win stuff
> making short paths configurable in Win with env-var CONAN_USER_HOME_SHORT

- conans/client/loader.py
- conans/model/conan_file.py
- conans/test/functional/in_local_cache_test.py
> In local cache flag

- conans/client/require_resolver.py
- conans/test/model/version_ranges_test.py
Related to (not a fix) : https://github.com/conan-io/conan/issues/1743
> new version-range test

- .ci/appveyor/install.bat
- .ci/appveyor/test.bat
- .ci/travis/run.sh
- conans/test/server/utils/server_launcher.py
Big improvement in Windows. Not bad in linux, still unknown in OSX
> nosetests multiprocess CI

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/conan_command_output.py
- conans/test/command/profile_test.py
> Conan profile get key

- conans/client/migrations.py
- conans/client/remote_manager.py
- conans/paths.py
- conans/server/conf/__init__.py
- conans/test/remove_old_export_sources_layout_test.py
- kept client compatibility being able to uncompress tgz with .c_src
- Removed tgz creation with .c_src
> Do not upload tgzs with .c_src

- conans/client/tools/win.py
- conans/test/util/build_sln_command_test.py
> - add parallel option to build_sln_command

- conans/client/rest/uploader_downloader.py
- conans/client/tools/net.py
- conans/test/util/tools_test.py
> - add overwrite parameter to tools.download

- conans/client/rest/uploader_downloader.py
- conans/util/files.py
- Appending to an open handler (not open/close)
- Checking total size
> Check if completion and more efficient append

- conans/client/rest/rest_client.py
- conans/client/rest/version_checker.py
- conans/server/rest/controllers/users_controller.py
#1832 and removed confusing deprecated message from totally ok servers like Artifactory/Bintray
> Fixed response in auth and removed confusing log

- conans/client/rest/uploader_downloader.py
- conans/client/tools/net.py
- conans/test/util/tools_test.py
> Basic auth and headers exposed to tools.download

- conans/client/cmake.py
allow to specify custom toolset for CMake generator, mainly feature is targeted for Visual Studio generators, although there might be other generators supporting it, I just don't know em 
* one use case is to use Clang based toolset (such as LLVM one or Microsoft Clang/C2)
* another use case is to use toolsets with Windows XP support (e.g. v140_xp)
* Windows Driver Kit has its own toolset as well (not sure if any driver developers use conan btw)
* Intel compiler is another one (although not supported by Conan yet)
> - add toolset parameter to CMake helper

- conans/client/tools/system_pm.py
do not run SystemPackageTool with sudo if we already running as root
useful if calling conan inside Docker
> - do not use sudo if we already running as root

- conans/client/command.py
- conans/client/proxy.py
- conans/client/require_resolver.py
- conans/test/model/version_ranges_test.py
Related to: https://github.com/conan-io/conan/issues/1479
> docstring and help for search --case-sensitive

- conans/client/new.py
https://github.com/conan-io/conan/issues/1880
> making new --bare use new collect_libs

- conans/client/generators/cmake.py
- conans/client/tools/files.py
- conans/test/integration/diamond_test.py
- conans/test/util/output_test.py
Can solve https://github.com/conan-io/conan/issues/1904
> tools.unzip unnecessary short_paths check

- conans/client/conan_api.py
- conans/test/command/profile_test.py
Partially address: https://github.com/conan-io/conan/issues/1910
> fixed profile list

- conans/client/conan_api.py
- conans/client/rest/rest_client.py
- conans/client/uploader.py
- conans/model/ref.py
- conans/test/command/upload_test.py
Address https://github.com/conan-io/conan/issues/1779
> upload pattern fix

- pyinstaller.py
Should address https://github.com/conan-io/conan/issues/1868
> fixed pyinstaller hidden import

- conans/client/packager.py
- conans/test/command/build_test.py
- conans/test/command/create_test.py
- conans/test/functional/folders_access_test.py
Fixed tests, and removed duplicated tests lines, `folder_access_tests` covers all cases.
> Changed curdir in package()

- conans/client/configure_build_environment.py
- conans/client/tools/oss.py
- conans/test/functional/autotools_configure_test.py
I tried with some recipes from myself and looks Autotools is working ok passing the build/host like it's crossbuilding to x86. #1468
> x86 is not cross building

- conans/client/new_ci.py
> Added xcode9 for apple-clang 9.0

- conans/client/command.py
From https://github.com/conan-io/docs/issues/199
> better --build

- conans/client/command.py
- conans/client/conan_api.py
- conans/test/command/create_test.py
https://github.com/conan-io/conan/issues/1913
> adding werror to create

- conans/test/command/install_test.py
- conans/test/generators/xcode_gcc_vs_test.py
https://github.com/conan-io/conan/issues/1892
Also a refactor of a very ugly and old test.
> new test so package_info not executed at conan install

- conans/client/command.py
- conans/client/conan_api.py
- conans/test/command/build_test.py
- conans/test/command/package_test.py
- conans/test/integration/devflow_test.py
--package-folder now is relative to cwd and only defaulted to --build-folder/package
Also some adjustments in the help messages.
> Changed --package-folder behavior

- conans/client/cmake.py
- conans/test/functional/cmake_test.py
I don't have a windows machine right now to test this with VS.
Can someone please give me some feedback on how I can write a test for this?
> Read toolset value from environment variable

- conans/client/command.py
Improves: https://github.com/conan-io/conan/pull/1931
Also for: https://github.com/conan-io/conan/issues/1787
> improve some help strings

- conans/client/tools/system_pm.py
Update warning message containing supported package managers to also show pacman.
> List pacman as a supported package manager

- conans/client/profile_loader.py
- conans/test/integration/profile_test.py
- conans/test/model/profile_test.py
> Profile file with lines only with spaces

- conans/client/command.py
- conans/test/command/source_test.py
#1972 was just the tip of the iceberg.
> Not repeated arguments

- conans/test/model/version_ranges_test.py
https://github.com/conan-io/conan/issues/1791
> more version ranges tests

- conans/client/manager.py
- conans/test/command/create_test.py
https://github.com/conan-io/conan/issues/1956
> don't rebuild conan created pkg because build_policy=always

- conans/client/build/autotools_environment.py
- conans/test/functional/autotools_configure_test.py
> Autotools fix

- conans/client/build/cmake.py
- conans/test/functional/cmake_test.py
> - CMake parallel build for Visual Studio

- conans/client/conan_api.py
- conans/client/importer.py
- conans/client/installer.py
- conans/test/functional/deploy_test.py
- conans/test/functional/folders_access_test.py
#1969 and folders in package_info() always None except self.package
> install-folder in deploy and controlled folders presence in package_info

- conans/client/build/cmake.py
- conans/test/functional/cmake_test.py
> - fix CMake.test() for Ninja generator

- conans/client/cmd/copy.py
- conans/client/command.py
- conans/test/command/copy_packages_test.py
- conans/test/functional/path_limit_test.py
- conans/test/integration/symlinks_test.py
https://github.com/conan-io/conan/issues/2017
> fixed copy command, now able to not copy binaries

- conans/client/conf/config_installer.py
- conans/test/command/config_install_test.py
- conans/test/functional/cmake_test.py
https://github.com/conan-io/conan/issues/1951
> not remove zip if conan config install local-zip

- conans/client/tools/__init__.py
- conans/client/tools/pkg_config.py
- conans/test/util/pkg_config_test.py
tool.PkgConfig helper to obtain various properties from pkg-config
> - tools.PkgConfig helper

- conans/client/command.py
- conans/client/conan_api.py
https://github.com/conan-io/conan/issues/1971
> fixed type in api download

- conans/client/cmd/copy.py
- conans/client/proxy.py
- conans/test/command/upload_test.py
- conans/test/integration/export_sources_test.py
- conans/test/utils/tools.py
https://github.com/conan-io/conan/issues/2003
> complete sources not necessary if not exports_sources

- conans/client/importer.py
- conans/client/installer.py
- conans/model/conan_file.py
- conans/test/functional/imports_tests.py
https://github.com/conan-io/conan/issues/1893
> adding self.keep_imports feature

- conans/client/tools/oss.py
> - auto-detect MSYS2 (for system package tool)

- conans/requirements.txt
https://github.com/conan-io/conan/issues/2058
> workaround MSYS2 issue with psutil

- conans/__init__.py
- conans/server/conf/__init__.py
- conans/test/util/tools_test.py
Reproduced with some py3 versions.
> Encoding issues

- conans/requirements.txt
- conans/util/locks.py
https://github.com/conan-io/conan/issues/2066
https://github.com/conan-io/conan/issues/2058
> reverted locks

- conans/client/tools/system_pm.py
- conans/test/util/tools_test.py
> - disable sudo on Windows

- conans/client/tools/net.py
https://github.com/conan-io/conan/issues/1682
> added destination arg to tools.get

- conans/client/build_requires.py
- conans/test/integration/build_requires_test.py
https://github.com/conan-io/conan/issues/2085
> remove self build requires

- conans/test/functional/build_environment_helpers_test.py
https://github.com/conan-io/conan/issues/2099
> fixed broken VS test due to typo and bad filename

- README.rst
> Readme change

- conans/client/build/cmake.py
- conans/test/functional/cmake_test.py
> Do not use cores if visual < 10

- conans/client/generators/cmake_common.py
> added skip install path by default

- conans/client/cmd/new.py
- conans/client/generators/virtualenv.py
https://github.com/conan-io/conan/issues/2122
> removing conanfile_directory from new

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/deps_builder.py
- conans/client/output.py
- conans/client/require_resolver.py
- conans/model/options.py
- conans/test/command/create_test.py
- conans/test/integration/conflict_diamond_test.py
- conans/test/integration/version_ranges_conflict_test.py
- conans/test/model/options_test.py
- conans/test/model/transitive_reqs_test.py
- conans/test/model/version_ranges_test.py
https://github.com/conan-io/conan/issues/2004
> force werror

- conans/client/generators/__init__.py
- conans/test/generators/generators_test.py
https://github.com/conan-io/conan/issues/2132
> raising error instead of warn when bad generator

- conans/client/command.py
- conans/client/conan_api.py
- conans/test/command/info_test.py
- conans/test/integration/build_id_test.py
- conans/test/integration/package_info_test.py
#1932
Also a test of package_info() to ensure some discussion with solvingj not related with the #1932
> Conan info command reading info files

- conans/client/manager.py
- conans/test/command/create_test.py
- conans/test/command/test_package_test.py
- conans/test/integration/cmake_install_package_test.py
- conans/test/integration/manifest_validation_test.py
- conans/test/integration/profile_build_requires_test.py
- conans/test/integration/test_package_config_test.py
https://github.com/conan-io/conan/issues/2192
> changed scoped msg for test-package

- conans/client/command.py
https://github.com/conan-io/conan/issues/2203
> improved help message

- conans/test/build_helpers/meson_test.py
> Fix meson test generating build folders in conan sourcetree

- README.rst
- Added jenkins badges
- Removed travis and appveyor ones
> Added jenkins badges to README

- conans/test/integration/diamond_test.py
The last refactor of "conan install ." broke my PreFlight test, because the `path` is supposed to be passed in the `install` argument, not always. I'll open the same PR for the beta3. 
I want this now merged to develop to have a green build.
> Fix diamond test function

- conans/test/integration/diamond_test.py
Same as #2220 for the release branch
> Fix diamond tests

- conans/client/cmd/new_ci.py
https://github.com/conan-io/conan/issues/2215
> removed VS150comntools from new-ci

- conans/client/command.py
- conans/test/command/build_test.py
- conans/test/command/export_pkg_test.py
- conans/test/command/info_folders_test.py
- conans/test/command/info_test.py
- conans/test/command/package_test.py
- conans/test/command/source_test.py
- conans/test/command/upload_complete_test.py
- conans/test/command/upload_test.py
- conans/test/functional/in_local_cache_test.py
- conans/test/integration/cmake_folders_test.py
- conans/test/integration/devflow_test.py
Docs PR: https://github.com/conan-io/docs/pull/445
> Remove underscore parameters in commands

- conans/client/profile_loader.py
- conans/test/command/profile_test.py
- conans/test/functional/conan_settings_preprocessor_test.py
- conans/test/functional/proxies_conf_test.py
- conans/test/integration/profile_test.py
- conans/test/utils/tools.py
Removed in testing the auto-creation of the profile that can hide bugs in the real client.
> Fix default profile creation

- conans/client/conf/__init__.py
> Added same archs to target

- conans/client/cmd/new.py
- conans/model/info.py
- conans/test/integration/package_id_test.py
> Package id and build settings

- conans/client/printer.py
- conans/test/command/profile_test.py
https://github.com/conan-io/conan/issues/2268
Docs: https://github.com/conan-io/docs/pull/465
> fix profile show to match profile format

- conans/client/manager.py
- conans/test/command/download_test.py
> Download at least recipe in conan download command

- conans/client/cmd/new.py
> Not run the test example when cross building

- conans/client/proxy.py
- conans/test/integration/multi_remote_test.py
- conans/test/integration/version_check_test.py
> Fail when getting a recipe from remote raises error != 404

- conans/client/manager.py
- conans/test/command/install_test.py
> Fixing cross building message

- conans/__init__.py
- conans/client/generators/cmake_common.py
- conans/client/tools/env.py
- conans/client/tools/files.py
- conans/client/tools/win.py
- conans/test/util/tools_test.py
> CI: Release/1.0.0

- conans/client/conf/__init__.py
https://github.com/conan-io/conan/issues/2299
> add more arch_build values

- conans/client/command.py
- conans/client/manager.py
https://github.com/conan-io/docs/issues/481
> fixed underscores

- conans/client/build/autotools_environment.py
- conans/client/tools/env.py
- conans/client/tools/files.py
- conans/client/tools/oss.py
- conans/client/tools/win.py
- conans/test/util/tools_test.py
Added new tests here: https://github.com/conan-io/test/blob/master/conan/external_tools/run_in_windows_bash_test.py
> Using unix paths when needed

- conans/client/client_cache.py
- conans/client/profile_loader.py
- conans/test/integration/profile_test.py
- conans/test/model/profile_test.py
> Env including default fixed and inheritance fixed

- pyinstaller.py
https://github.com/conan-io/conan/issues/2354
> fix win pyinstaller metadata

- conans/client/cmd/test.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/installer.py
- conans/client/manager.py
- conans/test/command/create_test.py
https://github.com/conan-io/conan/issues/2044
> implemented conan create --keep-build

- conans/test/command/source_test.py
https://github.com/conan-io/conan/issues/2327#issuecomment-359257413
My only concern with this PR if it really deserves to be added such a test.
> added new test to show local patch in source()

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> fixed nmake parallel (from cmake)

- conans/client/deps_builder.py
- conans/model/options.py
- conans/test/command/install_test.py
- conans/test/model/options_test.py
- pyinstaller.py
https://github.com/conan-io/conan/issues/2393
https://github.com/conan-io/conan/issues/2391
> fix options definitions with patterns

- conans/model/options.py
- conans/test/command/install_test.py
- conans/test/model/options_test.py
> fixed dict order for options

- conans/client/generators/text.py
- conans/model/build_info.py
- conans/test/sysroot_test.py
Includes a failing test, fix still under development.
cc/ @theodelrieu (many thanks!)
> failing test for sysroot

- conans/client/command.py
- conans/client/conan_api.py
- conans/test/command/create_test.py
> 2355 feature/skip testing when create

- conans/client/deps_builder.py
- conans/model/conan_file.py
- conans/test/integration/profile_build_requires_test.py
- conans/test/utils/python_test_files.py
Some other features claims for better python code reusing. Lately, we kind of decided to promote the "tool" way of reuse python instead of the inheritance, so it reduces the necessary lines of code.
#https://github.com/conan-io/docs/pull/479
fixes #1037
> Automatically apply pythonpath

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> - specify -m32/-m64 to CMake in case of MinGW as well

- conans/client/conf/detect.py
https://github.com/conan-io/docs/pull/519
> Warn for libcxx gcc abi

- conans/client/conf/__init__.py
> Add gcc 7.3

- setup.py
> updating setup.py

- conans/test/util/tools_test.py
- conans/tools.py
- conans/util/env_reader.py
fixes #2427 
references conan-io/docs#511
> Added get_env in conans/tools.py to be available in final conanfile.py

- conans/client/command.py
- conans/test/command/help_test.py
Docs: https://github.com/conan-io/docs/pull/534
> adding new help command

- conans/client/generators/visualstudio.py
> adding information to ResourceCompile VS generator

- conans/client/remote_registry.py
- conans/test/functional/registry_test.py
> Removed conan-transit from default registry

- conans/client/conf/__init__.py
> Add GCC 5.5 to default configuration

- conans/client/installer.py
- conans/test/integration/package_id_test.py
https://github.com/conan-io/docs/pull/549
> Package ID in the missing msg

- conans/client/manager.py
- conans/test/command/export_pkg_test.py
> set develop=True for export-pkg

- conans/client/generators/cmake_common.py
> disabling cmake compiler check for unknown compilers

- conans/__init__.py
- conans/client/cmd/test.py
- conans/client/manager.py
- conans/test/integration/same_userchannel_test.py
> adding user and channel to test_package/conanfile

- conans/client/build/autotools_environment.py
- conans/test/build_helpers/autotools_configure_test.py
> Not eabi for x86

- conans/client/build/msbuild.py
- conans/client/tools/win.py
- conans/test/util/build_sln_command_test.py
> output errors for invalid platforms

- conans/requirements_dev.txt
- conans/test/command/create_test.py
- conans/test/command/export_pkg_test.py
- conans/test/command/export_test.py
- conans/test/command/package_test.py
- conans/test/conan_api/manifests_arguments_test.py
- conans/test/functional/deploy_test.py
- conans/test/functional/develop_test.py
- conans/test/generators/visual_studio_multi_test.py
- conans/test/integration/build_id_test.py
- conans/test/integration/build_requires_test.py
- conans/test/integration/cmake_folders_test.py
- conans/test/integration/complete_test.py
- conans/test/integration/export_sources_test.py
- conans/test/integration/manifest_validation_test.py
- conans/test/integration/profile_test.py
- conans/test/integration/version_ranges_diamond_test.py
- conans/test/model/version_ranges_test.py
- conans/test/util/conanfile_tools_test.py
"The nose-parameterized package is deprecated and has been renamed to parameterized."
> Switch from nose-parameterized to parameterized

- conans/client/cmd/profile.py
- conans/model/env_info.py
- conans/test/command/profile_test.py
> fix profile update for env-vars

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/client/packager.py
- conans/test/command/export_pkg_test.py
Docs in: https://github.com/conan-io/docs/pull/564
Close #2350
> add --package-folder to export-pkg

- conans/client/generators/__init__.py
- conans/client/generators/json_generator.py
- conans/test/generators/json_test.py
- conans/test/integration/json_generator_test.py
> Add a json generator

- conans/__init__.py
- conans/client/build/autotools_environment.py
- conans/client/build/compiler_flags.py
- conans/client/build/msbuild.py
- conans/client/build/visual_environment.py
- conans/client/generators/compiler_args.py
- conans/client/tools/win.py
- conans/test/build_helpers/autotools_configure_test.py
- conans/test/build_helpers/compiler_flags_test.py
- conans/test/build_helpers/visual_environment_test.py
- conans/test/generators/compiler_args_test.py
- conans/test/util/build_sln_command_test.py
- Fix visual studio flags using Autotools.
> Not Merge: Release 1.1.1

- conans/client/cmd/search.py
- conans/test/command/search_test.py
> fixed bug in search pkg-ref output

- conans/client/runner.py
- conans/test/functional/runner_test.py
- conans/test/utils/runner.py
> Bug printing to StringIO in python2

- conans/client/tools/win.py
- conans/test/util/tools_test.py
> no-op if not Windows in tools.vcvars()

- conans/client/build/autotools_environment.py
- conans/client/build/cmake.py
- conans/client/build/meson.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/model/conan_file.py
- conans/test/build_helpers/autotools_configure_test.py
- conans/test/build_helpers/cmake_test.py
- conans/test/build_helpers/meson_test.py
- conans/test/command/build_test.py
- conans/test/utils/conanfile.py
> implemented build() stages arguments

- conans/client/manager.py
- conans/test/command/source_test.py
Address: https://github.com/conan-io/conan/issues/2327
> doing an exports while conan-source

- conans/test/command/info_folders_test.py
- conans/util/windows.py
> CONAN_USER_HOME_SHORT cygwin/msys2 access problems

- conans/client/printer.py
- conans/test/integration/private_deps_test.py
> Better output if recipe found but not the package

- conans/test/conanfile_extend_test.py
Adding a test to reuse python subclass of a ConanFile from another python file. A test like this one was missing in the codebase.
> Added test reusing ConanFile from python file

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/test/command/download_test.py
> conan download --recipe param and test

- conans/client/command.py
- conans/test/command/install_test.py
> conan install parser nargs changed to ? and addded tests

- conans/client/manager.py
- conans/client/proxy.py
- conans/test/command/user_test.py
> 2290 show users for given remote

- conans/client/build/cppstd_flags.py
- conans/test/build_helpers/cpp_std_flags_test.py
Close #2596
Important to check possible implications of the bugfix regarding package ids.
> fix cppstd defaults for clang 6.0 + fix bug with defaults

- conans/client/conan_api.py
- conans/client/conf/config_installer.py
- conans/client/runner.py
- conans/test/command/config_install_test.py
> raise error if git clone fails in conan-config-install

- conans/client/deps_builder.py
- conans/test/integration/alias_test.py
- conans/test/model/transitive_reqs_test.py
Might address:
- https://github.com/conan-io/conan/issues/2583
- https://github.com/conan-io/conan/issues/2576
Alternative to PR: https://github.com/conan-io/conan/pull/2586/files
> Fixing diamonds with alias

- conans/client/installer.py
- conans/client/tools/env.py
- conans/model/env_info.py
- conans/test/integration/python_build_test.py
Close #2644
I have done some performace checks, everything looks good. Did some small optimizations.
> added pythonpath to package_info() call

- conans/test/integration/cmake_flags_test.py
To complement https://github.com/conan-io/conan/pull/2555
> cmake escape integration test

- conans/client/conf/__init__.py
- conans/client/rest/auth_manager.py
- conans/test/command/upload_test.py
- conans/test/command/user_test.py
> Preliminary support for disabling login prompt (#2502)

- conans/client/file_copier.py
- conans/client/importer.py
- conans/test/functional/deploy_import_file_permission_test.py
> Preliminary support for writable files from deploy and imports (#2441)

- conans/client/cmd/new.py
- conans/model/conan_file.py
Need to add this to the changelog.
> Make conanfile templates PEP8 compliant and added ConanFile docstrings

- conans/client/installer.py
- conans/client/manifest_manager.py
- conans/errors.py
To improve over https://github.com/conan-io/conan/issues/2641
> improved messages, fix manifest exceptions

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> Fix CONAN_CMAKE_SYSTEM_PROCESSOR

- conans/client/action_recorder.py
- conans/client/conan_command_output.py
- conans/test/command/json_output_test.py
- Dates in output json should be in ISO 8601
> json times in iso

- conans/client/cmd/export_linter.py
> fixing py34 pylint

- conans/test/command/user_test.py
> fixed py34 test (order output)

- conans/client/remote_manager.py
- conans/util/files.py
Minor refactor related to https://github.com/conan-io/conan/issues/2729
> minor refactor to touch

- conans/client/client_cache.py
- conans/client/cmd/search.py
- conans/client/cmd/uploader.py
- conans/client/proxy.py
- conans/client/remote_manager.py
- conans/client/remover.py
- conans/client/rest/auth_manager.py
- conans/client/rest/rest_client.py
- conans/server/rest/controllers/conan_controller.py
- conans/test/functional/remote_manager_test.py
- conans/test/integration/manifest_validation_test.py
- conans/test/remote/auth_bearer_test.py
- conans/test/remote/rest_api_test.py
> renamed digest

- conans/client/tools/files.py
Implements #2741 
Change the used unit size from 1024 to 1000
> Issue #2741 - Change unit size to 1000 instead of 1024

- conans/util/windows.py
> fixed cacls without USERDOMAIN

- conans/client/command.py
> Adds -ks for --keep-source option

- conans/client/proxy.py
> dead code from previous merge

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/remote_registry.py
- conans/test/command/remote_test.py
> Support for renaming a remote #2618

- conans/client/remote_registry.py
- conans/test/command/remote_test.py
> fixed issue with remote rename

- conans/client/conan_api.py
- conans/test/conan_api/curdir_kept_test.py
> fixed curdir

- conans/client/rest/rest_client.py
- conans/test/command/upload_test.py
> Dont ERROR if remote package not exists for upload --no-overwrite

- conans/client/file_copier.py
- conans/client/packager.py
- conans/test/build_helpers/msbuild_test.py
- conans/test/command/create_test.py
- conans/test/command/export_pkg_test.py
- conans/test/command/package_test.py
- conans/test/functional/conan_trace_file_test.py
- conans/test/functional/deploy_test.py
- conans/test/functional/imports_tests.py
- conans/test/integration/complete_test.py
>  Improved warning and copy messages for package()

- conans/client/graph/graph_builder.py
- conans/client/graph/require_resolver.py
- conans/client/manager.py
- conans/test/model/transitive_reqs_test.py
- conans/test/model/version_ranges_test.py
This does the same refactor than a previous PR, moving the ``update`` from a class attribute to a function argument call.
> remove RequireResolver update from ctor

- conans/client/generators/cmake.py
- conans/test/generators/cmake_test.py
- conans/test/integration/cmake_flags_test.py
- conans/test/integration/cmake_targets_test.py
> fixed more escapes in cmake generator

- conans/client/cmd/new.py
- conans/client/cmd/new_ci.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/test/command/new_test.py
Hi!
This PR solves the issue #2359 
I added the template to fill Linux and Mac support. However, I think Mac will be rarely used, because it's paid.
The PR with docs update is here: https://github.com/conan-io/docs/pull/636
Regards!
> CircleCI support (#2359)

- conans/client/build/autotools_environment.py
- conans/client/build/compiler_flags.py
- conans/client/build/meson.py
- conans/client/build/msbuild.py
- conans/client/build/visual_environment.py
- conans/client/conf/__init__.py
- conans/client/generators/compiler_args.py
- conans/test/build_helpers/autotools_configure_test.py
- conans/test/build_helpers/compiler_flags_test.py
- conans/test/build_helpers/msbuild_test.py
- conans/test/build_helpers/visual_environment_test.py
- conans/test/generators/compiler_args_test.py
- conans/test/util/build_sln_command_test.py
- conans/test/utils/conanfile.py
Introduced also to debug and release the optimization flags that were missing.
> New build types and flag management

- conans/client/generators/pkg_config.py
- conans/test/generators/pkg_config_test.py
> Fix abs paths with pkg_config generator

- conans/client/runner.py
- conans/test/util/conanfile_tools_test.py
- conans/tools.py
> restored the save() method with append argument, broken API

- conans/client/cmd/new_ci.py
- Updated travis CI tempalte with apple-clang 9.1 / xcode 9.3. This is not supported in circle-ci yet: https://circleci.com/docs/1.0/build-image-macos/
- Added apple-clang 7.3 / xcode 7.3 for circle-ci
> updated apple-clang in ci scripts

- conans/client/build/compiler_flags.py
- conans/test/build_helpers/visual_environment_test.py
> fix VisualStudioBuildEnvironment build type flags with toolset

- conans/__init__.py
- conans/client/remote_manager.py
- conans/test/functional/tgz_md5_test.py
> checking tgz checksum

- conans/client/build/msbuild.py
- conans/test/build_helpers/msbuild_test.py
> Fixed VisualStudioBuildEnvironment flags in MSBuild during props template generation

- conans/test/util/tools_test.py
- conans/util/files.py
https://github.com/bincrafters/conan-vorbis/pull/6
> fixing some unicode

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> CMAKE_SYSTEM_VERSION following Android api_level

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
- conans/test/integration/cmake_flags_test.py
The #2758 issue mentioned another issue about a conanfile.txt installing with no settings, but can't be reproduced.
No docs are required
> Fixed CMake without settings

- conans/model/options.py
- conans/test/integration/options_test.py
> Fixed equals in tuple default_options (#2915)

- conans/client/tools/files.py
- conans/test/util/tools_test.py
- conans/test/util/which_test.py
- conans/test/utils/context_manager.py
> Make sure tools.which() does not return a dir

- conans/client/packager.py
- conans/test/functional/short_paths_test.py
- conans/util/windows.py
> fix inconsistent cache with short_paths

- conans/client/manager.py
- conans/client/tools/env.py
- conans/test/integration/python_build_test.py
> fix export-pkg python reuse

- conans/client/cmd/download.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/package_installer.py
- conans/client/proxy.py
- conans/client/remote_manager.py
- conans/test/command/download_test.py
- conans/test/integration/manifest_validation_test.py
Pure refactor. Preparation for changes in graph model for 1.5.
> download refactor

- conans/client/tools/win.py
- conans/test/util/tools_test.py
> Fixes newlines in vcvars output for vcvars_dict

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> - automatically set up vcvars for Ninja and NMake generators

- conans/model/version.py
- conans/test/model/version_test.py
> Fix version class for greater than comparison

- conans/client/graph/build_mode.py
- conans/client/graph/graph.py
- conans/client/graph/graph_builder.py
- conans/client/installer.py
> force truly private

- conans/client/build/autotools_environment.py
- conans/test/build_helpers/autotools_configure_test.py
> fPIC auto-managed in autotools build helper

- conans/client/migrations.py
> do not overwrite settings.yml

- conans/client/generators/virtualbuildenv.py
- conans/client/generators/virtualenv.py
- conans/client/tools/win.py
- conans/test/generators/virtualbuildenv_test.py
- conans/test/integration/conan_env_test.py
> Set vcvars in virtualbuildenv generator for visual studio

- conans/client/file_copier.py
- conans/test/functional/file_copier_test.py
> fixing symlinked folder bug

- conans/client/tools/win.py
- conans/test/util/unix_path_test.py
> fixe get_cased_path

- conans/client/cmd/export.py
- conans/test/functional/scm_test.py
Closes #2965
Adds a new test (not failing) related to #2961
> scm message changed and added test

- conans/client/conf/__init__.py
- conans/client/migrations.py
> Fixed and added 20 standard

- conans/client/cmd/download.py
- conans/client/conan_api.py
- conans/client/manager.py
Pure refactor, just moving the download functionality to its source file, instead of being in ConanManager
> move download

- conans/client/build/cppstd_flags.py
- conans/test/integration/cppstd_test.py
> fixed preprocessor

- conans/client/generators/cmake_common.py
- conans/test/integration/cmake_flags_test.py
Closes https://github.com/conan-io/conan/issues/2975
> CMake std 20 as a flag

- conans/__init__.py
- conans/client/generators/cmake_common.py
- conans/client/generators/cmake_multi.py
- conans/model/build_info.py
- conans/test/generators/cmake_test.py
- conans/test/integration/cmake_flags_test.py
> NOT MERGE Release/1.4.2

- README.rst
Please, try it on your machines and if works, merge and adopt it.
It is important to have an easier way to let users test live changes.
> Readme: run from sources

- conans/client/conf/detect.py
> fix gcc detect

- conans/client/command.py
> fix sigterm

- MANIFEST.in
>  Add manifest file to package license

- conans/client/graph/graph.py
- conans/client/installer.py
- conans/test/integration/order_libs_test.py
> fix link order when privates

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
- conans/test/integration/cmake_flags_test.py
- conans/test/integration/cmake_install_package_test.py
> Relax generator check for Windows in Cmake build helper

- conans/client/installer.py
> refactor installer project

- conans/test/integration/workspace_test.py
> fix workspace tests

- conans/client/tools/system_pm.py
> SYSREQUIRES_MODE=Disable shouldn't update

- conans/client/tools/files.py
- conans/test/util/files_extract_wildcard_test.py
This pull request implements #2938 
The pull request for documentation is conan-io/docs#689
> Add filter for extract tools

- conans/client/tools/files.py
- conans/test/util/files_extract_wildcard_test.py
https://github.com/conan-io/conan/pull/3065
> small change in filter unzip test

- conans/client/tools/oss.py
As requested in #2873; this PR adds support for manjaro
> Add Manjaro support

- conans/client/cmd/user.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/conan_command_output.py
- conans/client/rest/auth_manager.py
- conans/test/command/user_test.py
- conans/test/functional/conan_trace_file_test.py
```
$ conan user
Current 'conan-center' remote's user: 'dann'
Current 'bincrafters' remote's user: 'None' (anonymous)
Current 'upload_repo' remote's user: 'dani'
Current 'conan-community' remote's user: 'danimtb' [Authenticated]
Current 'conan_artifactory' remote's user: 'danielm' [Authenticated]
Current 'szmyd' remote's user: 'None' (anonymous)
Current 'cli11' remote's user: 'kkk'
Current 'conan_server' remote's user: 'demo' [Authenticated]
```
Check slight changes in the output to clarify messages.
> Show authenticated users

- conans/client/graph/printer.py
- conans/test/functional/package_id_test.py
> fixed duplicated call to package_id

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
Docs here:  https://github.com/conan-io/docs/pull/702
> Disable CMAKE_EXPORT_NO_PACKAGE_REGISTRY

- conans/client/conf/__init__.py
- conans/client/migrations.py
> Macos optional version

- conans/client/cmd/export.py
- conans/client/source.py
- conans/client/tools/scm.py
- conans/model/scm.py
- conans/test/functional/merge_directories_test.py
- conans/test/functional/scm_test.py
- conans/test/util/tools_test.py
> SCM improvements

- conans/client/tools/win.py
- conans/test/util/vcvars_arch_test.py
> Apply vcvars params for Visual 14 too

- conans/test/command/remote_test.py
> remote remove test

- conans/test/functional/require_override_test.py
Tried to reproduce the issue without success. I couldn't find a TestClient test for dep override nor a single test using the requirements method with override. Check if I miss them or merge accordingly.
> New test for dependency override

- conans/test/command/user_test.py
- conans/test/utils/tools.py
> try fix dicts comparison

- conans/client/source.py
- conans/test/functional/scm_test.py
- Remove a print that can print a lot of stuff.
> Removed print

- conans/client/cmd/export.py
- conans/client/source.py
- conans/test/functional/scm_test.py
> Fix: conan create not deleting sources when scm capture enabled

- conans/client/graph/graph_manager.py
- conans/test/command/create_test.py
- conans/test/command/info_test.py
cc / @theodelrieu 
The fix is a bit hacky, it requires improvements in the model for a cleaner solution.
> fix duplicate build requires

- conans/client/installer.py
> fixed private binary skip

- conans/client/graph/graph.py
- conans/client/graph/graph_binaries.py
- conans/client/graph/printer.py
- conans/test/integration/private_deps_test.py
> fixed private bugs in 1.5

- conans/client/tools/system_pm.py
- conans/test/util/tools_test.py
> fixed sudo=False mode=verify calling update in SystemPackageTool

- conans/client/tools/system_pm.py
- conans/test/util/tools_test.py
fixes #3180 
see also https://github.com/bincrafters/community/issues/345
> - call yum update instead of yum check-update

- conans/client/rest/rest_client.py
- conans/test/command/upload_test.py
- And detected bug of a list without ","
> Fixed typo "Forbidden"

- conans/client/command.py
- conans/client/conan_command_output.py
- conans/test/command/remote_test.py
Fix #3125
- Docs in https://github.com/conan-io/docs/pull/717
> added conan remote list --raw

- conans/client/generators/visualstudio.py
- conans/test/generators/visual_studio_test.py
Fix #3121
@pawelkami PR didn't work well in some cases due to case-sensitive paths. This PR should fix it.
> use USERPROFILE in visual_studio generator

- conans/client/remote_manager.py
- conans/test/command/upload_test.py
> managing dirty tgzs

- conans/client/runner.py
fix issue https://github.com/conan-io/conan/issues/3035
- a contextmanager is used to clearly separate this from the actual logic.
- unfortunately the global `os.environ` has to be temporarily modified to work with the `os.system` call.
- if `self._simple_os_call` would be removed a much cleaner solution would be possible - passing a modified env dict to `subprocess.Popen`
> remove pyinstaller env from conan subprocesses

- conans/model/conan_file.py
- conans/test/functional/runner_test.py
- conans/test/integration/run_envronment_test.py
> run with environment paths

- conans/client/runner.py
> stripping trailing :; from LD_LIBRARY_PATH

- conans/client/conf/__init__.py
> Add toolsets

- conans/client/migrations.py
To prepare for #3136 and any other settings change in 1.6
> migration ready 1.6

- conans/client/generators/xcode.py
- conans/model/build_info.py
- conans/test/generators/xcode_gcc_vs_test.py
- Docs:
https://github.com/conan-io/docs/pull/727
Also tested manually, xcode is "importing" good the new directory list.
> Add FRAMEWORK_SEARCH_PATHS to xcode generator

- conans/client/graph/graph.py
- conans/client/graph/graph_binaries.py
- conans/test/integration/private_deps_test.py
> fix transitive privates

- conans/client/tools/net.py
Just propagating params, tests not needed.
closes #3140 
Missing docs...
> Added keep_permissions and pattern params to tools.get()

- conans/client/tools/files.py
- conans/test/util/tools_test.py
Tested with "file" command line tool to verify that the operating system recognizes correctly the end lines.
> unix2dos dos2unix

- conans/client/manager.py
- conans/test/integration/manifest_validation_test.py
> fix --manifest issue with test_package

- conans/client/build/cmake.py
- conans/client/tools/env.py
- conans/test/build_helpers/cmake_test.py
- conans/test/integration/conan_env_test.py
- conans/test/integration/run_envronment_test.py
> run_environment for CMake and ld_library_path tests

- .ci/jenkins/Jenkinsfile
- conans/server/conf/__init__.py
Bug spotted in the revisions branch.
> Fixed server environment default init

- conans/client/build/cmake.py
Small refactor after https://github.com/conan-io/conan/pull/3248
> small refactor of patch_config_paths()

- conans/client/graph/graph.py
- conans/test/command/info_test.py
> fixing --build-order by collapsing graph

- conans/client/cmd/export.py
- conans/test/integration/alias_test.py
> forbid an alias to a different package name

- conans/client/command.py
An update of the commands reference is required. @danimtb you have a magic script, right? schedule for next release.
> Fix download help

- conans/client/command.py
- conans/client/conan_api.py
- conans/client/conan_command_output.py
- conans/client/graph/grapher.py
- conans/client/manager.py
- conans/client/printer.py
- conans/test/utils/tools.py
- Not passing settings_preprocessor as argument everywhere
- project_reference argument is unnecessary, it can be obtained from conanfile
> Minor refactors: settings_preprocessor as param and project_reference removed

- conans/client/generators/cmake_common.py
> CMake 3.12 support cxx20

- conans/client/cmd/uploader.py
- conans/client/generators/cmake_find_package.py
- conans/client/graph/graph_binaries.py
- conans/client/installer.py
- conans/client/printer.py
- conans/client/recorder/search_recorder.py
- conans/client/remote_manager.py
- conans/client/rest/rest_client_common.py
- conans/client/rest/rest_client_v1.py
- conans/model/info.py
- conans/model/manifest.py
- conans/search/search.py
- conans/server/migrate.py
- conans/test/command/json_output_test.py
- conans/test/integration/basic_build_test.py
- conans/test/integration/conan_env_test.py
- conans/test/integration/version_ranges_diamond_test.py
- conans/test/util/tools_test.py
- conans/test/utils/tools.py
- conans/util/tracer.py
Extracted from @lasote Revisions PR https://github.com/conan-io/conan/pull/3055
> minor refactors revisions

- conans/client/rest/uploader_downloader.py
- conans/test/functional/client_certs_test.py
- conans/test/functional/download_retries_test.py
- conans/test/utils/tools.py
- Default retry attempts of file downloads to 3.
- Improved downloader to retry also when the error is produced in the reception of the data stream (previously checked only the initial request)
@tru
> Downloads auto retry

- conans/client/graph/graph_builder.py
- conans/model/requires.py
- conans/test/functional/require_override_test.py
- conans/test/model/transitive_reqs_test.py
- conans/test/model/version_ranges_test.py
> Fix spelling of 'overridden'

- conans/client/build/msbuild.py
- conans/test/build_helpers/msbuild_test.py
- conans/test/util/build_sln_command_test.py
- conans/test/util/tools_test.py
> Quote MSBuild arguments

- conans/client/conan_api.py
- conans/test/model/fake_retriever.py
- conans/test/model/transitive_reqs_test.py
- conans/test/model/version_ranges_test.py
> extracting duplicated Retriever in tests

- conans/test/generators/xcode_gcc_vs_test.py
> fixed generators test

- conans/client/conf/config_installer.py
> disabling templateDir for conan config install git

- .ci/jenkins/runner.py
- conans/test/__init__.py
- setup.py
To adjust globally the CONAN_RECIPE_LINTER env var.
> Optimize testsuite

- conans/client/build/cmake.py
- conans/test/build_helpers/cmake_test.py
> fix should_build for cmake build helper

- conans/model/options.py
`dict.get` is exactly made for that purpose.
> Use dict.get for get_safe

- conans/client/loader.py
- conans/model/options.py
- conans/test/integration/options_test.py
> fix *:option pattern for consumers

- conans/test/integration/cmake_targets_test.py
> test for transitive shared flags

- conans/client/tools/apple.py
> Find libtool when getting building information on Darwin

- conans/model/info.py
- conans/test/util/unix_path_test.py
Also fixed a small test that can fail in Windows, non-related.
Close #3533
> removed dead serialize code

- conans/client/graph/graph_builder.py
- conans/test/integration/private_deps_test.py
> fixing transitive private bug

- conans/client/file_copier.py
- conans/test/integration/symlinks_test.py
Close #3535
Close #3258
Close #3409
> changing processing of exports exclude patterns

- conans/client/manager.py
- conans/test/command/create_test.py
- conans/test/command/install_test.py
> configuration print for install

- conans/client/generators/__init__.py
- conans/client/generators/b2.py
- conans/test/generators/b2_test.py
Related documentation PR is https://github.com/conan-io/docs/pull/790
> New and improved generator for B2 (Boost Build).

- conans/client/local_file_getter.py
- conans/test/functional/short_paths_test.py
> fix get short_paths

- conans/client/build/autotools_environment.py
- conans/test/build_helpers/autotools_configure_test.py
>  Added --libdir parameter to autotools configure

- conans/client/cmd/export.py
- conans/test/client/cmd/export_test.py
Will fix failing test in #3505
> fix bug: bad replacement if scm attribute was the last one in ClassDef

- conans/test/model/options_test.py
> Fix tests than were failing in py3.4

- conans/util/progress_bar.py
> Add seekable function to progress bar wrapper

- conans/test/utils/tools.py
> fix raise without Exception

- conans/client/client_cache.py
- conans/client/cmd/download.py
- conans/client/cmd/search.py
- conans/client/cmd/uploader.py
- conans/client/conan_api.py
- conans/client/conf/config_installer.py
- conans/client/graph/graph_binaries.py
- conans/client/graph/proxy.py
- conans/client/installer.py
- conans/client/printer.py
- conans/client/remote_registry.py
- conans/client/remover.py
- conans/client/source.py
- conans/test/command/config_install_test.py
- conans/test/command/info_folders_test.py
- conans/test/command/info_test.py
- conans/test/command/remote_test.py
- conans/test/command/upload_test.py
- conans/test/functional/registry_test.py
- conans/test/utils/tools.py
Changelog: Feature: Internal refactor to the remote registry to manage a json file. Also improved internal interface.
> Registry internal refactor + json file

- conans/test/client/cmd/ast_replacement_scm_test.py
> fix import

- conans/client/cmd/build.py
- conans/client/cmd/export_pkg.py
- conans/client/cmd/test.py
- conans/client/conan_api.py
- conans/client/manager.py
- conans/test/command/upload_complete_test.py
- conans/test/functional/create_package_test.py
The ``ConanManager`` is low cohesion and low value, removing local flow functionality from it.
> refactor, removing things from manager

- conans/client/cmd/uploader.py
- conans/model/manifest.py
- conans/test/command/upload_test.py
Changelog: Feature: Increase debugging information when an error uploading a recipe with different timestamp occurs.
> Manifest diff prints

- conans/test/conditional_requirements_id_test.py
> new test for conditional requirements keep package_id

- conans/client/conan_api.py
- conans/test/command/package_test.py
- conans/test/command/source_test.py
- conans/test/command/test_package_test.py
> Improve "conanfile not found" message

- conans/test/transitive_options_affect_id_test.py
Test for https://github.com/conan-io/conan/issues/3776
> adding test for transitive options not affecting binary ID

- conans/client/loader.py
- conans/test/functional/conanfile_helpers_test.py
Necessary, as demonstrated by improved test
> reverting imported modules management

- conans/client/build/visual_environment.py
- conans/test/build_helpers/visual_environment_test.py
closes #3790 
closes #3105 
Changelog: Fix: Fixed ``link_flags`` management in ``MSBuild`` build helper
> Fix: fix link_flags management with MSBuild

- conans/client/build/cppstd_flags.py
- conans/client/settings_preprocessor.py
- conans/test/integration/cppstd_test.py
- conans/test/model/other_settings_test.py
Changelog: Fix: remove error that was raised for custom compiler & compiler version, while checking ``cppstd`` setting.
closes #3842
> fixing error with custom compiler and cppstd

- conans/test/client/cmd/export_test.py
> Test conan_sources.tgz is deleted when using SCM feature

- conans/client/conf/__init__.py
> Update gcc version in allowed settings to 8.2

- conans/client/tools/win.py
Fix windows subsystem tests related to the #3836
> Convert paths for known compilation env vars

- conans/test/functional/scm_test.py
- conans/test/util/tools_test.py
> Tag tests related to SVN (and a couple using Git)

- conans/test/integration/version_ranges_diamond_test.py
Test to check that the docs are correct about version ranges resolving mechanism.
#3977
> Test to ensure the version ranges behavior

- README.rst
> README for dev packages

- conans/client/build/cmake_flags.py
Changelog: Improve CMake helper ``in_local_cache`` assignation
> Improve CMake helper in_local_cache assignation

- conans/client/conan_api.py
- conans/client/installer.py
- conans/client/remote_manager.py
- conans/client/source.py
- conans/test/command/export_dirty_test.py
- conans/test/command/source_test.py
- conans/test/utils/tools.py
Changelog: Bugfix: Fix removal of conanfile.py with ``conan source`` command and the removal of source folder in the local cache when something fails
Fix #4025
Fix #4013
> fixing source bugs and issues

- conans/model/ref.py
- conans/test/command/info_options_test.py
- conans/test/command/install_test.py
- conans/test/command/remove_test.py
- conans/test/command/search_test.py
- conans/test/functional/create_package_test.py
- conans/test/functional/scm_test.py
- conans/test/model/ref_test.py
Changelog: Bugfix: Better checks of package reference ``pkg/version@user/channel``, avoids bugs for conanfile in 4 nested folders and ``conan install path/to/the/file``
Close #3950
> better ConanFileReference checks

- conans/client/rest/rest_client.py
- conans/test/utils/tools.py
> Env var for client to (un)block API V2

- conans/client/graph/range_resolver.py
- conans/test/unittests/client/graph/test_range_resolver.py
Related to #3898.
SemVer library is not honoring that syntx.
> Remove brackets from valid semver

- conans/client/cmd/download.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/loader.py
- conans/test/command/create_test.py
Changelog: Feature: allow ``conan export . version@user/channel`` and ``conan create . version@user/channel``
Also, some internal refactors to help in the graph-lock feature
> loading name-version for export

- conans/server/server_launcher.py
- conans/test/integration/revisions_test.py
Changelog: Bugfix: Add v1_only argument in Conan server class
Close #4080
> remove only_v1 parameter

- conans/test/integration/python_build_test.py
Fix change in TestClient of `ignore_error` to `assert_error`
> fix ignore_error tests

- conans/test/command/export_path_test.py
- conans/test/command/export_test.py
- conans/test/integration/diamond_test.py
- conans/test/remote/rest_api_test.py
- conans/test/utils/cpp_test_files.py
On my machine > 1m:20secs is saved.
I am avoiding computing the whole diamond for both "language" options of the graph.
> simplifying diamond test for faster tests

- conans/client/cmd/build.py
- conans/client/cmd/export.py
- conans/client/cmd/uploader.py
- conans/client/conan_api.py
- conans/client/graph/graph_builder.py
- conans/client/graph/proxy.py
- conans/client/installer.py
- conans/client/packager.py
- conans/client/profile_loader.py
- conans/client/remote_manager.py
- conans/client/remover.py
- conans/client/rest/auth_manager.py
- conans/client/rest/rest_client_common.py
- conans/client/rest/rest_client_v1.py
- conans/client/rest/rest_client_v2.py
- conans/client/rest/uploader_downloader.py
- conans/client/rest/version_checker.py
- conans/server/server_launcher.py
- conans/util/tracer.py
Changelog: Feature: Improve client DEBUG traces with better and more complete messages.
Changelog: Feature: Server prints the configuration used at startup to help debugging issues.
Closes #3895 #4030
> Better debug traces and server printing config at startup

- conans/test/functional/command/info_test.py
- conans/test/functional/old/remote_checks_test.py
- conans/test/integration/revisions_test.py
- conans/test/utils/tools.py
> fix revisions in nightly

- README.rst
- tox.ini
Changelog: Feature: Tox launcher to run the test suite.
> Tox launcher

- conans/test/integration/conan_test_test.py
- conans/test/integration/workspace_test.py
Based on: https://gist.github.com/lasote/c48557e087acc22dbd180ac01ee366aa
> sleeps to mitigate spurious errors in testing

- conans/client/build/cmake_flags.py
> Remove OR of generator in cmake flags

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.rst
Changelog: Updated contributing guidelines to new workflow
Docs: omit
This updated the contributing guidelines including information about added docs PRs and issue stages.
> Review of Contributing guidelines and added docs and stages information

- conans/client/conan_api.py
- conans/client/graph/graph_manager.py
- conans/client/manager.py
- conans/client/printer.py
- conans/test/functional/command/info_test.py
Docs: Omit
Solve https://github.com/conan-io/conan/pull/4166#issuecomment-449320310
> removed Required by: virtual

- conans/client/build/cmake.py
- conans/client/cmd/uploader.py
- conans/client/file_copier.py
- conans/client/generators/b2.py
- conans/client/generators/compiler_args.py
- conans/client/generators/json_generator.py
- conans/client/graph/proxy.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/migrations.py
- conans/client/remote_manager.py
- conans/client/rest/rest_client_common.py
- conans/client/runner.py
- conans/client/tools/apple.py
- conans/client/tools/win.py
- conans/search/search.py
- conans/test/functional/generators/cmake_paths_test.py
- conans/test/functional/generators/cmake_test.py
- conans/test/functional/generators/make_test.py
- conans/test/integration/package_id_test.py
- conans/util/windows.py
Docs: Omit
- Some pep8 styling
- Renamed ConanInstaller => BinaryInstaller
- Optimized slow cmake test => 20 -> 5 secs
- Removed duplicated current_remote retrieval
> minor cleanings

- conans/client/build/cmake_flags.py
- conans/client/build/compiler_flags.py
- conans/test/functional/build_helpers/cmake_flags_test.py
Docs: Omit
Following https://github.com/conan-io/conan/pull/4227
> refactor cmake flags

- conans/test/functional/command/create_test.py
- conans/test/integration/complete_test.py
- conans/test/integration/conan_test_test.py
Docs: Omit
This can save up to 60 seconds in Windows builds
Close #4230
> optimizing slow tests

- .gitignore
- conans/test/unittests/client/build/autotools_environment_test.py
- conans/test/unittests/client/build/cmake_test.py
- conans/test/unittests/client/build/compiler_flags_test.py
- conans/test/unittests/client/build/cpp_std_flags_test.py
- conans/test/unittests/client/build/meson_test.py
- conans/test/unittests/client/build/msbuild_test.py
- conans/test/unittests/client/build/visual_environment.py
Docs: omit
These tests were excluded from the PR #4127 due to gitignore
> Added missing build helpers unit tests

- conans/model/editable_cpp_info.py
- conans/test/unittests/model/editable_cpp_info/apply_test.py
- conans/test/unittests/model/editable_cpp_info/parse_test.py
> Use old interface of ConfigParser

- conans/test/unittests/client/tools/os_info/osinfo_test.py
> Fixed mocked check_output() for uname command

- conans/test/functional/generators/cmake_generator_test.py
- conans/test/unittests/client/build/cmake_flags.py
> FIX DEVELOP: cmake generator default choice

- conans/model/conan_file.py
Changelog: (Fix): Fixed pydoc of package_id
> Fix pydoc of package_id

- conans/client/tools/scm.py
- conans/server/store/server_store.py
- conans/test/unittests/util/tools_test.py
Changelog: Bugfix: Removing usage of FileNotFoundError which is Py3 only
Docs: Omit
@TAGS: slow, svn
@PYVERS: py36, py27, py34
> fix FileNotFoundError is py3 only

- conans/client/generators/__init__.py
- conans/client/loader.py
- conans/test/functional/generators/custom_generator_test.py
Changelog: Bugfix: Custom generator allow to use imports
Docs: Omit
Close #3744
> generator template

- conans/test/functional/scm/scm_test.py
> Fix develop: add quotes to word so it is a string

- conans/test/functional/command/info_command_test.py
> [typo] Remove unused code

- conans/client/graph/graph_manager.py
> remove build mode check

- conans/client/tools/files.py
- conans/test/unittests/tools/files_patch_test.py
- conans/test/unittests/util/conanfile_tools_test.py
Changelog: Bugfix: ``tools.patch`` strip!=0 parameter was not working for created or deleted files.
Docs: omit
Close #4453
> fix patch strip

- conans/client/graph/graph_builder.py
- conans/test/functional/editable/transitive_editable_test.py
Changelog: Bugfix: Transitive Editable packages fail to install
Docs: omit
Close #4445
@TAGS: slow
> fixing editable package revisions

- conans/model/package_metadata.py
Changelog: Fix: Fix potential downgrade from future 1.13 to 1.12
Docs: omit
> Fixes future possible downgrade from 1.13 to 1.12.2

- conans/client/command.py
- conans/test/functional/command/search_test.py
Docs: omit
closes #4576 
@REVISIONS: 1
> Raise if using 'conan search ... --revisions' with the feature disabled

- conans/client/tools/oss.py
Docs: omit
Fix error introduced in https://github.com/conan-io/conan/pull/4347
> HotFix: FileNotFoundError is not py2

- conans/client/cmd/uploader.py
> [FIX CI] Fix upload test with PREF being discarded even when not existing

- conans/client/migrations.py
> fix migration

- conans/client/tools/win.py
- conans/tools.py
> Add output argument to msbuild_command tool

- conans/client/conan_api.py
- conans/client/graph/python_requires.py
- conans/test/functional/python_requires/python_requires_test.py
Changelog: Feature: Implement ``--update`` argument for ``python-requires`` too.
Docs: omit
Close  #4650
> python requires updates

- conans/client/graph/graph_builder.py
- conans/client/graph/graph_manager.py
- conans/test/functional/graph/graph_manager_test.py
- conans/test/functional/graph/transitive_deps_test.py
- conans/test/functional/workspace/workspace_test.py
Changelog: Bugfix: Fix computation of graph when transitive diamonds are processed.
Docs: omit
@tags: slow
Close #4720
Close #4727
> fix graph computation

- conans/__init__.py
- conans/client/graph/graph_builder.py
- conans/client/graph/graph_manager.py
- conans/test/functional/graph/graph_manager_test.py
- conans/test/functional/graph/transitive_deps_test.py
- conans/test/functional/workspace/workspace_test.py
> Release/1.13.1 only CI

- conans/client/build/cmake.py
- conans/client/build/cmake_flags.py
- conans/client/conf/__init__.py
- conans/test/unittests/client/build/cmake_test.py
Changelog: Fix: add support for CMake generator platform
Docs: https://github.com/conan-io/docs/pull/1125
tags: @slow @svn
closes #4707 
closes #4755
> Fix: add support for CMake generator platform

- .ci/jenkins/Jenkinsfile
> Avoid running branch indexing builds

- conans/__init__.py
- conans/client/graph/graph.py
- conans/client/graph/graph_binaries.py
- conans/client/graph/graph_builder.py
- conans/client/graph/graph_manager.py
- conans/model/workspace.py
- conans/test/functional/graph/graph_manager_base.py
- conans/test/functional/graph/graph_manager_test.py
- conans/test/functional/workspace/workspace_test.py
- conans/test/integration/install_outdated_test.py
- conans/test/utils/conanfile.py
> Release/1.13.2 CI ONLY

- conans/client/tools/win.py
- conans/test/unittests/util/tools_test.py
> Review of vswhere PR #4805

- conans/__init__.py
- conans/client/cmd/export.py
- conans/client/rest/uploader_downloader.py
- conans/client/tools/scm.py
- conans/test/integration/revisions_test.py
- conans/test/unittests/util/tools_test.py
> Release/1.13.3 ONLY CI

- conans/client/cmd/export_pkg.py
- conans/client/graph/proxy.py
- conans/client/installer.py
- conans/client/remote_manager.py
- conans/client/rest/rest_client_v2.py
> improve output for v2 and revisions

- conans/client/command.py
- conans/client/conan_api.py
- conans/errors.py
Changelog: Fix: Print a message for unhandled Conan errors building the API and collaborators
Docs: omit
> Print a message for unknown errors building the API and collaborators

- conans/__init__.py
- conans/client/cmd/uploader.py
- conans/client/command.py
- conans/client/conan_api.py
- conans/client/migrations.py
- conans/client/remote_manager.py
- conans/client/rest/auth_manager.py
- conans/client/rest/rest_client_common.py
- conans/errors.py
- conans/test/functional/command/install_test.py
> Release/1.14.1 CI

- conans/client/graph/python_requires.py
- conans/client/loader.py
- conans/test/functional/command/inspect_test.py
Docs: omit
(only changes UX)
closes #4814
> Capture NotFoundError due to missing python_requires

- conans/client/graph/graph_binaries.py
Docs: omit
New assert to try to debug: https://github.com/conan-io/conan/issues/4898
> adding assert for #4898

- conans/client/remover.py
- conans/test/functional/editable/forbidden_commands_test.py
> Fix wrong error message

- conans/__init__.py
- conans/client/migrations.py
- conans/test/functional/old/test_migrations.py
> Release/1.14.2 (ONLY CI)

- conans/model/conan_generator.py
- conans/server/rest/bottle_plugins/authorization_header.py
- conans/server/service/authorize.py
Docs: omit
closes https://github.com/conan-io/conan/issues/4855
> Add metaclass in a py2/3 compatible way

- conans/__init__.py
- conans/client/graph/graph_builder.py
- conans/test/functional/graph/graph_manager_test.py
> Release/1.14.3, CI ONLY

- conans/client/runner.py
> Unbuffered output in ConanRunner

- conans/test/functional/command/build_test.py
Docs: omit
I think that #2899 wildcard settings didn't progress because it has many risks, and the solution exposed there of:
```bash
conan install .. -s myApp:build_type=Debug -s build_type=Release
conan build ..
```
works well, this PR is proposing a test that checks this behavior. Should it be added to the docs too?
So I am proposing to close it.
Close #2899
> test for build with debug using release deps

- conans/client/build/cmake.py
- conans/client/build/cmake_flags.py
Changelog: Bugfix: Fixed error while using Visual Studio 2019 with Ninja generator.
Docs: Omit
Close #4977
> Fix Vs2019 when generator Ninja

- conans/requirements_dev.txt
Docs: omit
Isolated in a PR, to check nothing breaks (I will use it in #4917)
> Up requirement 'parameterized' (this version adds 'parameterized_class' decorator)

- conans/client/command.py
- conans/client/conan_api.py
- conans/model/workspace.py
- conans/test/functional/workspace/workspace_test.py
Changelog: Feature: Add install folder to command 'conan workspace install'
Docs: https://github.com/conan-io/docs/pull/1261
closes https://github.com/conan-io/conan/issues/4799
closes https://github.com/conan-io/conan/issues/4777
> Add install folder to command 'conan workspace install'

- README.rst
- setup.py
Docs: omit
@pyvers: Linux@py27, Linux@py36
> setup description

- conans/test/functional/build_helpers/cmake_targets_test.py
> Fix develop test: Adjusted vs environment before running cmake

- conans/test/functional/build_helpers/cmake_flags_test.py
- conans/test/functional/generators/cmake_skip_rpath_test.py
> hardcoding VS 2017 in tests

- conans/test/functional/command/config_install_test.py
Docs: omit
This is a new test, to make sure the ``conan config install`` doesn't add twice hooks to conan.conf
> test for hooks in conan.conf config-install

- conans/model/manifest.py
A complement of: https://github.com/conan-io/conan/pull/4991
Docs: omit
> Better error message to show usage of CONAN_SKIP_BROKEN_SYMLINKS_CHECK

- conans/__init__.py
- conans/client/migrations_settings.py
> fix migration test

- conans/test/functional/old/test_migrations.py
- conans/test/unittests/client/profile_loader/compiler_cppstd_test.py
> check raise migration compiler.cppstd failed

- conans/client/conan_api.py
This was a regression caused by #4724.
Changelog: Bugfix: Fix adding editable packages that use python_requires
Docs: no docs
> Fix adding editable packages that use python_requires

- conans/client/build/cmake_flags.py
- conans/client/build/compiler_flags.py
- conans/client/conf/__init__.py
- conans/client/tools/oss.py
- conans/test/unittests/client/build/compiler_flags_test.py
- conans/test/unittests/model/other_settings_test.py
- conans/test/unittests/model/transitive_reqs_test.py
- conans/test/unittests/util/tools_test.py
closes #4294 
Changelog: Feature: QNX Neutrino support
/cc @jpovedano @Johnnyxy
> Feature: QNX Neutrino support

- conans/client/hook_manager.py
- conans/client/installer.py
- conans/test/integration/hook_test.py
Changelog: Feature: Add hooks `pre_package_info` and `post_package_info`
Docs: https://github.com/conan-io/docs/pull/1293
closes #5100
> Add hook pre/post_package_info

- conans/test/functional/command/config_install_test.py
- conans/test/functional/command/export_linter_test.py
- conans/test/functional/configuration/proxies_conf_test.py
Docs: omit
@PYVERS: Macos@py36
> try to fix devleop

- conans/client/command.py
- conans/client/conan_api.py
- conans/test/integration/system_reqs_test.py
> Use string as reference for the Conan API

- conans/client/cmd/new.py
- conans/test/functional/command/new_test.py
> templates folder

- README.rst
> Fix link layout

- conans/client/cmd/export.py
- conans/client/loader.py
- conans/paths/__init__.py
- conans/test/functional/conanfile/conan_data_test.py
- conans/test/utils/test_files.py
Docs: omit
Experimental introduced feature (A.k.A Roswell secret files) to automatically get data from a `yml` file.
@TAGS: slow
> Data from yml

- conans/client/graph/graph.py
- conans/client/graph/graph_builder.py
Changelog: Bugfix: Fix computation of ancestors performance regression
Docs: omit
Close #5246
@tags: slow
cc/ @jakuborava
> fix ancestors performance

- conans/client/build/cmake_flags.py
- conans/client/tools/__init__.py
- conans/client/tools/android.py
- conans/test/unittests/client/build/cmake_test.py
- conans/test/unittests/util/android_test.py
Docs: https://github.com/conan-io/docs/pull/1301
> Review Android CMake flags

- conans/client/cmd/new.py
- conans/test/functional/command/new_test.py
> using jinja for conan new --file templates

- conans/client/command.py
Docs: omit
https://github.com/conan-io/docs/pull/1315
> Add build cascade to help

- conans/model/workspace.py
> Reorder functions in Workspace class

- conans/client/tools/files.py
- conans/test/unittests/tools/files_patch_test.py
Changelog: Bugfix: Allow creation and deletion of files in ``tools.patch`` with ``strip>0``
Docs: omit
Close #5320
> fix patch with strip

- conans/client/generators/virtualenv.py
Changelog: Fix: Add missing call to super constructor to `VirtualEnvGenerator`.
Docs: Omit
Fixes #5374.
> Fix virtualenv constructor.

- conans/client/graph/graph.py
- conans/client/graph/graph_builder.py
Docs: Omit
My attempt to explain better what GraphBuilder is doing. While writing comments some minor improvements were done (just refactors, no change in functionality intended) that reduce the code and helps understanding a bit better.
Close #4738
@tags: slow
> graph levels improvements

- .codeclimate.yml
Relax Code Climate rules for minor and major severity
This PR will promote Conan degree to **B**, you can see in my branch:
https://codeclimate.com/github/uilianries/conan
I have ignored many structural problems, which I think requires more work than the proposed benefits
Related issue #3558 
/cc @lasote 
Docs: Omit
> Relaxed Code Climate checks

- conans/test/unittests/client/conanfile_loader_test.py
- conans/util/config_parser.py
Changelog: Fix: Enable the definition of revisions in conanfile.txt
Docs: omit
Close  #5427
> enable revisions in conanfile.txt

- conans/model/graph_lock.py
- conans/test/functional/graph_lock/graph_lock_ci_test.py
- conans/test/functional/graph_lock/graph_lock_test.py
> version lockfiles

- conans/search/binary_html_table.py
Changelog: Bugfix: search command table output has invalid HTML code syntax
Docs: Omit
Not follow the whole guidelines for contributing, because my PR is pointing to the typo.
> table html: fix Legend section

- conans/client/cmd/new_ci.py
- conans/client/conf/__init__.py
- conans/client/migrations_settings.py
Changelog: Feature: support 7.1 clang version
Docs: omit
Closes #4938
> add clang 7.1 version

- conans/client/cmd/build.py
- conans/client/cmd/create.py
- conans/client/cmd/export.py
- conans/client/cmd/export_pkg.py
- conans/client/cmd/test.py
- conans/client/conan_api.py
- conans/client/installer.py
- conans/client/manager.py
- conans/client/packager.py
- conans/paths/package_layouts/package_cache_layout.py
Docs: omit
This is a pure refactor, using the new ConanApp object to simplify collaborators and args passing around.
> using app to simplify collaborators

- conans/client/conf/detect.py
- conans/client/tools/oss.py
- conans/test/unittests/client/tools/oss/get_cross_building_settings_test.py
Docs: omit
Related to https://github.com/conan-io/conan/pull/5630
@datalogics-robb  please take a look
Extracted duplicated code to OSInfo and incorporated new Solaris arch detection to the Conan default profile detection.
> Small changes in detection arch solaris and AIX

- conans/test/functional/build_requires/build_requires_test.py
- conans/test/functional/command/export_pkg_test.py
- conans/test/functional/editable/layouts_test.py
- conans/test/functional/editable/transitive_editable_test.py
- conans/test/functional/graph/full_revision_mode_test.py
- conans/test/functional/graph/graph_manager_test.py
- conans/test/functional/graph/half_diamond_test.py
- conans/test/functional/graph/package_id_modes_test.py
- conans/test/functional/graph/private_deps_test.py
- conans/test/functional/graph/transitive_deps_test.py
- conans/test/functional/graph/version_range_error_test.py
- conans/test/functional/graph_lock/graph_lock_test.py
- conans/test/integration/package_id_test.py
- conans/test/unittests/client/graph/version_ranges_graph_test.py
- conans/test/unittests/model/transitive_reqs_test.py
- conans/test/utils/tools.py
Docs: omit
PR attending this comment: https://github.com/conan-io/conan/pull/5652#pullrequestreview-279357104
> Use 'requires' with GetConanfile where it was already being used

- conans/client/graph/graph_manager.py
- conans/test/functional/build_requires/build_requires_test.py
- conans/test/functional/workspace/graph_test.py
Changelog: Bugfix: Fixed assertion when using nested build_requires that depend on packages that are also used in the main dependency graph
Docs: omit
Close #5612
Close #5685
Close #5622 (included in this one)
@tags: slow
> fixing bug with multiple nested build-requires

- conans/client/cmd/download.py
- conans/client/cmd/export.py
- conans/client/conan_api.py
- conans/client/installer.py
- conans/client/manager.py
- conans/test/functional/graph/graph_manager_base.py
Docs: omit
Just a refactor, using the app object instead of separate collaborators
> app simple refactor

- conans/client/graph/graph_manager.py
> removing unnecessary update after bug fix of 1.18.2 with build-requires subgraphs

- conans/test/functional/command/export_pkg_test.py
- conans/test/functional/command/install_test.py
- conans/test/functional/command/upload_test.py
- conans/test/functional/graph/full_revision_mode_test.py
- conans/test/functional/graph/private_deps_test.py
- conans/test/functional/graph_lock/graph_lock_test.py
- conans/test/functional/old/package_integrity_test.py
- conans/test/functional/old/test_migrations.py
- conans/test/functional/python_requires/python_requires_test.py
- conans/test/integration/revisions_test.py
- conans/test/utils/tools.py
Docs: omit
PR following this comment https://github.com/conan-io/conan/pull/5652#discussion_r317418273
> No need to call explicitly 'str' for GenConanfile

- conans/client/conan_api.py
- conans/client/conf/config_installer.py
Docs: omit
- simple refactor app.cache.config => app.config
- passing app to configuration_install
- fixed string format
> app simplifying

- conans/client/graph/range_resolver.py
- conans/model/ref.py
- conans/search/search.py
Changelog: Bugfix: output of references without user/channel is done with _/_, like in lockfiles.
Docs: Omit
Fix #5799
#revisions: 1
> no user/channel repr without _

- conans/client/cmd/export_pkg.py
- conans/client/conan_api.py
- conans/client/graph/graph_manager.py
- conans/client/manager.py
- conans/test/functional/graph/graph_manager_base.py
Docs: Omit
Small refactor to clean abuse of ``display_name`` for business logic
> do not use the display_name as input to change behavior

- conans/test/integration/revisions_test.py
Docs: omit
Coming from this https://github.com/conan-io/conan/pull/5863#issuecomment-540511801
> fix repeated clear of PREV

- conans/client/cache/cache.py
- conans/client/cmd/copy.py
- conans/client/graph/proxy.py
- conans/client/installer.py
- conans/paths/package_layouts/package_cache_layout.py
- conans/test/functional/command/search_test.py
> minor refactors

- conans/client/generators/b2.py
- conans/test/unittests/client/generators/b2_test.py
Changelog: Fix: Removes duplicate lines from b2 generator output
> removed duplicated line in b2 output

- conans/test/functional/generators/virtualenv_test.py
Docs: omit
Fix typo pointed out here: https://github.com/conan-io/conan/pull/5828#discussion_r335561290
> Fix typo in comment

- conans/test/functional/generators/cmake_multi_test.py
- conans/test/functional/generators/cmake_paths_test.py
- conans/test/functional/scm/scm_test.py
- conans/test/utils/tools.py
Docs: omit
Provide the same functionality that `TestClient::run` already has.
> Add 'assert_error' argument to 'TestClient::run_command'

- conans/client/remote_manager.py
- conans/client/source.py
- conans/test/unittests/source/merge_directories_test.py
- conans/util/files.py
Docs: omit
Preparation for https://github.com/conan-io/conan/pull/5543/files
> Pure refactor: Move merge_directories

- conans/client/conf/__init__.py
Changelog: Feature: Added Clang 10 to the `settings.yml` base file.
Docs: omit
> Add Clang 10 support

- conans/test/unittests/client/tools/system_pm_test.py
Docs: omit
Fix the workaround here https://github.com/conan-io/conan/pull/5791#discussion_r339093531
> Mock the 'which' function

- conans/client/command.py
- conans/test/functional/command/download_test.py
Changelog: Bugfix: Allow ``conan download`` for packages without user/channel
Docs: omit
Close #6009
> fixing download without user channel

- conans/__init__.py
> Fix conan version in develop

- conans/client/cache/cache.py
- conans/client/cache/remote_registry.py
- conans/client/command.py
- conans/client/conf/config_installer.py
- conans/client/remote_manager.py
- conans/client/store/localdb.py
- conans/client/tools/win.py
- conans/test/functional/command/remote_test.py
- conans/test/functional/command/remove_test.py
- conans/test/functional/command/search_test.py
- conans/test/unittests/client/conf/config_installer/test_process_folder.py
- conans/test/utils/tools.py
Docs: Omit
- Python2 deprecation message in RED, with ***********
- Some pep8 fixes
- A couple of minor refactors, like ``registry_path`` => ``remotes_path``
> minor refactor

- conans/client/cmd/export_pkg.py
- conans/client/cmd/uploader.py
- conans/client/conf/__init__.py
- conans/client/rest/uploader_downloader.py
- conans/server/store/disk_adapter.py
- conans/test/functional/build_helpers/cmake_targets_test.py
- conans/test/functional/command/remove_test.py
- conans/test/functional/generators/cmake_test.py
- conans/test/functional/generators/make_test.py
- conans/test/functional/generators/visual_studio_test.py
- conans/test/functional/graph/version_range_error_test.py
- conans/test/functional/graph/version_ranges_diamond_test.py
- conans/test/functional/old/conanfile_extend_test.py
- conans/test/functional/package_id/compatible_test.py
- conans/test/functional/python_requires/python_package_reuse_test.py
- conans/test/unittests/client/cmd/export_test.py
- conans/test/unittests/client/generators/cmake_paths_test.py
- conans/test/unittests/client/generators/cmake_test.py
- conans/test/utils/tools.py
> remove unused imports

- conans/client/rest/uploader_downloader.py
Docs: omit
Continuation of https://github.com/conan-io/conan/pull/6142:
- Remove unused import
- Remove ugly SyntaxWarning due to parenthesis in assert
#tags: slow
> remove syntax warning

- conans/test/functional/graph/graph_manager_base.py
- conans/test/functional/graph/graph_manager_test.py
> simplifying graph tests

- conans/test/functional/remote/multi_remote_test.py
Docs: omit
#REVISIONS: 1
cc/ @AlexandreBossard
> Test remotes picked when doing a install with --update

- conans/test/functional/command/export_test.py
- conans/test/functional/command/imports_test.py
- conans/test/functional/command/info_test.py
- conans/test/functional/conanfile/deploy_test.py
- conans/test/functional/environment/apply_environment_test.py
- conans/test/functional/generators/cmake_multi_test.py
- conans/test/functional/generators/virtualenv_python_test.py
- conans/test/functional/generators/xcode_gcc_vs_test.py
- conans/test/functional/graph/private_deps_test.py
- conans/test/functional/graph_lock/graph_lock_ci_test.py
- conans/test/functional/graph_lock/graph_lock_py_requires_test.py
- conans/test/functional/old/options_in_requirements_test.py
- conans/test/functional/workspace/workspace_test.py
- conans/test/integration/only_source_test.py
- conans/test/integration/options_test.py
- conans/test/integration/revisions_test.py
- conans/test/unittests/client/generators/generator_filter_error_test.py
- conans/test/utils/tools.py
Docs: omit
closes https://github.com/conan-io/conan/issues/6178
> [refactor] Use 'client.load' in test code

- conans/test/functional/tgz_macos_dot_files_test.py
> Change scope of function in tests

- conans/client/generators/virtualenv.py
Docs: omit
After https://github.com/conan-io/conan/pull/5989 we can simplify `virtualenv` generator sources
> [refactor] Simplify 'virtualenv' generator sources

- conans/client/rest/rest_client_v1.py
> Refactor: remove unused quiet param and logic in RestV1

- conans/client/build/cmake.py
- conans/client/build/meson.py
- conans/client/build/msbuild.py
- conans/client/conan_api.py
- conans/client/installer.py
> minor refactor tools.environment_append

- conans/test/unittests/client/build/cmake_test.py
> fixing test indent and style

- conans/client/cmd/export.py
Docs: omit
Once saw it, you can't look away 🙈
> [refactor] Use preferred way to compare 'not in'

- conans/test/functional/conanfile/conan_data_test.py
- conans/test/utils/test_files.py
> improving data test

- conans/client/generators/cmake_common.py
- conans/test/unittests/client/generators/cmake_test.py
> [refactor] Move CMake messages inside the functions they refer to

- conans/test/unittests/util/tools_test.py
> Fix download unathorized test mocking config

- conans/client/conf/__init__.py
- conans/test/functional/command/config_install_test.py
> Fix requests library broken links

- conans/__init__.py
- conans/client/cmd/export.py
- conans/client/conf/detect.py
- conans/client/generators/cmake_common.py
- conans/client/migrations_settings.py
- conans/server/service/v2/service_v2.py
- conans/test/functional/conanfile/conan_data_test.py
- conans/test/functional/generators/cmake_multi_test.py
- conans/test/functional/generators/cmake_test.py
- conans/test/functional/remote/multi_remote_test.py
- conans/test/unittests/client/generators/cmake_test.py
- conans/test/unittests/client/tools/net_test.py
- conans/test/utils/test_files.py
- conans/util/files.py
> merge Release/1.21.2 to master

- conans/client/command.py
- conans/test/functional/configuration/python_version_test.py
Docs: omit
Notified here: https://github.com/conan-io/conan/pull/6336#issuecomment-582438805
> Fix typo in Python message

- conans/client/rest/rest_client_v2.py
- conans/test/functional/download_cache_test.py
Changelog: Fix: Avoid caching revision "0" under api V2 (revisions enabled) in the download cache
Docs: https://github.com/conan-io/docs/pull/1552
Fix https://github.com/conan-io/conan/issues/6467
> fixing mixing apis for download cache

- conans/__init__.py
- conans/client/generators/premake.py
- conans/test/unittests/client/generators/premake_test.py
Changelog: BugFix: Add ``system_libs`` to ``premake`` generator
Docs: Omit
Fix https://github.com/conan-io/conan/issues/6494
> fix missing system_libs in Premake generator

- conans/test/functional/generators/virtualenv_test.py
Docs: omit
After #6265, useless `if` condition and op
> After #6265 it is not needed

- .ci/jenkins/Jenkinsfile
> Run CI without Macos

- .ci/jenkins/Jenkinsfile
> Do not run CI for Macos (temporary)

- .ci/jenkins/Jenkinsfile
> Recover Macos CI

- conans/__init__.py
- conans/client/cmd/uploader.py
- conans/client/migrations_settings.py
- conans/model/graph_lock.py
- conans/paths/package_layouts/package_cache_layout.py
- conans/requirements.txt
- conans/test/functional/graph_lock/graph_lock_test.py
> merge release/1.22.2 to master

- conans/client/build/cmake.py
- conans/client/migrations_settings.py
- conans/test/functional/package_id/compatible_test.py
- conans/test/functional/scm/scm_test.py
- conans/test/unittests/client/build/cmake_test.py
> Merge master into develop

- conans/test/functional/scm/test_scm_to_conandata.py
Docs: omit
Add test with booleans
(Take care of some lines exceding max-length)
> Add test with booleans to 'scm_to_conandata'

- .gitignore
Docs: omit
Add the `.vscode` generated folder to the gitignore for convenience.
> Add vscode folder to gitignore

- conans/client/build/msbuild.py
- conans/model/graph_info.py
> use correct imports for tools

- conans/client/build/cmake_flags.py
- conans/client/manager.py
- conans/client/tools/oss.py
> remove wrong import and style
