README.md
The original one does not work for me. This one does.
=> correct git clone https URI in readme

conans/tools.py
Show more accurate human size when downloading small archives (and for big ones).
Was:
Percent: [########################################] 100.0% of 0.0Mb Done...
Unzipping 0 Mb, this can take a while
Become:
Percent: [########################################] 100.0% of 53 KB Done...
Unzipping 216 KB, this can take a while
=> Pretty human size when downloading

conans/client/command.py, conans/client/manager.py, conans/test/integration/package_command_test.py
Very useful for big libraries which with is not possible to just recompile if you have bugs in package method. Reads options/settings from build/xxx/conaninfo.txt and regenerate package folder.
conans package openssl/1.0.2@lasote/testing 9cf83afd07b678d38a9c1645f605875400847ff3
=> Package command

conans/client/command.py
This pull request makes conan to show the command name in a command help. Here is before/after for search command as an example:
Before:
```
$ conan search -h
usage: conan [-h] [--case-sensitive] [-r REMOTE] [-v] [-p PACKAGE] [pattern]
show local/remote packages
positional arguments:
pattern               Pattern name, e.g., openssl/*
optional arguments:
-h, --help            show this help message and exit
--case-sensitive      Make a case-sensitive search
-r REMOTE, --remote REMOTE
Remote origin
-v, --verbose         Show packages options and settings
-p PACKAGE, --package PACKAGE
Package ID pattern. EX: 23*
```
After:
```
$ conan search -h
usage: conan search [-h] [--case-sensitive] [-r REMOTE] [-v] [-p PACKAGE]
[pattern]
show local/remote packages
positional arguments:
pattern …
```
=> Show command name in command help

conans/client/rest/cacert.py
There is a problem with pip installation of package (and don't really know why with installer either), cacert.pem is autogenerated (for workaround the pyinstaller hell with statics) but it was trying to generate in installation dir. If I install conan as root (sudo pip install conan) and then, first use with regular user, access to write the file was forbidden.
=> cacert.pem auto generated, but in homepath

conans/client/manager.py
It fails because it tried to build in other folder.
=> Conan test command fixed

conans/client/remote_manager.py, conans/test/integration/complete_test.py, conans/test/remote_manager_test.py
fixed test that writed to user .conan/data, fixed bug error msg for no remotes
conans/test/remote_manager_test.py -> line 38, was causing writes to user .conan/data instead of temporary folders
=> Two minor fixes

conans/client/export.py, conans/client/installer.py, conans/client/packager.py, conans/operations.py, conans/util/files.py
this eliminate lots of problems with conan remove (specially .git folders), and other deletions, nightmare  in windows
=> Robust shutil.rmtree with onerror permissions

conans/client/detect.py
I've manually tested it (difficult to mock/patch), and it seems to fix the issue.
=> use regex instead of Version to search for gcc version. Should fix #50

.gitignore, conans/client/generators.py, conans/client/installer.py, conans/client/loader.py, conans/model/build_info.py, conans/paths.py
Add support for [YouCompleteMe](https://valloric.github.io/YouCompleteMe/) code-completion engine for Vim.  This will generate the python file for it to work with the build/install directories generated by conan.
As part of this change, I also added support for calculating the current cpp info when writing the generator.  This allows the current generator to take advantage of the packages intended compilation flags.
I also attached a property to each `ConanFile` that gets loaded called `conanfile_directory`.  This contains the directory from which the `ConanFile` was loaded. It's completely unrelated to the other change so we can probably create a separate pull request for it, if it's desired.
=> Add support for YouCompleteMe integration

.gitignore, conans/client/loader.py, conans/model/conan_file.py, conans/test/deps_graph_test.py
As discussed, creating pull request for `conanfile_directory`.  The big pro of attaching it as a property when the conan file is loaded is that the user doesn't have to worry about it; it's done for free.  The big con of doing it this way is that it's introducing *magic* that the user may be looking to figure out how this is done.
Another option would be to create the property in the base class that returns a private member.  When we load the conan file, I can set the member to the path provided.  It should be available immediately to the implementation except for the constructor (but that's a limitation of the current proposed implementation anyway).
=> Conanfile directory

conans/client/installer.py, conans/test/integration/private_deps_test.py
Private deps tests, as are defined are very slow (building shared libs in a complex graph), so I have just added some code to an existing test (thus adding about 8 seconds to test, in win which is the slowest).
The fix is simple, basically the computation of private dependencies skipping (not having to retrieve/build private dependencies for existing binaries), was not prepared for user projects, only for packages. For the current project, the ConanReference does not exist (and we cannot skip that dependency), so just avoiding it seems to be enough.
=> Enabling private_deps from current project, fix #79

conans/client/installer.py, conans/client/remote_manager.py, conans/paths.py, conans/test/integration/syncronize_test.py, conans/test/remote_manager_test.py, conans/test/tgz_md5_test.py, conans/test/upload_test.py
The upload/download of exported files is done file by file. This can be terribly slow if exporting a lot of files, which is the case for in-repository conanfiles.
Conanfile inside library repositories is necessary for package creators that want to develop their packages with conan too, i.e. for development of intermediate conan packages both with dependencies and dependees.
This PR is closely related to issues #80 and #77, asi it is related to the fact that there are packages that  can be under active development using conan to handle its dependencies, then package and upload to be used by others.
This is a necessary improvement towards that goal, targz'ing all the exported files for performance in upload/downloads.
=> TarGZ exported files to support conanfiles exporting whole source

conans/client/command.py, conans/client/conf/__init__.py
Fixes #78
It is only necessary to have a [proxies] section in the conan.conf file, it will take the system defaults. Remove [proxies] for proxies = None, or add your own proxies in conan.conf to override system defaults.
=> proxy configuration in conan.conf

conans/model/conan_file.py
I updated `conan_file.py#run` to pass through the working directory in the `ConanFile#run` method. It's not _necessary_, as the commands I use accept a directory argument, but it is far more convenient - I would no longer have to keep using:
```python
self.run("some_command args {build_dir}".format(build_dir=my_build_dir))
```
but instead use:
```python
self.run("some_command args", cwd=my_build_dir)
```
=> Add cwd parameter to conan_file#run, and pass it through to the runner

conans/client/generators.py
The current implementation of the qmake generator appends variables such as INCLUDEPATH twice for each included library by an oversight on my part. This commit fixes that.
In addition it makes the qmake generator behave more like the CMake generator. It now creates library-specific variables for things such as INCLUDEPATH, LIBS, etc., such as CONAN_INCLUDEPATH_POCO.
Further, you now have to explicitly specify that you want the basic setup, just like the CMake generator:
```
CONFIG += conan_basic_setup
include(conanbuildinfo.pri)
```
This allows the inclusion of conanbuildinfo if you wish to access the above mentioned library-specific variables without automatically cluttering the global INCLUDEPATH, LIBS, etc..
=> Make qmake generator similar to CMake generator

conans/client/generators/__init__.py, conans/client/manager.py, conans/model/conan_generator.py, conans/util/files.py
This PR addresses https://github.com/conan-io/conan/issues/74
It has been done just for user side project generated files (conaninfo.txt and all generators: conanbuildinfo.cmake, ...) The problem with doing it for all files, i.e. also for package files is that packages are SHA signed in the manifest, so changing line endings can cause troubles. Also they would very rarely be inspected, so I think it can be enough with user side files.
=> normalizing in Win crlf for user generated files

conans/__init__.py, conans/client/conf/__init__.py, conans/client/migrations.py
Related to: https://github.com/conan-io/conan/issues/86
It adds several ARM architectures to default settings.yml (deprecate old "arm")
Also adding some gcc older versions, as requested by some users.
The migration just creates a backup file with old settings if modified by user.
=> changed settings with migration

conans/client/command.py, conans/client/loader.py, conans/client/manager.py, conans/test/conanfile_extend_test.py
This PR partially addresses #77, #83, and #80:
It allows to define any custom conanfile to load for commands install, build & info.
- It allows having a .conanfile.txt and load it with (--file, -f) as (cc/ @mcraveiro):
```
$ conan install --file=.conanfile.txt
```
- You can have as many conanfile.txt files as you want for your projects:
```
$ conan install --file=conanfile_test.txt
$ conan install --file=conanfile_production.txt
```
- It allows defining different conanfiles for dev and production. The tests included show that, for example, the dev conanfile can **extend** the production conanfile to add test libraries, for example, so DRY (cc @bjoernpollex, @azriel91)
```
$ conan install -f=conanfile_dev.py
```
It works for **build and info commands too**. Please note, that not for …
=> allow loading custom name conanfile for install, build & info

conans/client/detect.py
This fixes an issue raised by @TyRoXx in twitter, when running on a Raspberry PI.
The architectures detection might not be perfect, as I haven't been able to run on different machines, and also unable to find a reasonable reference of them online. But at least should be better than the current mis-detection.
=> fixed #163 arm initial auto detection

conans/tools.py
- Insipired in #92. Now it uses the existing downloader (that uses requests) to download files from conanfile.
-  Working with sourceforge ok.
Thanks @mathieu, your approach with requests is just fine. Sorry for the delay.
=> Download files from conanfile.py using our own downloader

conans/client/command.py, conans/client/installer.py, conans/client/loader.py, conans/client/manager.py, conans/client/proxy.py, conans/client/remover.py, conans/client/uploader.py, conans/test/download_test.py
I have started to implement the "update" feature, with packages that are overwritten, knowing if downstream have to update to latest. 
I was checking where to implement it, and realized that there were several methods in ``ConanInstaller`` totally related to ``RemoteManager``, while the main responsibility of ``ConanInstaller`` is clearly building things, and managing export=>source=>build=>package when upstream binaries are not available.
``RemoteManager`` is clearly more related to connection to the remotes, and executing remote commands. So I decided to propose a Proxy class that can be put in the middle and is the responsible of "middleware" interceptions, as e.g. the update feature, when requested a conanfile.
=> extracted from installer retrieve methods

conans/tools.py
If we tried to download a zip (in conanfile source method) from a valid https domain it can still fail because it depends if our local computer (issue detected in appveyor) have a valid openssl with a ssl authorities list. The requests client uses this autorities list to verify that the remote certificate is valid.
Even you specify verify=False for requests library it failed too (maybe its a requests bug).
The PR uses the list that we already used for our server connections.
=> SSL verify

conans/client/cmake.py
I have had to upgrade my computer, realized that the standard mingw version now is gcc 4.9, not 4.8, and it no longer requires Unix Makefiles for cmake (my special old 4.9 required them, nuwen I think).
Tests passing in win10 with mingw 4.9. Might fail in CI appveyor... lets see.
=> mingw4.9 no longer use Unix Makefiles

conans/client/cmake.py, conans/client/manager.py, conans/test/command/export_test.py
Win was overwriting package HelloX, with package hELlox, due to filesystem insensitiveness.
=> check in conan export for case insensitive OSs. Fix #171

conans/client/installer.py, conans/client/manager.py
If you mark a requirement in a project as private it doesn't get installed. Added a check for private packages if the requirer isn't the package to be build. Tests seem to pass, should which would be fixed by the pull request?
=> _compute_private_nodes checks if the private_requirer isn't the orignal node.

conans/client/file_copier.py
- It allows to export "../files" relative to current conanfile.py.
- The motivation is maybe having the conan stuff in the same project/repo than original project, but maybe we want to put the conanfile.py and test folder (very common that it collide with the project test folder) in a directory ".conan".
.conan/conanfile.py
.conan/test/main.cpp
CMakeLists.txt
proyect.cpp
proyect.h
- This way, the exports could be something like "exports = ["../*"]", and not git clone in source would be required.
=> Allow to export upper directory files

conans/client/export.py, conans/client/file_copier.py, conans/client/manager.py, conans/client/packager.py, conans/test/integration/complete_test.py, conans/test/tools.py
Does a full copy report in export(), package() and imports(), as pointed out in #200
- Only warns in package()
- Maybe export() and imports() could be avoided, it makes output more verbose, but I think it is also useful to check things are ok.
=> fixes #200, implements reporting of copies

conans/client/proxy.py, conans/client/rest/rest_client.py, conans/client/rest/uploader_downloader.py
I have had a look to this issue. First, it is not related to a "version check" error, it is a connection error during a normal download. Maybe the last layer of the communication stack which is called VersionChecker was confusing.
I tried it disconnecting the network in the middle of a download. The only issue, is that it takes a lot, until it realizes it is disconnected, I guess this is a good thing. Actually, if the network is up again, it resumes download.
=> ConanConnectionError for disconnection while downloading. Fix #211

conans/client/loader.py, conans/test/conanfile_loader_test.py, conans/test/integration/flat_requirements_test.py, conans/util/config_parser.py
The interface to the ConfigParser could be improved, as it is returning text instead of list of lines, which it had already computed. But, by now, I prefer to keep it simple, as that would break the ConanInfo parser, so lets keep changes to a minimum now.
=> allowing inline comments in conanfile.txt. Fix #224

conans/client/rest/uploader_downloader.py
Found a performance issue when downloading large conan packages. Boost took 30+ secs on my machine and only 1-2 secs in the browser. After the simple changes in this changeset the performance is now acceptable (comparable to the browser). 
Please consider downloading all conan packages by streaming downloads to temporary files, and not to memory, then to disk - as we are seeing some packages with a size of 500+ MB.
=> Bugfix: Bad performance when downloading large files.:w

conans/client/manager.py, conans/client/printer.py, conans/paths.py, conans/test/command/info_test.py, conans/test/integration/multi_remotes_test.py
Also related to #245, but not directly. ``conan info`` was still checking for updates as default, so really slow. Made it opt-in.
=> opt-in for check updates in conan info

conans/client/generators/visualstudio.py
Added the dependent dll paths to the 'ExecutablePath' msbuild property in the Visual Studio Generator.
=> Fix for 'Visual Studio generator dll paths #264'

conans/test/tools.py
This allows the tests to be run on more recent OS X versions.
=> test: Allow user to override CONAN_LIBCXX during tests

conans/client/generators/cmake.py
Fix #269 
To opt-in in using "system-headers", define in CMake, prior to conan_basic_setup():
```cmake
set(CONAN_SYSTEM_INCLUDES "On")
conan_basic_setup()
```
Alters the behavior introduced in issue #126, by @TyRoXx , making SYSTEM now opt-in instead of hard-coded, as it turns out that in gcc it has some unexpected side effects (read #269).
=> making system includes in cmake opt-in

.gitignore, conans/client/generators/cmake.py, conans/test/generators/cmake_test.py
I made a simple modification to fix the issue #291. For each dependency, the `CONAN_<dep>_ROOT` is appended to `CMAKE_PREFIX_PATH`.
I tested it on Linux with a modified Protobuf package (https://github.com/osechet/conan-protobuf) where the test's CMakeLists calls `find_package()` and `protobuf_generate_cpp()`.
=> Append dependency's root path to CMAKE_PREFIX_PATH

conans/tools.py
Python already supports detecting the zip format by
open the tarfile with r*. This just changes r:gz to r:*
and adds extra checks for tar.bz2 and tbz2.
=> Support bzip2 archives as well as gzip ones

conans/client/installer.py, conans/client/packager.py
Some of the C++ projects which use CMake as a build system have an install target. Their listsfiles already contain the definition of what and how should be installed. Defining the installation steps of the project in the `package` method of the `ConanFile` duplicates this information. Ideally I would like to maintain the code for installation at only one place. 
So for projects with an install target, in the `package` method of the ConanFile we can build the install target instead of defining again which files need to be copied.
For this packaging method to work, the [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/v3.6/variable/CMAKE_INSTALL_PREFIX.html) of the project should be set at the CMake configuration step, when the `build` method is called, but at the moment the …
=> Set package_folder attribute of ConanFile instance before build

conans/client/configure_environment.py, conans/test/compile_helpers_test.py
Some configure scripts doesn't seem to honor C_INLUDE_PATH and
CPP_INCLUDE_PATH but instead expect -I <path> to be set in CFLAGS
and CPPFLAGS. I ran into this in the Python configure script
Adding them here should not have any negative effects except listing
some of the include paths twice if the configure script honors
both environments.
An alternative approach would be to allow a option to be set to
tell it where to add the include paths, but it might be to complicated.
=> Add include paths to CFLAGS and CPPFLAGS.

conans/client/cmake.py
This can be used to force Ninja as the generator instead of Unix
Makefiles for example.
Fixes #329
=> Add CONAN_CMAKE_GENERATOR to override the cmake generator used.

conans/client/configure_environment.py
Similar to #319 some configure scripts doesn't respect LIBS environment
but rather expect all libs to be listed in LDFLAGS.
=> Add all libs link lines to LDFLAGS as well as LIBS

conans/test/update_settings_yml_test.py
The settings in the update_settings_yml_test failed because
my compiler was a higher version number than the ones listed
in there. I have updated the settings.yml in the source file
but we might want to make sure that these settings are shared
between the test and what we ship in the acutal application
to avoid these problems in the future.
=> Fix tests on recent versions of OSX and Xcode

conans/tools.py
After searching for why my files where not patched correctly
way to long I came to the conclusion that the patch tool actually
silently failed. This is pretty bad behavior if something changes
so I have added a exception for this.
=> Don't fail silently when patching files

conans/client/generators/__init__.py, conans/test/integration/custom_generator_test.py
For what I was doing with the PkgConfig generator I had to
be able to generate one file per dependency. The current
generator system was not able to handle this. Fortunately
it was a easy change without having to break any current
generators.
=> Add support for letting the generators save multiple files.

conans/__init__.py
The version of conans doesn't reflect the correct version, thus the client complains that the server is not up to date althought it is using the correct branch.
=> bump version to 0.10.1

conans/client/detect.py
The compiler detection (at least linux, gcc) fails when using python 3, because the following line in conans.client.detect._execute throws an exception:
`return proc.returncode, "".join(output_buffer)`
The reason is that in Python 3 the output_buffer is a list of bytes, not strings.
This commit should fix that.
If you want, I can write a test for that as well, because I haven't tested it with Python 2, if you tell me in which file to put the test case - maybe conans/test/command/install_test.py?
=> Fixed failure to detect compiler with Python 3

conans/server/conf/__init__.py
The ``ConfigParser`` converts by default every key to lowercase, including the user names. See issue #423.
I think usernames with uppercase should be allowed, to match possible user names in conan.io, and other services as github. All the default files are already lowercase, so it shouldn't be a problem, but please check.
=> disabled ConfigParser default conversion to lowercase

conans/requirements_osx.txt
This is in reference to issue #431
=> Peg cryptography module to less than version 1.5

conans/client/remote_registry.py, conans/client/rest/auth_manager.py, conans/test/registry_test.py
This addresses issue #436 
I have also removed localhost from the default remotes.
=> fixed conan.io msg in login other remotes. Removed default local

conans/requirements.txt
In Arch Linux, requests got updated to 2.11.1 and PyYAML to 3.12.
=> Bump version requirements for requests and PyYAML

conans/client/rest/auth_manager.py
When we get a valid token during the retry_with_new_token we should handle the return with `wrapper` function, to handle right a ForbiddenException, and showing a message without the body like:
```
ERROR: {
"errors" : [ {
"status" : 403,
"message" : "Forbidden"
} ]
}
```
=> Fixed forbidden flow

setup.py
Dash ('-') in version "0.12.1-dev" breaks the regex. Allow the version to contain dashes.
=> Unbreak setup.py's build()

conans/client/command.py
Added -u option to the argument parser and use it in the install phase.
=> Allow -u option in test_package

conans/client/conf/__init__.py, conans/client/detect.py
Adds powerPC (ppc64le) as architecture: issue https://github.com/conan-io/conan/issues/405
Detect ``AArch64`` as ``armv8`` architecture: issue https://github.com/conan-io/conan/issues/417
=> added new ppc and aarch64=>armv8 architectures

conans/test/tools_test.py, conans/tools.py
This should implement: https://github.com/conan-io/conan/issues/537
Note: I have NOT protected against an ImportError. Those errors where happening in the installer (deb, win), as pyinstaller didnt bundle multiprocessing. Now that the import is explicit to multiprocessing, it seems that the installer also work (tested in the installer in Win, should be tested in other OSs)
=> adding tools.cpu_count

conans/client/loader.py, conans/client/manager.py, conans/test/integration/only_source_test.py
This should solve issue: https://github.com/conan-io/conan/issues/545
Generating conanbuildinfo.txt not necessary, now you can specify it with ``-g txt`` argument
=> do not automatically generate conanbuildinfo.txt for install ref

conans/client/remote_manager.py
When we have files in the recipe with bad dates (epoch time) we need to touch the files to avoid problems as the one described in #556.
This change should fix that issue. 
Note that this piece of code could be extracted to a independent function and be reused in get_recipe and get_package, since it is exactly the same. I leave that improvement for the principal maintainers since I am not confident enough with python ;)
=> Touch files when getting the recipe. It fixes #556

conans/client/configure_environment.py
You can pass -Wl,-s to some linkers when using clang
on Linux but it's not generic enough to warrant some
special sauce. This get's rid of a warning that is
pretty annoying.
=> Clang doesn't like -s so let's not add that

conans/client/command.py, conans/client/manager.py, conans/client/source.py
I allowed myself to propose solution for #607 and #604. 
It will not change behavior for existing conan source < ref > command.
I tested it manually and it seems to work. Now I will try to write some tests to be sure :). Any hints and feedback appreciated. 
Briefly:
- allows user to call "conan source < directory_name >"
- will download whatever is specified in ConanFile source() command to current working directory
- behavior of dirty flag is slightly changed for local directories - it will warn user that source directory is dirty and continue anyway
- it will never delete local source directory (it assumes that user knows what he is doing)
- I also fixed help messages for build, export and package commands (minors - capital letters, etc.)
Unknowns:
- I'm not copying exports to source …
=> Command conan source working for local directories

conans/model/manifest.py
When manifests are stored in revision control system, it's necessary to
reduce differences to simplify review of changes. That requires reproducible
order of files, e.g. alphabetic sorting.
=> Sort file list when generating manifests

conans/client/command.py, conans/client/output.py, conans/client/remover.py, conans/test/output_test.py
This should help with: https://github.com/conan-io/conan/issues/653
After many hours of trying different things, I have added a fallback ascii output when errors raise. Also, changed the messages from ``conan remove``, which OSError messages were the cause of some issues (when ran in Cyrillic or other alphabets, which typical Win terminal cp850 encodings cannot handle).
Lets see how it goes with CI...
=> improved encoding failures

conans/model/config_dict.py, conans/test/model/settings_test.py
When compairing a ConfigItem defined by `ANY`, it automatically failed because the `values_range` was empty. I just don't use `values_range`when defined by `ANY`
=> Taking in account "ANY" config definition

conans/model/manifest.py
Conan generated manifests which didn't end with "\n" character. Such files
are shown by git with warning 'No newline at end of file', and they also
trigger warnings in style bot used by Qt review system. Editors like vim
add trailing line feed automatically, and it's generally considered to be
a good style for text files.
Also fixed parsing of anifest files ending with line feed.
=> Add line feeds at the end of generated manifests

conans/client/remote_manager.py
To solve: https://github.com/conan-io/conan/issues/682
=> added connection message error to output

conans/client/require_resolver.py, conans/test/model/version_ranges_test.py
This improves the behavior of the node-semver library used for version ranges, removing the annoying, version "2.1" not being solution for "<=2.1", plus avoid crashing for versions not semver, as "master".
It seems that with this we could avoid forking the upstream lib. Plus it is not fully clear to me a fix to such lib, without messing too much, as the source of the problem seems the prerelease part of the version being automatically added, might break things if removed or modified?
cc/ @DEGoodmanWilson
=> minor fixes and worarounds around node-semver

conans/requirements.txt
boto is not used by Conan. Remove the formal dependency from requirements.txt.
=> remove dependency on boto

conans/client/cmake.py, conans/client/conf/__init__.py, conans/client/configure_environment.py, conans/test/model/other_settings_test.py, conans/test/model/transitive_reqs_test.py, conans/tools.py
Basic support for FreeBSD (#742):
FreeBSD listed under os in the default settings
CMake generators
OSInfo tools (is_freebsd and os_version)
=> FreeBSD minimal support

conans/client/cmake.py, conans/client/conf/__init__.py, conans/client/configure_environment.py, conans/client/detect.py, conans/test/model/other_settings_test.py, conans/test/model/settings_test.py, conans/test/update_settings_yml_test.py, conans/tools.py
For issue #742:
1. Change default compiler to clang with libc++ on FreeBSD
2. Fix a few unit tests with FreeBSD in acceptable OS in default config file
Four kinds of error and failure remain in tests:
1. g++ not available (it's not installed by default on FreeBSD). Maybe replace with a clang test for FreeBSD?
2. Assertions on env variables fail because only the labels are written in the outputs, not the values. Happen in "ProfileTest._assert_env_variable_printed()". No idea, couldn't find where those output lines are generated by the client.
3. Go isn't available (again not installed by default, could we make those optional?)
4. conan.conans.test.integration.python_diamond_test.PythonDiamondTest fails because it expects string like "Hello Hello4" and gets "Project: Build stuff Hello3". …
=> FreeBSD support, part 2

conans/client/client_cache.py, conans/client/command.py, conans/client/printer.py
I've added a simple conan command to query available profiles:
- list: show the list of available profiles
- show <profile>: displays the profile
I'm not too fond of the [_root] hack in Scopes but I'm not certain I master Conan's code enough to propose a better alternative.
=> Basic profile query commands: list and show

conans/client/client_cache.py, conans/client/proxy.py, conans/client/remote_manager.py, conans/paths.py, conans/test/path_exists_test.py, conans/util/files.py
NOT TO MERGE, a proposal to review:
- Remove ``path_exists`` from client operations
- Check in ``Paths``, always a conanfile path or conanfile manifest is requested
- Simplified files -> ``mkdir``, ``path_exists`` removing unused code
- Clean ``path_exists_test``, removing unnecessary slow build.
=> my proposal for fixing the case-sensitive paths

conans/client/remote_registry.py, conans/server/test/utils/server_launcher.py, conans/test/command/export_path_test.py, conans/test/command/export_test.py, conans/test/compile_helpers_test.py, conans/test/integration/profile_test.py, conans/test/utils/cpp_test_files.py, conans/test/utils/test_files.py
- Addresses #784 
- Logger changes in the fasteners is to avoid too much undesired trace in the shell during the test builds.
- Deactivated spaces in paths for FreeBSD (Make problems)
- quiet parameter for test server launcher
- Used "cc" instead of "gcc" and "c++" instead of "g++". In FreeBSD it works with clang
=> FreeBSD green build

.travis.yml, conans/client/command.py, conans/client/deps_builder.py, conans/client/installer.py, conans/client/manager.py, conans/client/proxy.py, conans/client/remote_manager.py, conans/client/rest/auth_manager.py, conans/client/rest/rest_client.py, conans/test/download_test.py, conans/test/integration/info_test.py, conans/test/integration/install_outdated_test.py, conans/test/integration/private_deps_test.py, conans/test/model/transitive_reqs_test.py, conans/test/model/version_ranges_test.py, conans/test/path_limit_test.py, conans/test/remote/rest_api_test.py
#772 
With install refactor, `conan info --build` command that will "simulate" an install and return a list of nodes to be built.
Not used `--build_order` parameter because it has a different meaning, maybe less useful.
=> Installer refactor + #772

conans/client/generators/cmake.py
This commit fixes potential errors when CONAN_VERSION variable
in conan_split_version() function is not set so the command
is interpreted as with 3 arguments only. This could also help if
the variable has spaces so the command is interpreted with 5 arguments.
As a rule, always quote cmake command arguments
See https://travis-ci.org/foonathan/type_safe/jobs/186587154#L756 and https://travis-ci.org/ChaiScript/ChaiScript/jobs/186450865#L558 for examples of this error.
=> Quote string(REPLACE) cmake command fourth argument

conans/client/conf/__init__.py, conans/test/client_conf_test.py, conans/test/integration/settings_override_test.py
#489
It allows to override default settings from environment variables. If a setting with subsettings like compiler is defined (CONAN_ENV_COMPILER) the subsettings are ignored from the conf file and they need to be defined as an environment variables too.
=> Allow to define default settings as Environment variables

conans/client/remote_manager.py
When checksumming files for upload it could fail, currently
it's really hard to figure out what's going wrong since it
just says fails. This patch adds more feedback on what files
that fails.
=> Give better warning message when package integrity fails

conans/client/generators/cmake.py, conans/client/generators/cmake_multi.py
At the momemt conan's cmake generators `cmake` and `cmake_multi` create the following code if i use `conan_basic_setup(TARGETS)` in my cmake file
```cmake
conan_find_libraries_abs_path(${CONAN_LIBS_MYPROJECT} ${CONAN_LIB_DIRS_MYPROJECT}
CONAN_FULLPATH_LIBS_MYPROJECT)
```
If you have multiple arguments for `CONAN_LIBS_MYPROJECT` or `CONAN_LIB_DIRS_MYPROJECT` like with poco, the arguments are not correctly handled.
We could easily fix that by adding quotation marks.
```cmake
conan_find_libraries_abs_path("${CONAN_LIBS_MYPROJECT}" "${CONAN_LIB_DIRS_MYPROJECT}"
CONAN_FULLPATH_LIBS_MYPROJECT)
```
=> fix incorrect argument handling with conan_find_libraries_abs_path function

conans/client/remote_registry.py, conans/test/command/remote_test.py
Should fix: https://github.com/conan-io/conan/issues/854
The approach is to NOT ALLOW duplicated URLs in remotes, it doesn't make sense and it is confusing
=> fixed duplicated URLs in remotes

conans/client/cmake.py, conans/client/conf/__init__.py, conans/client/configure_environment.py, conans/client/detect.py, conans/paths.py, conans/test/integration/conan_env_test.py, conans/test/model/other_settings_test.py, conans/test/model/settings_test.py, conans/test/model/transitive_reqs_test.py, conans/test/update_settings_yml_test.py, conans/tools.py
Added extra informations to enable conan to work with Solaris x86
=> Added support to Solaris 

conans/client/generators/cmake_common.py
'-' can occur in the compiler name in config files, so honor them too. Without them, CONAN_COMPILER is extracted as 'apple' for 'apple-clang' with all the consequences.
=> Fixing “compiler=apple-clang” parsing from conaninfo.txt performed by conanbuildinfo.cmake

conans/client/rest/rest_client.py
=> #685 remove trailing slash from the remote URL

conans/client/generators/cmake_common.py
In case cross compilation some toolchain defines
```
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
This effectively prevents conan to find proper libraries.
But in case of conan the path is already known and there is no need to search for library in other places.
=> Fix conan_find_libraries for cross-compile.

conans/client/export.py, conans/client/source.py, conans/test/integration/symlinks_test.py
Previously, the `FileCopier` used for exporting did not preserve symbolic links. This caused issues for packages which contain static asset libraries. For example:
```
├── shared_library.so -> shared_library.so.2
└── shared_library.so.2
```
If the package exports these files, the symbolic link was not previously preserved. Instead, the conan store would receive duplicates of the same file, under the different names.
I believe the `links=True` addition to the export logic will change this behavior.
=> Preserve links when exporting

conans/test/conanfile_tools_test.py, conans/tools.py
If something goes wrong with tools.patch() today you
get a very generic problem and it can be hard to track
down. Fortunately patch provides a logging logger that
can be used to output ConanOutput information. This
gives way better info than just the generic exception.
=> Add loghandler for patch module

conans/client/configure_environment.py, conans/client/generators/scons.py, conans/test/compile_helpers_test.py
Use CXXFLAGS for C++ flags instead of CPPFLAGS intended for the C preprocessor.
Not sure if using the CPPFLAGS variable was intended, but it seems that it was breaking one of my C build because the flags were fed to the C compiler that was rejecting them.
=> Use CXXFLAGS instead of CPPFLAGS 

conans/test/model/profile_test.py
This test proves that https://github.com/conan-io/conan/issues/978 has already been fixed by recent PRs by @lasote.
=> added test to verify #978

conans/client/generators/cmake_common.py, conans/test/generators/cmake_test.py
Should address: https://github.com/conan-io/conan/issues/950.
It would be good to test against some existing packages using cppflags, cxxflags, etc.
If @kent-at-multiscale could try running from sources from this branch, it would also be great feedback.
=> removing quotes from cmake flags

.travis.yml, conans/build_info/conan_build_info.py, conans/client/client_cache.py, conans/client/command.py, conans/client/rest/rest_client.py, conans/client/rest/uploader_downloader.py, conans/paths.py, conans/test/integration/test_build_info_extraction.py, conans/test/put_properties_test.py, conans/test/tools.py
- Partial build-info objects only with downloads.
- Custom PUT headers with an `artifacts.properties` file.
- OSX logging level increased, the builds fail because of the MAX log size
=> Artifactory build-info processing changes

conans/client/require_resolver.py, conans/test/integration/version_ranges_conflict_test.py
This was metioned in #747, but never fixed.
=> Changed output of invalid downstream requirements from warn to werror

conans/client/export.py, conans/client/source.py, conans/test/command/package_command_test.py
The local ``conan source`` command was copying all the origin folder, which is weird, because in normal operation, it will do the ``exports`` only. 
Address: https://github.com/conan-io/conan/issues/1095
=> local source command execute export

conans/client/command.py, conans/test/command/profile_test.py
```conan profile list``` should list profile alphabetically instead of relying on filesystem order.
=> Order profiles in 'profile list' by name instead of file system timestamp

conans/client/cmake.py, conans/test/functional/cmake_test.py
- To be able to alter the `.definitions` dict after the CMake() instantiation.
- All automatic definitions built with quotes using the same function.
=> CMake helper build_type and runtime as a configurable definition

conans/server/service/authorize.py, conans/test/server/service/authorizer_test.py
Just spent some time trying to figure out why user authentication wasn't working in my Conan installation, until I realized that Conan server doesn't allow for spaces between usernames in the `[read_permissions]` and `[write_permissions]` sections of `server.conf`. No big deal, but I figured I might as well propose this tiny change to allow for such spaces. It's an easy, nitpicky thing to overlook when setting up Conan, and it might just save someone else a few minutes.
=> Allow spaces in permission spec in server.conf

conans/client/command.py
Just a fix for a tiny annoyance I had :).
This computes the required tabulation amount based on the length of the longest command and synthesizes a format string. It is also required to strip the help string because sometimes there is an extra whitespace. 
(left - before, right - after)
=> Fixed tabular indentation in help text

conans/tools.py, conans/util/files.py
This mirrors tools.check* functions. And since we should
encourage people to use sha256 instead of sha1 it's good
to have this util function available.
=> Expose sha256sum in tools.

conans/client/generators/cmake_common.py, conans/test/integration/cmake_flags_test.py
A fix for #1321 to be able to use CMake's RelWithDebInfo/MinRelSize configurations
=> Add RelWithDebInfo/MinRelSize to cmake generators (#1321)

conans/client/configure_build_environment.py
The `configure_dir` parameter of `AutoToolsBuildEnvironment.configure`
should work with just the directory name, without a trailing slash.
Since configure scripts don't run in Windows environment, `os.path.join`
was not used in this case.
This addresses issue #1322.
=> Fix required slash in configure_dir of AutoToolsBuildEnvironment

conans/client/generators/scons.py
Just like the cmake and txt generators, the scons generator now
supports so called "multi-config variables".
name = mylib
def package_info(self):
self.cpp_info.regex.libs = ["myregexlib1", "myregexlib2"]
self.cpp_info.filesystem.libs = ["myfilesystemlib"]
From this snippet, the generator will create in SConscript_conan the keys:
- conan
- conan:regex
- conan:filesystem
- mylib
- mylib:regex
- mylib:filesystem
All the keys containing a colon are the new generated ones.
=> Support multi-config variables for the scons generator

conans/client/manager.py, conans/test/command/search_test.py
Now, if searching a remote, no "outdated from recipe" info is output, but it is interesting.
In fact, it is using the local recipe if existing to provide that info. I think this might be confusing, so I propose to use always the remote recipe.
=> print outdated from recipe in remotes

conans/client/detect.py
It looks like my last PR (#1309) does not really add support for GCC 7.1, since GCC new configure option `--with-gcc-major-version-only` break Conan's GCC version detection.
With `--with-gcc-major-version-only` enabled (which is the default for packaged versions of GCC), the `-dumpversion` argument no longer return the full version but only the major version number.
We need to use the new `-dumpfullversion` argument in order to retrieve the full version.
Relevant GCC patch : https://gcc.gnu.org/ml/gcc-patches/2017-01/msg00567.html
This PR make `_gcc_compiler()` function to use `-dumpfullversion` if `-dumpversion` return only one number.
=> Add support for GCC 7.1+ detection

conans/client/conan_api.py, conans/client/installer.py, conans/test/command/install_test.py, conans/test/integration/conan_test_test.py, conans/test/integration/only_source_test.py
https://github.com/conan-io/conan/issues/1366
Could break something. Until now, the "*" was automatically being added to the created ``--build=Pkg`` by the ``test_package`` command. So if someone is relying on ``conan --build=Pkg`` to find and build ``PkgLibrary`` it will not work. They will have to change to ``conan --build=Pkg*``
=> fixing test_package pattern

conans/client/command.py, conans/client/conan_api.py, conans/client/new.py, conans/client/new_ci.py, conans/test/command/new_test.py
This PR provides GitLab CI support for Gcc and Clang, by `conan new`
I tested this feature in Gitlab, with Catch project. The gitlab recipe created by conan new is [here](https://gitlab.com/uilianries/conan-catch/blob/playground/.gitlab-ci.yml) and you can see all tests results [here](https://gitlab.com/uilianries/conan-catch/pipelines/9088694).
Gitlab CI looks like Travis, however, some aspects are not present in both:
* There is not Travis matrix in Gitlab CI, it uses multiple jobs and all are named.
* Also, in Gitlab you can choice the docker image for each job, different from Travis.
* Gitlab doesn't support `sudo: required` as Travis, so, we need to call `sudo` when necessary.
* In Gitlab, `script:` must be present for each job. In Travis we could use only a global declaration.
I …
=> #1399 Conan new generates Gitlab CI

conans/client/configure_build_environment.py, conans/client/generators/virtualbuildenv.py, conans/client/generators/virtualenv.py, conans/test/functional/autotools_configure_test.py, conans/test/functional/build_environment_helpers.py, conans/test/integration/conan_env_test.py, conans/test/utils/conanfile.py
#1287, #1408 and #1389
**Goal:** virtualbuildenv append to flags (CPPFLAGS, LDFLAGS...etc) the previously declared env variables, for example from a profile, from -r...etc
**Problem solved**: Conan only appended variables with previously environment value if the received value was a list, and it joined all the values with `os.pathsep`. But it was a problem, CPPFLAGS etc should be joined with spaces so a list with known variables `append_with_spaces` has been added to `VirtualEnvGenerator`
UPDATED, Also VisualStudio similar problems (#1408 and #1389)
=> Appending environment variables in BuildEnvTools and VirtualEnvTools

conans/client/generators/cmake_common.py
There were missing defines for CMake configuration RelWithDebInfo/MinRelSize
=> Add RelWithDebInfo/MinRelSize defines to CMake generator

conans/test/util/tools_test.py, conans/tools.py, contributors.txt
Hi guys!
I bring a new tool support for FreeBSD: **pkg**
Here are some important references about pkg:
[pkg-install](https://www.freebsd.org/cgi/man.cgi?query=pkg-install&sektion=8&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports)
[pkg-info](https://www.freebsd.org/cgi/man.cgi?query=pkg-info&sektion=8&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports)
[pkg-update](https://www.freebsd.org/cgi/man.cgi?query=pkg-update&sektion=8&apropos=0&manpath=FreeBSD+11.0-RELEASE+and+Ports)
To test this feature, I used Vagrant to create a VM with FreeBSD-11.0, after that, I just created a dummy project by `conan new`:
```python
def build_requirements(self):
if self.settings.os == "FreeBSD":
package_tool = tools.SystemPackageTool()
package_tool.install("tree")
```
As result:
```shelll …
```
=> #1496 SystemPackgeTool on FreeBSD

conans/client/loader_parse.py, conans/client/manager.py, conans/test/integration/load_requires_file_test.py
For our projects, we're loading the list of 'requires' from an external yml file into the conanfile.py recipe. The yml file is called the same thing in each project. Once we attempted to build a consumer project, the dependent project claimed to have a dependency loop.
After adding some print statements to both recipes, it was discovered that the list of 'requires' for the consumer project was being injected into the dependent project. Once we debugged the Conan code, it was realised that the current working folder always stays the same and points to the consumer project.
When the dependent projects conanfile.py was loaded, the recipe was parsed and the code to dynamically load the list of requires runs and looks for the yml file and because the current working folder is set to the …
=> Change current working directory for the loaded conanfile.py

conans/client/cmake.py, conans/test/functional/cmake_test.py, contributors.txt
Hi! 
This PR is an enhancement to provide `CMAKE_VERBOSE_MAKEFILE` in CMake helper.
Related issue: #1569
Regards.
=> Add verbose definition for cmake helper

conans/client/new_ci.py
If you specify in the constructor the user and channel in the **build.py** are not overrideable by the CI environment variables. I think we should remove it. Am I missing something?
=> Not user/channel as parameter in constructor of generated build.py

conans/test/util/tools_test.py, conans/tools.py
Hello,
This PR is to add support for the pkgutil system package tool on Solaris.
This package tool is not an official one, it's linked to the [OpenCSW ](https://www.opencsw.org/about/) project that makes pre-compiled binaries for the SunOS platform easily available.
This project is however used a lot by Solaris systems administrators for the convenient and large binaries catalog they provide (and because of the poor quality of the default available tools...).
An issue I faced was with "installed" method that I copied from the BrewTool:
`exit_code = self._runner('test -n "$(brew ls --versions %s)"' % package_name, None)`
I don't have a mac to test this command but from what I understand it tries to check if the output of `brew ls --versions` is empty or if it contains the package we are …
=> Adding support for system package tool pkgutil on Solaris

conans/client/generators/cmake.py, conans/client/generators/cmake_common.py, conans/test/generators/cmake_test.py
This small change adds the settings from the install command to the generated cmake file.
Based on this, I can define some other includes I want to make in my own cmake files and mainly I can restrict the Visual Studio build to the installed build_type via CMAKE_CONFIGURATION_TYPES to avoid confusion.
=> Add conan settings to cmake generated file

conans/model/conan_generator.py
It looks like an oversight that there's no property to access to this convenience variable.
=> Add property for access to _deps_user_info

conans/test/util/tools_test.py, conans/tools.py
Hi!
This PR brings  ![Chocolatey](http://i.imgur.com/6eqVxxE.png) into `SystemPackageTool`. 
Some points may be observed:
* Chocolatey doesn't have a real `update` like *apt* and *brew*, but there is an opened [issue](https://github.com/chocolatey/chocolatey/issues/320). For such feature, I'm used `choco outdated`, a shortcut for `choco upgrade all --noop`, to update information about installed packages.
* When Chocolatey search for local packages, it returns *%ERROLEVEL% == 0* when a package is installed or not. I used *findstr* to validate if such package is installed.
* The original package test expects *git* installed on development machine. By default, is not installed on AppVeyor, so I used *chocolatey* package.
Related issue: #1612 
Saludos.
=> Add support for Chocolatey (#1612)

conans/client/generators/cmake_common.py, conans/test/generators/cmake_test.py
(#1640) Fixes an issue where the CMake generator would fail to escape settings and user_info values, resulting in an invalid CMake file.
The problem was a little wider than expected. Evaluated against the CMake documentation and determined that ", $, and \ all need to be properly escaped when applied. Also, I extended the implementation to the settings values as well, since it is conceivable (though unlikely) that a setting could contain a value requiring escape as well.
=> Fix for issue #1640

conans/test/util/tools_test.py, conans/tools.py
Related issue: #1612 
Fixed Chocolatey package manager on Windows. `NullTool` was reverted as default on Windows,
TODO: Update docs to explain how to create ChocolateyTool instance.
=> Chocolatey as optional on Windows

conans/tools.py
Use os.path.join for path joining in vcvars_command function.
There was a problem when the path in environment variable doesn't finish with '/' at the end.
=> Fix path joining in vcvars_command

conans/client/command.py, conans/tools.py
as you know, Visual Studio has removed VS150COMNTOOLS environment variable, and currently it has to be manually set up in order to use conan.
however, recently MS has added tool called vswhere (https://github.com/Microsoft/vswhere) which can be used to find Visual Studio installation directory.
proposed patch uses vswhere if VS150COMNTOOLS  is not set.
also, it fixes an issue that vcvarsall.bat can change current directory (https://developercommunity.visualstudio.com/content/problem/26780/vsdevcmdbat-changes-the-current-working-directory.html)
=> use vswhere to locate Visual Studio 2017, if available

conans/client/command.py, conans/client/conan_api.py, conans/client/installer.py, conans/client/manager.py, conans/client/packager.py, conans/test/command/package_files_test.py, conans/test/functional/create_package_test.py
It changes behavior a little:
- In conan cache, now ``conaninfo.txt`` in package folder is always generated, not copied from build folder. The generation of ``conaninfo.txt`` and ``conanbuildinfo.txt`` in build folder might be removed, I don't think anyone is using them
Related to https://github.com/conan-io/conan/issues/1548
=> package() working for package_files

conans/server/conf/default_server_conf.py, conans/server/service/authorize.py, conans/test/server/service/authorizer_test.py
Currently, the BasicAuthroizer pattern `*` includes even unauthenticated users. In the spirit of PCRE where `*` can match 0 or more occurrences, but `?` matches 1+ occurrence, this pull request adds the ability to specify wildcard rules that require authentication.
e.g. This config snippet
```default_server_conf:
[read_permissions]
*/*@*/*: ?
```
will require authentication for all recipe and package operations, but any authenticated user is authorized.
=> Add ?:"Any authenticated user" to BasicAuthorizer

conans/client/rest/auth_manager.py, conans/client/userio.py, conans/test/remote/auth_test.py, conans/test/utils/tools.py
- Should solve the problem with expiring tokens reported by @tru 
- Support for multiremote=> multiuser/multipassword
- Same naming used in package tools, interesting feature to improve conan package tools, specifing multiple users/password without complexing the calls to conan user or conan upload -u -p
=> Auth with environment

conans/client/cmake.py, conans/test/util/tools_test.py, conans/tools.py
Add additional argument build_type for **CMake** build helper - build, install and test methods to be able to override **Conan** _build_type_ setting.
When using **CMake** build helper for _Release_ **Conan** setting in recipe sometimes I want to build _RelWithDebInfo_ **CMake** configuration instead of _Release_ configuration. Currently when I have _Release_ in settings and I call `cmake.build()`, **Conan** tries `cmake --build <build_dir> --config Release`. It will be good to be possible to override the default assumptions for _Debug_ when I have _Debug_ **Conan** setting and Release when I have _Release_ **Conan** setting.
Of course I always can call appropriate build command with `self.run` but having direct support for this in **CMake** build helper will be more convenient.
=> Add option to pass different build type in CMake build helper.

conans/client/command.py, conans/model/build_info.py, conans/test/command/build_test.py, conans/test/integration/conan_env_test.py, conans/test/integration/flat_requirements_test.py, conans/test/model/build_info_test.py
Proposed performance boost and fixed tests, for https://github.com/conan-io/conan/pull/1711
=> Filter directories

conans/requirements.txt
Related to #1710, allow pylint versions from 1.6.5 up to 1.8.0 in requirements.txt. Current pylint 1.7.2 works fine and passes all Conan tests.
=> Allow pylint versions 1.6.5 up to 1.8.0

conans/client/conan_api.py, conans/test/conan_api/manifests_arguments_test.py
This PR fixes the issue #1689 
After this changes the variable `default_manifest_folder` does not get used inside conan_api.py. But I guess it still makes sense that it stays there.
=> Change default arguments for manifests related arguments in conan_api.

conans/client/generators/visualstudio.py
visual_studio generator: Add include directories for the MIDL compiler, so that it can find and use `*.idl` files from dependencies. This change assumes that the `*.idl` files will be exported into the same `include` directories as normal headers.
IDL files in Visual Studio are "Interface Definition Language" files, the COM equivalent of `*.h` files.
=> Add include directories for the MIDL compiler

conans/client/tools/files.py
This happened when a zip contained a file with 0 bytes:
```
ERROR: Traceback (most recent call last):
File "/Users/luism/workspace/conan/conans/errors.py", line 24, in conanfile_exception_formatter
yield
File "/Users/luism/workspace/conan/conans/client/source.py", line 94, in config_source_local
conan_file.source()
...
File "/Users/luism/workspace/conan/conans/client/tools/files.py", line 72, in print_progress
txt_msg = "Unzipping %.0f %%" % (the_size * 100.0 / uncomp_size)
ZeroDivisionError: float division by zero
```
=> Fixed unzip with files without contents

conans/client/generators/visualstudio.py
visual_studio generator: Add include directories for the resource compiler, so that it can find and use *.h files that define resource symbols and IDs. This will allow dependencies to use resources from the projects they depend on. (use the same directories as normal header includes)
This change should not break anyone because they will only need it if they are including header files, and if they are doing that, the header files should have unique names.
Related to conan-io #1421.
=> Add include directories for the Resource compiler

conans/client/tools/net.py
`tools.get()` is a handy one-liner, but it doesn't support checking the hash of the downloaded file.  This PR adds optional parameters so you can verify the md5, sha1, or sha256 hash before unzipping and deleting the file.
=> Add optional parameters to tools.get() for hash checking

conans/client/loader_parse.py
https://github.com/conan-io/conan/issues/1782
I debugged the origin issue, and it gets to the ``pyexpat`` builtin import.
It seems that this is closely related to https://bugs.python.org/issue29830, which is the only builtin with submodules. 
Maybe this fix is then too specific for just this very import. The issue might have an easy workaround, just importing locally (inside methods) the offending import.
=> fix loader parse

conans/client/tools/files.py
A few of us felt this error was a bit misleading with the capital L, knowing that linux is case sensitive, some wondered if perhaps this meant it was looking for a `Lib` folder with a capital `L` .  Seeing that is can be passed in as a parameter, it doesn't feel like a good improvement to change the error to have a lower case `l` which would still be confusing if you passed in a non-default folder name.  So, this seemed more robust, although it might make the message too long.  Just a simple suggestion, feel free to reject. Also, did not test.
=> Update error message for copy command files.py

conans/client/tools/files.py, conans/test/util/file_hashes_test.py
This shows the exception like so: 
```
ERROR: msys2_installer/20161025@bincrafters/testing: Error in source() method, line 28
tools.check_sha256(archive_name, checksum)
ConanException: sha256 signature failed for 'msys2-base-x86_64-20161025.tar.xz' file.
Provided signature: 2c198787ea1c4be39ff80466c4d831f8c7f06bd56d6d190bf63ede35292e344c
Computed signature: bb1f1a0b35b3d96bf9c15092da8ce969a84a134f7b08811292fbc9d84d48c65d
```
=> Added "provided" signature to exception message

conans/client/tools/files.py, conans/test/util/which_test.py
**tools.which** has the same effect as posix **which** command, or **shutil.which** from python3
as conan is for python2, it's necessary addition
certain build tools sometimes need full paths, e.g. CMake needs **CMAKE_AR** and **CMAKE_RANLIB** to be absolute paths
=> - add tools.which helper

conans/client/tools/win.py
follow up on #1794 
I suppose it is worth to display a warning message if users have VS150COMNTOOLS environment variable set incorrectly, at least it will help to troubleshooting such kind of problems
=> - display warning if VS150COMNTOOLS is set to invalid path

conans/client/proxy.py, conans/test/integration/install_update_test.py
https://github.com/conan-io/conan/issues/1841
I am concerned about the following scenario (check L120 of the test)
- Recipe is updated from remote
- Source code is updated from remote
- Package binary is not updated, the old one is currently used, if it is not updated from the remote, or forced to build.
Maybe this is to be changed, and always remove all binaries when the recipe has been updated from the remote.
=> fixed sources not being removed with recipe update

conans/client/rest/uploader_downloader.py
The mkdir of the destination dir was failing if the file_path is just a file name, with no dir.
=> Fixing downloader

conans/client/generators/__init__.py, conans/client/generators/visualstudio_multi.py, conans/client/loader_parse.py, conans/client/tools/files.py, conans/client/tools/net.py, conans/test/generators/visual_studio_multi_test.py
follow up on #1674 
adds **visual_studio_multi** generator - same as **visual_studio**, but supports multiple configurations (just like **cmake_multi**)
I have the following script which demonstrates generator usages:
```
call conan install . -g visual_studio_multi -s arch=x86 -s build_type=Debug   -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MDd --build missing --update
call conan install . -g visual_studio_multi -s arch=x86_64 -s build_type=Debug   -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MDd --build missing --update
call conan install . -g visual_studio_multi -s arch=x86 -s build_type=Release   -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MD --build missing --update
call conan install . -g …
```
=> - add visual_studio_multi generator

conans/client/cmake.py
**CMAKE_SYSTEM_NAME** must be Darwin when compiling for iOS (and other systems like watchOS, tvOS)
otherwise, you'll get annoying warning:
```
System is unknown to cmake, create:
Platform/iOS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
```
but there is worse consequence - CMake will not have variables like **UNIX** and **APPLE** defined, so it can produce unexpected results or even fail
=> - CMAKE_SYSTEM_NAME must be Darwin for iOS, watchOS and tvOS

conans/model/options.py, conans/test/model/options_test.py, conans/test/model/transitive_reqs_test.py
follow up #1715 
support specifying options like `-o Boost.*:shared=True`
that shall apply `shared=True` to all boost packages
there is major difference in implementation - if option doesn't exist in one of packages, it is just ignored (regular syntax like `-o Boost.Assert:shared=False` causes command to fail)
it was requested by users, since among various Boost packages, some of them are header-only and have no shared option, while others have it
=> - implement patter matching for options

conans/client/configure_build_environment.py, conans/client/tools/files.py, conans/test/functional/autotools_configure_test.py
Env vars from `AutoToolsBuildEnvironment` will contain only slashes.
Should solve #1281
=> Replace slashes in win

conans/client/generators/xcode.py, conans/test/generators/xcode_gcc_vs_test.py
* Populate GCC_PREPROCESSOR_DEFINITIONS from deps_cpp_info.defines.
* Populate OTHER_CFLAGS from deps_cpp_info.cflags.
* Populate OTHER_CPLUSPLUSFLAGS from deps_cpp_info.cppflags.
=> xcode generator: Fix handling of compiler flags.

conans/client/tools/oss.py, conans/client/tools/system_pm.py
add PacManTool as SystemPackageTool implementation for Arch Linux
also could be used for MSYS2 (but I don't know how to detect MSYS2 environment ATM, and not sure if it is a sane default)
=> - add PacManTool for pacman (Arch Linux)

conans/client/command.py, conans/client/conan_api.py, conans/client/manager.py, conans/test/command/user_test.py
Hi!
This PR is about the issue #1929.
I accepted the suggestion of @memsharded, using `-i/--interactive` to request the password when run the command `conan user`.
Some more details about the feature:
If I only pass `-i` to the command, it will ask for username and password. The remote will be the default.
```
$ conan user -i
Remote 'bintray' username: uilianries
Please enter a password for "uilianries" account:
Change 'bintray' user from None (anonymous) to uilianries
```
When I pass `username` or `remote`, the argument passed by me will be used as preferred.
```
$ conan user -i -r local baz
Please enter a password for "baz" account:
Change 'local' user from None (anonymous) to baz
```
When both `password` and `interactive` are present, an error will be raised. It doesn't make sense, ask …
=> Ask for password when run user command (#1929)

conans/client/tools/win.py
in certain cases, users compile for non-MSVC but still need Visual Studio command prompt.
one of such examples, is using **Clang on Windows** - although compiler is Clang, it still needs Visual Studio standard library headers, Windows SDK headers, libraries and certain tools, such as resource compiler, manifest tool, sign tool, etc.
_I think the same story applies to the Intel compiler._
so given that fact, vcvars_command is not something just for MSVC compiler, but the entire infrastructure for Windows development.
therefore, to use vcvars_command, we still need to pass Visual Studio version, instead of compiler version of compiler we're currently building for (that can be different entities in case of Clang or ICC).
there is valid workaround for this - declaring custom settings object …
=> - allow to override compiler_version in vcvars_command

conans/model/options.py, conans/test/model/options_test.py
Comes from: https://github.com/conan-io/conan/issues/1975
doing ``some_option in self.options`` to check if some option is existing in the current options, hangs and finally crashes python interpreter (recursive calls)
=> adding support for checking existing option with in

conans/client/client_cache.py, conans/util/locks.py
Should help with: https://github.com/conan-io/conan/issues/2010
It is almost impossible to add such messages to the SimpleLock over specific binaries, as it doesn't have an active wait. Collisions and hangs on SimpleLock should be less frequent anyway, these messages might be enough.
=> added messages to concurrent locks

conans/client/rest/uploader_downloader.py, conans/test/util/tools_test.py
https://github.com/conan-io/conan/issues/2000
Where did the "a=append" come from? Is it enough to just open the file in write mode, or is there some case we actually want to append?
=> fixing appending while download overwrite

conans/client/build/cmake.py, conans/client/conf/__init__.py, conans/client/tools/win.py, conans/test/functional/cmake_test.py, conans/test/functional/compile_helpers_test.py, conans/test/model/other_settings_test.py, conans/test/model/transitive_reqs_test.py, conans/test/util/build_sln_command_test.py, conans/test/util/vcvars_arch_test.py, conans/test/util/vcvars_store_test.py
follow up on #1155 and #1584 
also addresses #1262 
adds basic support for WindowsStore OS:
- WindowsStore 8.1 = WinRT
- WindowsStore 10.0 = UWP
this doesn't add support for Windows Phone, Windows Mobile or Windows CE - it will come as separate PRs later.
=> support WindowsStore OS

conans/requirements.txt
distro 1.1.0 is out and already packaged for eg. Arch Linux.
=> python-distro 1.1.0 is out

conans/__init__.py, conans/client/generators/ycm.py, conans/model/conan_generator.py, conans/paths.py, conans/test/generators/generator_filter_error_test.py
Address: https://github.com/conan-io/conan/pull/2074
The access to ``build_info`` from generators is pointless, even potentially dangerous:
- When the package is in the local cache, ``package_info()`` has not been called yet while building (but build() uses generators), so the info is empty
- Not only is empty, but as the directories are non-existing and the results are cached, it breaks dependencies info if ``include_paths`` is checked
- If the package is in user folder, ``package_info()`` is not called at all. That was removed a few versions ago. So right now, the information of ycm for local installs is always empty for the current package. Then, this PR is not breaking anything, it was already not working.
I think it is much safer with this fix. The only missing functionality (that …
=> removing build_info from generators

conans/client/cmd/new_ci.py, conans/test/command/new_test.py
#2167 
I've reviewed the docs, nothing concrete to update, in #433 I updated a detail about package_tools that can be already merged to master.
=> gcc majors and clang deprecated in travis

conans/client/tools/oss.py, conans/client/tools/system_pm.py, conans/test/util/tools_test.py
This adds the commands to support the zypper package management
tool as used in the opensuse and Suse Linux Enterprise Server
distributions within SystemPackageTool
p.s. apologies for multiple pull requests, my usual workflow is patches & emails, I am not very good with github!
=> Add support for Suse's zypper in SystemPackageTool

conans/client/cmd/new.py
Removed `source_dir` from files generated with `conan new --sources` and `conan new --ci-shared`
PR to docs: https://github.com/conan-io/docs/pull/434
=> Removed source_dir from conan new command

conans/requirements.txt
Solves #2164, avoids pylint false warnings on Python 3.
=> require fresh pylint and astroid

pyinstaller.py
#2207 
To be ready to use `pyinstaller` in Windows and for x64 is necessary to install pyinstaller from pip and fix some prints and file stuff.
Not needed
=> Pyinstaller ready

conans/client/client_cache.py, conans/client/remover.py, conans/test/command/export_test.py, conans/test/command/info_test.py, conans/util/locks.py
Address https://github.com/conan-io/conan/issues/2243
The problem with https://github.com/conan-io/conan/issues/2243 is that when the code does:
```python
def get_recipe(self, conan_reference):
with self._client_cache.conanfile_write_lock(conan_reference):
result = self._get_recipe(conan_reference)
return result
```
The ``conanfile_write_lock`` creates the lock file (rw.count) inside the conan local cache Pkg/version/user/channel folder. If the ``_get_recipe`` fails because the package doesn't exist, the lock files are still there (they can't be removed, as you don't know about concurrent usage). So the search, that uses the folder existence to detect packages, is giving a false positive
Another possible solution could be to change the **search** and force it to detect an …
=> fixed creation of packages when non-existing

conans/client/manager.py, conans/test/command/export_pkg_test.py
https://github.com/conan-io/conan/issues/2242
=> fix options reuse after install in export-pkg

conans/client/tools/env.py, conans/client/tools/win.py, conans/test/util/tools_test.py
PR in docs, reviewed by Diego: https://github.com/conan-io/docs/pull/452 
The purpose is to be able to inject more environment variables to the Windows subsystem to control in a more direct way the order of the commands in the path, in concrete with Visual Studio, and avoid the need of a visual studio wrapper. Now the way to prioritize Visual is:
```
vs_path = tools.vcvars_dict(self.settings)["PATH"]
tools.run_in_windows_bash(command, env={"PATH": vs_path})
``` 
https://github.com/conan-io/docs/pull/452
=> vsvars filtering path, run in bash accepting env vars

conans/client/deps_builder.py, conans/test/integration/alias_test.py
Address: https://github.com/conan-io/conan/issues/2252
The issue is due to the conflict detection in the dependency graph calculation when there are diamonds. If there is an alias:
- Pkg/latest => Pkg/0.1
And a diamond:
- LibA => Pkg/latest
- LibB => Pkg/latest
- Consumer => LibA, LibB
The first time the graph is expanded, via LibA, we get Consumer->LibA->Pkg/0.1 (alias substitution).
The second branch checks LibB->Pkg/latest and raises a conflict. As conflicts are raised before actually fetching the dependency by the algorithm, the easiest way to fix it seems to store the resolved aliased references, to check them.
=> fix for alias diamond conflict

conans/client/build_requires.py, conans/test/integration/same_userchannel_test.py
https://github.com/conan-io/conan/issues/2254
If ``build_requirements()`` use ``self.user`` and ``self.channel``, it is failing even if the env vars CONAN_USERNAME are defined in the environment, because the environment is not being correctly applied to build_requirements().
=> fixed build_requirements() env

conans/client/generators/cmake_common.py
Fix for #2285 - the generated conanbuildinfo.cmake is now aware of the VS LLVM toolset and handles the compiler selection logic accordingly. Unrecognized toolsets are assumed to use Visual Studio.
=> (Fixes #2285) Generated conanbuildinfo.cmake now correctly selects expected compiler when using LLVM with Visual Studio

conans/client/generators/cmake_common.py
https://github.com/conan-io/conan/issues/2310
The check for compiler in ``conanbuildinfo.cmake`` only covers CLang/LLVM as accepted toolsets, so it is raising for Intel.
I have searched for some sensible defaults for Intel toolsets to add to ``settings.yml`` but no clear reference so far, and if any, there are a lot of versions, not sure which of them to add. As they can be added by users, not a big stopper.
Testing might be difficult, without installing the toolsets. CMake will likely complain if it is not in the system before getting to that poing, and it is very difficult to mock.
=> not throw if intel in cmake

conans/client/tools/win.py
I found this bug trying to build boost using the `with vcvars(self.settings)`. It was not able to locate the vswhere because "where.exe" was removed from the path (System32).
=> Keep system32 and windows paths

conans/client/tools/win.py
When Autotools configure method used a relative path it crashed because of the newly introduced "get_cased_path"
=> Fixed use of cased paths

conans/client/build/autotools_environment.py, conans/test/build_helpers/autotools_configure_test.py
- [X ] I've read the [Contributing guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X ] I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. Also adding a description of the changes in the ``changelog.rst`` file. https://github.com/conan-io/docs
This adds an option to select the target to the autotools make command. This is very useful e.g. to either do an install "make install" or build shared libraries, in the case where the project creates a separate targets (e.g. "make shared")
=> add option for build target to make

conans/client/installer.py, conans/test/integration/build_id_test.py
https://github.com/conan-io/conan/issues/2225
Docs: https://github.com/conan-io/docs/pull/500
I have been reviewing the usage, and it seems there is an easy solution: if the build_id (or ``build_reference`` in code) is the same as the ``package_reference``, then it can be assumed that the ``build_id()`` method did not have any effect, and then the normal behavior could be used
=> not skipping build if build_id() does not affect

conans/test/util/tools_test.py
- [x ] I've followed the PEP8 style guides for Python code.
`conan.conans.test.util.tools_test.ToolsTestTest::system_package_tool_fail_when_not_0_returned_test` was failing in Fedora with:
```
FAIL: system_package_tool_fail_when_not_0_returned_test (conan.conans.test.util.tools_test.ToolsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/pedro/git_projects/conan.io/conan/conans/test/util/tools_test.py", line 127, in system_package_tool_fail_when_not_0_returned_test
spt.update()
AssertionError: "Command 'sudo apt-get update' failed" does not match "Command 'sudo yum check-update' failed"
```
Now it should be ok for supported Linux distribution.
=> Fixed test for Linux distros

conans/client/build/cmake.py, conans/test/build_helpers/cmake_test.py
Fix https://github.com/conan-io/conan/issues/2370
CONAN_CMAKE_GENERATOR can define the generator, and in that case checking for some settings that will not be used to define the generator seems unnecessary. I have swapped the order.
=> changed order of CONAN_CMAKE_GENERATOR to not need settings

conans/client/generators/scons.py, conans/test/generators/scons_test.py
For some packages, it is useful to know the package version so that .so or .dll files can be located and installed.
In quotes to avoid python syntax errors with versions like 4.2.2
=> Add package versions to generated scons file

conans/client/tools/win.py
vswhere detection is failing because of non-ascii characters in vswhere output
=> fix encode-errors in vswhere output

conans/client/command.py
See more details about valid return codes:
- https://stackoverflow.com/questions/6466711/what-is-the-return-value-of-os-system-in-python
fixes #2360 
Manual test in Mac os X:
```bash
10:21 $ conan create . pedro/test
Hello/0.1@pedro/test: Exporting package recipe
^CYou pressed Ctrl+C!
ERROR: Exiting with code: 3
10:21 $ echo $?
3
```
And Linux:
```bash
conan@0588fa293512:~/test$ conan create . pedro/test
Hello/0.1@pedro/test: Exporting package recipe
^CYou pressed Ctrl+C!
ERROR: Exiting with code: 3
conan@0588fa293512:~/test$ echo $?
3
conan@0588fa293512:~/test$ uname -a
Linux 0588fa293512 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
See more about return codes:
- https://stackoverflow.com/questions/6466711/what-is-the-return-value-of-os-system …
=> Not 0 exit code when handling signals.

conans/client/conf/config_installer.py, conans/test/command/config_install_test.py
fixes #2324 
Only implemented the functionality to remove credentials in a generic way using urlparse which works with any kind of path. Not implemented verbose or not verbose as @markgalpin suggested in #2324 because now output displays url without credentials, see functional tests and trace below.
Added unit tests and functional tests.
Maybe function to remove credential should be moved to another module, now it's living in config_installer.
Also manual tests downloading from server with conan and checked that url is still stored with credentials in ``conan.conf``. See trace:
```
conan@1543e9c55635:~$ conan config install https://xxxx:xxxx@bitbucket.org/pvicente/test1/raw/c5f38af3544ed35e574a4d16b7720fc158decd29/conan.zip
Trying to download …
```
=> Don't display credentials from url while conan config install

conans/client/loader.py, conans/client/loader_parse.py, conans/model/conan_file.py, conans/test/command/source_test.py, conans/test/functional/conanfile_loader_test.py
This PR will add build_requires support for the conanfile.txt loader. This can be usefull in f.e. conan-cmake project [#67](https://github.com/conan-io/cmake-conan/issues/67).
Greetings  
Tonka
=> Add build_requires support for conanfile.txt loader

conans/client/importer.py, conans/client/loader_parse.py, conans/test/functional/conanfile_loader_test.py, conans/test/functional/imports_tests.py
Added `keep_path` parameter to `self.copy()` inside `imports()` for *conanfile.py*:
```
def imports(self):
self.copy("*license*", dst="licenses", keep_path=True)
```
and in `[imports]` for *conanfile.txt*:
```
[imports]:
., *license* -> ./licenses @ keep_path=True
```
Still missing docs!
=> Added keep_path parameter to copy in imports()

conans/client/tools/pkg_config.py, conans/test/util/pkg_config_test.py
- change PkgConfig helper to raise ConanException
=> - change PkgConfig helper to fail as early as possible

conans/client/loader.py, conans/test/built_type_setting_test.py
This test shows the current behavior:
- ``build_type`` in a recipe won't fail if not defined, as ``None`` is a valid value
- ``build_type`` in a test_package will fail if not defined. Because it is recovered from install state, and ``build_type`` wont exist there
- It works with ``build_type=None``, that doesn't fail
Closes https://github.com/conan-io/conan/issues/2500
=> build_type not defined not error

conans/client/cmd/test.py, conans/client/command.py, conans/client/conan_api.py, conans/client/conf/__init__.py, conans/test/command/create_test.py, conans/test/command/test_package_test.py
Additionally, by default a temp folder is used as build directory and
a new command line option can be used to specify a folder if needed.
=> Delete build folder after successful conan test (#2160)

conans/client/conf/detect.py, conans/test/util/detect_test.py
closes #2231 
Previously failing compiler detection in mac os x when gcc was forced:
```bash
09:28 $ CC=gcc CXX=g++ conan install boost/1.66.0@conan/stable
Auto detecting your dev setup to initialize the default profile (/Users/pvicente/.conan/profiles/default)
CC and CXX: gcc, g++
Found gcc 4.2
Default settings
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=4.2
compiler.libcxx=libstdc++
build_type=Release
*** You can change them in /Users/pvicente/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***
ERROR: Invalid setting '4.2' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '7', …
```
=> 2231 conan compiler detection

.ci/jenkins/runner.py
Author name in the commit is breaking the build, clearing the env var before the tests should work.
The contributor should update from develop and push again to try it.
https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-2549/1/pipeline/
=> Clean env var user for testing

conans/client/generators/ycm.py, conans/test/generators/generators_test.py
Expose the conan dependencies in a separate json files. The consumer now
have to copy the .ycm_extra_config.py once and link the
conan_ycm_flags.json file to its build directory.
https://github.com/conan-io/conan/issues/2466
=> Generate conan json dependencies for Ycm generator

conans/client/cmd/export_linter.py
Close #2523
I have been checking extensively pyinstaller and pylint, and couldn't figure out a way to make the python modules dynamically available for pylint running from the pyinstaller app (the python modules are simply not there). So at least disable the linter with an information message.
=> disabling pylint for pyinstaller

conans/client/cmd/export_linter.py, conans/model/conan_file.py, conans/test/command/export_linter_test.py
=> Fixed copy_deps linter warning when exporting

conans/client/build/autotools_environment.py, conans/client/tools/oss.py, conans/test/build_helpers/autotools_configure_test.py, conans/test/utils/conanfile.py
Refactored triplets:
- Support conan running in ARM devices and adjusting correctly the triplets. Closes #2603
- Refactor of triplets flags, same code to calculate the `host` triplet and the `build` triplet.
Not docs required.
=> Refactor triplets GNU autotools

conans/client/manager.py, conans/test/command/download_test.py
From investigating https://github.com/conan-io/conan/issues/2616 and @fsturm feedback
It happens that ``conan download`` is lazy regarding the sources. While the default lazy behavior is fine for install, I think that the correct behavior for download is to fetch them directly. This PR implements this.
=> make conan download directly retrieve the sources

conans/client/rest/auth_manager.py
As stated in #2668:
> I think we jumped the gun here. I did some tests and now CONAN_DISABLE_LOGIN_PROMPT has to be set to True for this to work. This is not what is stated in the documentation.
> 
> I propose we switch to `get_env()` from `conans.util.env_reader` so setting it to 1 will also work and updating the documentation. I'll go do some pull requests.
>
=> Fix disable login prompt environment variable.

conans/model/build_info.py, conans/test/generators/cmake_test.py
Improvement for behavior described in: https://github.com/conan-io/conan/issues/2739
TO BE CHECKED for possible breaking behavior.
=> do not add default paths to sub-configs

conans/client/command.py, conans/client/conan_api.py, conans/test/command/config_test.py, conans/test/command/search_test.py
This PR only changes help messages and arguments position in the display help.
The only important changes are in the following positional arguments:
- Those receiving a path or reference are now called: `path_or_reference`
- Those receiving user/channel or reference are now called: `scope_or_reference` <- I can see some controversy here 🤣 How would you call the "user/channel" item?
- Those receiving pattern or reference are now called: `pattern_or_reference`
Update to docs missing until approval ☑️
=> review commands help arguments

conans/client/conan_api.py
Issue: #2782 
Change how CONAN_COLOR_DISPLAY is handled and add special handling when PYCHARM detected.
- The terminal used for run config inside of PYCHARM requires special settings for colored output.
- Allowing requiring color output with ``CONAN_COLOR_DISPLAY=1`` environment variable
- If ``CONAN_COLOR_DISPLAY`` is not set rely on tty detection for colored output
[docs PR](https://github.com/conan-io/docs/pull/635)
=> Allowing requiring color output with ``CONAN_COLOR_DISPLAY=1``

conans/client/loader.py, conans/model/options.py, conans/test/remove_subsetting_test.py
Close #2781
The local flow was not recovering the correct state. It was done for settings, but not for options.
=> fixed options initialization in local flow

conans/client/conf/detect.py
=> - conan profile new --detect for MSYS

conans/model/env_info.py, conans/test/integration/conan_env_test.py
Instead of fixing the casing on the propagation, the path is always added uppercased now to the env object.
=> PATH always uppercase in self.env_info

conans/client/runner.py, conans/client/tools/win.py, conans/model/conan_file.py, conans/test/util/tools_test.py
Close #2839
As explained in the issue, it is tricky. This solutions uses the ``output=False`` trick to force calling Popen instead of ``os.system()``. This was possible because ``self.run(win_bash=True)`` is totally ignoring ``output`` argument, which probably should be fixed at some point.
=> fixed bash path with spaces issue

conans/client/client_cache.py, conans/client/conan_api.py, conans/client/manager.py, conans/client/manifest_manager.py, conans/client/proxy.py, conans/client/remover.py, conans/paths.py, conans/test/command/export_path_test.py, conans/test/command/export_test.py, conans/test/command/remove_test.py, conans/test/command/upload_complete_test.py, conans/test/integration/install_update_test.py, conans/test/integration/manifest_validation_test.py, conans/test/integration/syncronize_test.py, conans/test/integration/version_ranges_diamond_test.py
More refactors (all refactors, functionality shouldnt change):
- Simplified ``ConanRemover`` it didn't need the proxy anymore
- Continued the FiletreeManifest load/save simplifications
- Removed the ugly named ``digestfile_xxxx`` methods
=> refactor for remove and manifests

conans/client/installer.py, conans/client/manager.py, conans/client/packager.py, conans/test/functional/create_package_test.py, conans/test/functional/short_paths_test.py, conans/util/windows.py
When short_paths=True in a conanfile.py, the message displayed after package is created says "`Package '1' created`" instead of package ID due to the name of the short paths directory. This PR solves that
=> Fix "Package '1' created" message with short_paths=True

conans/client/build/msbuild.py, conans/test/build_helpers/msbuild_test.py
Would be nice to confirm if it helps, but anyway should be better this way, without generating the XML nodes if no value has to be specified.
=> MSBuild runtime when no runtime setting

conans/client/client_cache.py, conans/client/graph/build_requires.py, conans/client/graph/graph.py, conans/client/graph/graph_builder.py, conans/client/graph/printer.py, conans/client/installer.py, conans/client/manager.py, conans/client/manifest_manager.py, conans/client/printer.py, conans/client/proxy.py, conans/client/remote_manager.py, conans/test/model/transitive_reqs_test.py, conans/test/model/version_ranges_test.py
Yet another refactor to prepare 1.5:
- Manifests management is done at the end of the install process
- print_graph extracted
- Remote defined in the Node
- Minor renames and style
=> refactor manifest

conans/client/tools/__init__.py, conans/client/tools/apple.py, conans/test/util/apple_test.py
add various tools I am using for apple development
I was using them for my private recipes and keep copy-pasting between packages
now I am compiling bincrafters packages for iOS, and need them as well
so I've decided it is beneficial to have tools in conan codebase
Closes #2322
=> - add tools for Apple development

conans/client/generators/visualstudio.py
conanbuildinfo.props file which is generated for Visual Studio by conan often has got paths that looks like 'C:/Users/username/.conan/.......'. We'd like to add conanbuildinfo.props file to our VCS but it always changes on every computer, because everyone has got another username and it's annoying. Not having a file in directory causes that Visual Studio project cannot be opened without running 'conan install' before. 
Visual Studio has macro for this path and this commit changes these paths from 'C:/Users/username/.conan/'... to '$(USERPROFILE)/.conan/...' which is more universal.
=> Using Visual Studio macro for userprofile path

conans/client/tools/win.py, conans/test/util/tools_test.py, conans/test/util/vcvars_arch_test.py
Add `vcvars_ver` and `winsdk_version` arguments to `tools.vcvars_command`. This make it possible to set all possible arguments for `vcvarsall.bat`. It will be set when the `compiler.version > 14`.
The new arguments are named like in the Syntax help, but `vcvar_ver` f.e. could also be named `vc_version` or something like that.
```bat
:usage
echo Syntax:
echo     %~nx0 [arch] [platform_type] [winsdk_version] [-vcvars_ver=vc_version]
echo where : 
echo     [arch]: x86 ^| amd64 ^| x86_amd64 ^| x86_arm ^| x86_arm64 ^| amd64_x86 ^| amd64_arm ^| amd64_arm64
echo     [platform_type]: {empty} ^| store ^| uwp 
echo     [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.   
echo     [vc_version] : {none} for default VS 2017 VC++ compiler toolset ^| …
```
=> Add vcvars_ver and winsdk_version to tools.vcvars_command

conans/__init__.py, conans/client/build/cppstd_flags.py, conans/client/cmd/export.py, conans/client/conf/__init__.py, conans/client/file_copier.py, conans/client/generators/cmake_find_package.py, conans/client/migrations.py, conans/client/tools/win.py, conans/test/functional/file_copier_test.py, conans/test/functional/scm_test.py, conans/test/integration/cppstd_test.py, conans/test/util/unix_path_test.py
- Fixed `cmake_find_package` generator, that wrongly used `deps.defines` (containing the -D) instead of `deps.compile_definitions`.
- Bad message
=> NOT MERGE: Release 1.4.1

conans/client/generators/cmake_multi.py, conans/model/build_info.py, conans/test/generators/cmake_test.py
Fix #2981
It is a revert of #2740, plus fixing the duplicated paths issue in ``cmake_multi`` generator
=> restored default paths in multi-config cpp_info

conans/model/settings.py, conans/test/model/other_settings_test.py
Fix #3022
I think that once we have to check the type to improve the error message, it can be already converted, so it works without error.
=> fix settings constraint

conans/client/cmd/export.py, conans/test/functional/scm_test.py
Fix #3109
I think it is better to warn, but allow it, just in case someone has some use case with some git repo in a network unit instead of https.
=> allow scm filesystem origin, with warning and replace backslash

conans/client/conf/__init__.py, conans/client/conf/detect.py, conans/test/build_helpers/cpp_std_flags_test.py
Have not added tests for the detection issue but it is a simple regex
=> Fixes detection of apple-clang 10.0 and adds new version to settings

conans/client/rest/conan_requester.py, conans/test/functional/proxies_conf_test.py
If any proxy configuration is specified in the conan conf, conan cleans from the environment the vars related to the proxy management.
**Warn**: It could be breaking if anyone is mixing both global env vars and conan conf vars. But in the otherhand if you have (probably imposed by your environment) proxy env vars you need a way to get rid of them using the conan.conf
=> Removed env when proxy specified

conans/util/files.py
Fix issue when we doesn't have access to write and try to reraise no active exception, causes runtime error without any info.
=> Fix runtime error on exception reraise

conans/client/rest/conan_requester.py
Docs: https://github.com/conan-io/docs/pull/700
This PR generates a user agent string that outputs the Conan client version and the Python version.  This will allow us to track data for client version uptake, and data needed for assessing python version deprecation.  Example: Conan/1.5.0 (Python 2.7.1)
I have not implemented tests yet.  I did do manual tests to confirm it achieves the desired result against Bintray, and when requesting a source tarball from places like source forge.
=> Provide a user-agent header for Conan (#3390)

conans/client/build/msbuild.py, conans/client/tools/win.py
Are tests needed for this? vcvars_command with this params is already tested here:
https://github.com/conan-io/conan/blob/develop/conans/test/util/vcvars_arch_test.py#L73#L103
=> winsdk_version and vcvars_ver in MSBuild()

conans/client/remote_manager.py, conans/search/search.py, conans/test/command/remove_test.py, conans/test/command/search_test.py
Fix #3108
- It also changes the ``conan search -q`` behavior, to be exactly the same
- It introduces the ``-q os=None`` using ``None`` explictly to match
=> fix search and remove query

conans/client/graph/graph_builder.py, conans/client/graph/range_resolver.py, conans/test/command/install_test.py
Fix #3207
The error output now is:
```bash
> ERROR: Failed requirement 'Hello/0.1@lasote/stable' from 'PROJECT'
> ERROR: Unable to find 'Hello/0.1@lasote/stable' in remotes"
```
=> adding failing requirer

conans/test/util/tools_test.py, conans/test/utils/tools.py
Fixes random ``OSError: [Errno 48] Address already in use`` for bottle
=> Use random range for bottle ports in StoppableThreadBottle

conans/requirements.txt
Installation fails with Python 3.7 and PyYAML 3.12 due to yaml/pyyaml#126.
Fixes #3249.
=> Bump version for PyYAML to 3.13

conans/__init__.py, conans/client/cmd/copy.py, conans/client/cmd/uploader.py, conans/client/conan_api.py, conans/client/graph/graph_binaries.py, conans/client/graph/graph_builder.py, conans/client/graph/proxy.py, conans/client/printer.py, conans/client/recorder/action_recorder.py, conans/client/recorder/search_recorder.py, conans/client/remote_manager.py, conans/client/remote_registry.py, conans/client/remover.py, conans/client/rest/auth_manager.py, conans/client/rest/rest_client.py, conans/client/rest/rest_client_common.py, conans/client/rest/rest_client_v1.py, conans/client/rest/rest_client_v2.py, conans/client/rest/uploader_downloader.py, conans/client/source.py, conans/test/functional/registry_test.py, conans/test/model/transitive_reqs_test.py, conans/test/model/version_ranges_test.py, conans/test/remote/auth_bearer_test.py, conans/test/remote/rest_api_test.py
- ConanFileReferences from conan_api (that can receive str or reference) to rest_client.
- Renamed remote manager method `get_ref`
- Prepared rest client to implement V2
- Refactor in "client api" (remote_manager, auth_manager, proxy) to implement "get_recipe" and "get_package" (instead of get_recipe_urls and get_package_urls etc) being the rest_client the one filtering the files. This is to get prepare to V2 where the files are downloaded directly without requesting URLs.
- Solved a couple of bugs detected in `uploader_downloader.py`
=> Prepare for revisions

conans/client/tools/pkg_config.py
add `--print-errors` flag to pkg-config executions. this allows to get more descriptive error messages, and helps to better understand build failures on CI or from user's logs.
=> - add print_errors option to PkgConfig helper

conans/client/cmd/create.py, conans/client/cmd/download.py, conans/client/cmd/search.py, conans/client/cmd/test.py, conans/client/cmd/uploader.py, conans/client/cmd/user.py, conans/client/command.py, conans/client/conan_api.py, conans/client/conan_command_output.py, conans/client/graph/proxy.py, conans/client/installer.py, conans/client/manifest_manager.py, conans/client/printer.py, conans/client/recorder/action_recorder.py, conans/client/recorder/search_recorder.py, conans/client/remote_manager.py, conans/client/remote_registry.py, conans/client/remover.py, conans/client/rest/auth_manager.py, conans/test/command/search_test.py, conans/test/functional/action_recorder_test.py, conans/test/functional/registry_test.py, conans/util/tracer.py
Pure refactor of variable names. `remote` is a `Remote` object (almost only managed by the remote manager and the graph), and `remote_name` is a`str`.
=> Refactor remote=>remote_name

conans/client/command.py
Some help messages miss important information that is only in the docs.
Adding it in the helps gives more exposure to that information.
=> Clarify some help messages

conans/client/command.py, conans/client/conan_command_output.py, conans/client/printer.py
Few minor changes:
* The help message for --outdated has been updated to reflect the fact
that it requires a reference.
* Using --outdated without a reference will raise a ConanException.
* The message that appears when a user searches with the --outdated
option has been updated.
=> [#3250] Better user feedback when using --outdated for searching and deleting

conans/client/generators/qmake.py, conans/test/generators/generators_test.py
Fix #3351
Actually, the same issue could happen with ``cmake`` and other generators. Should I fix them all? Wait until it is reported?
Update: CMake generator is not affected by dots/hyphens in package names.
=> fix qmake with hyphen

conans/client/rest/rest_client_common.py, conans/client/rest/rest_client_v1.py
Removed dead code. Local packages can't ever have deleted files compared with a remote one.
=> "_remove_package_files" removed

conans/client/tools/oss.py
The newest versions of opensuse now report their distro.id() as "opensuse-leap", which breaks conan's detection of zypper. This patch fixes it for opensuse leap, opensuse tumbleweed and SLES
=> fix detection of zypper package tool on latest versions of opensuse

conans/client/tools/scm.py, conans/model/scm.py, conans/test/util/tools_test.py
Submodules are revisioned just like anything else, initialize them
after the right commit has been checked out to HEAD.
fixes #3332
=> Initialize submodules after checking out revision.

conans/client/graph/graph_builder.py, conans/client/graph/range_resolver.py, conans/test/model/version_ranges_test.py
Fix #3268
This might fix the issue, but also optimize even further for most users using version ranges. 
The solution proposed cached the results of the search query to the remote, which is the expensive one, not the results for certain range, as it might be more generic.
=> optimizing version ranges remote calls

conans/client/cmd/uploader.py, conans/client/command.py, conans/client/conan_api.py, conans/test/command/upload_test.py
You can now use the --query flag in the `conan upload` command like you
would in `conan remove`. In other words, you can use a query to specify
which packages will be uploaded to the server.
Will update documentation tonight.
=> Implemented --query flag in `conan upload` (#2445)

conans/client/loader.py, conans/model/options.py, conans/test/integration/options_test.py
The real issue was this line in `configure()`:
```
self.options["*"].shared = self.options.shared
```
And user input with something like ``conan install -o *:shared=True``.
Basically, options with ``*`` operator are reserved for the graph builder to be applied to requirements when graph is complete. The option with ``*`` is not applied initially to the consumer conanfile and when it hits the line above in configure, changes the general scope option to its default value (``shared=False``).
=> Apply general scope options to consumer Conanfile first

conans/client/tools/win.py, conans/test/util/tools_test.py
In addition to #3159, `vcvars_dict` also returns as a list for the vars `("INCLUDE", "LIB", "LIBPATH", "PATH")`. 
This way, it plays nicely with the `environment_append`. As now, by default, only the new elements in these lists are returned, the old values are naturally appended to the environment in the `environment_append` so no breaking behavior has introduced. 
NOTE: Only if someone was supposing that `ret["LIB"]` is a string would be affected, but I think it is not common to call directly to `vcvars_dict` and accesing directly to the return.
=> vcvars better diff and var list management

conans/client/command.py
=> Fix --build-order option name in `conan info` help

conans/client/generators/__init__.py, conans/test/util/files_test.py, conans/util/files.py
Add parameter `only_if_modified` to the utility function `save` to skip actual writing to disk if nothing has changed. 
Implement this functionality in generators generated files.
=> Do not modify generators files if nothing has changed (close #2895)

conans/client/graph/graph_manager.py, conans/client/manager.py, conans/test/command/export_pkg_test.py
Fix #3432
With the new graph computation, the ``export-pkg`` command was computing the whole graph, including the binaries availability. It was asking the server if it had binaries for the current exported package binary. While it worked (besides the issue of trying to connect the server), it was unnecessary, better remove it.
=> export-pkg shouldn't touch server

conans/client/command.py
The short description should be on alone on a line. Otherwise the next
sentence is displayed too and usually truncated, puzzling the reader.
Fixes #3425 .
=> Fix 'conan help' formatting

conans/client/installer.py, conans/test/integration/install_missing_dep_test.py
Current (1.7) ouput is:
```
Exporting package recipe
foo/1.0.0@issue/test: A new conanfile.py version was exported
foo/1.0.0@issue/test: Folder: /Users/jgsogo/.conan/data/foo/1.0.0/issue/test/export
carrot/1.0.0@issue/test requirement potato/1.0.0@issue/test overridden by foo/1.0.0@issue/test to potato/2.0.0@issue/test 
foo/1.0.0@issue/test: WARN: Forced build from source
foo/1.0.0@issue/test: Installing package
Requirements
carrot/1.0.0@issue/test from local cache - Cache
foo/1.0.0@issue/test from local cache - Cache
potato/2.0.0@issue/test from local cache - Cache
Packages
carrot/1.0.0@issue/test:88d205e84502b10878a230ecd0d4aeb5f0c15d5e - Missing
foo/1.0.0@issue/test:bb034b7230b58e9c8c59372b69d68b06c5ffff5e - Build
potato/2.0.0@issue/test:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache …
```
=> Add dependencies to package output info when binary is not found (close #3316)

conans/test/utils/tools.py
Improve output when TestClient raises an exception in order to know what is happening in CI:
```bash
> nosetests conans.test.integration.install_missing_dep_test
E
======================================================================
ERROR: missing_dep_test (conans.test.integration.install_missing_dep_test.InstallMissingDependency)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\Javi\dev\conan\conans\test\integration\install_missing_dep_test.py", line 24, in missing_dep_test
client.run("createe . dep1/1.0@lasote/testing")
File "C:\Javi\dev\conan\conans\test\utils\tools.py", line 513, in run
raise Exception(exc_message)
Exception:
------------------------------- Command failed: --------------------------------
createe . …
```
=> TestClient: wrap command and output from command in fancy lines

conans/client/tools/win.py
- Only close registry key if it has been opened.
- If `winreg.OpenKey` fails it raises an `OSError` ([py3](https://docs.python.org/3/library/winreg.html#winreg.OpenKey)) or `WindowsError` ([py2](https://docs.python.org/2/library/_winreg.html#_winreg.OpenKey)).
=> [fix] Handle winreg.OpenKey exception

conans/test/util/tools_test.py
Fails when there is no `windows_subsytem`
=> [fix] Issues related to OSInfo.bash_path()

conans/__init__.py, conans/client/rest/rest_client_v1.py, conans/test/remote/broken_download_test.py
- Closes #3483
- Spotted playing with Jenkins and a bad nginx configuration that produced a download to a non valid host causing an error but because of a `None` output object accesing `.error`.
=> Fix bug detected with downloader output

conans/client/cmd/export.py, conans/client/tools/scm.py, conans/model/scm.py, conans/test/functional/scm_test.py, conans/test/util/tools_test.py
=> Add get_repo_root to SCM, use it for path stored in scm_folder.txt (close #3465)

conans/client/tools/scm.py, conans/test/util/tools_test.py
The `Git` `get_branch` method has to return the branch name, the responsibility of adapting it to be used as a version is not from the `Git` class. @niosHD The test has been updated to reflect how it can be used now.
=> Fixed Git class, wrongly replacing characters from the branch name

conans/client/tools/win.py, conans/test/util/unix_path_test.py
Fix/improve implementation of `get_cased_path`: if you call it with a non-existing path, it will work only on the existing part of the path and leave the rest as is.
=> [fix] get_cased_path doesn't raise when path does not exists

conans/client/installer.py
While working on the CI reproducibility, graph locks, etc, I found very slow graph propagation. This PR will highly alleviate it.
Measured, for a linear graph (A->B->C-> .... ->) of 250 nodes, the propagation (computed by ConanInstaller), reduces from 30 to 3 seconds.
=> reduce propagate complexity from O(n2) to O(n)

conans/client/tools/system_pm.py, conans/test/util/tools_test.py
Following last comments  by @lasote [here](https://github.com/conan-io/conan/issues/3385#issuecomment-417239791) this pr implements the `add_repository` functionality for SystemPackageTool (only available for AptTool).
=> Implement add_repository for SystemPackageTool (only AptTool) (close #3385)

conans/client/remote_manager.py
during file compression, a new dot is displayed every 60 seconds
it avoids CI builds to be considered stalled
=> add processing indicator during files compression

conans/client/rest/uploader_downloader.py, conans/test/functional/download_retries_test.py
Currently, with APIv2 it is retrying the download when a file doesn't exist. It should retry only if there is another kind of error.
=> Don't retry when NotFoundException

conans/client/graph/graph.py, conans/client/graph/graph_builder.py, conans/client/graph/graph_manager.py, conans/client/installer.py, conans/client/loader.py, conans/client/tools/win.py, conans/model/conan_file.py, conans/test/model/conanfile_test.py, conans/test/util/tools_test.py
=> conanfile reserved attrs and methods

conans/__init__.py, conans/server/rest/controllers/v2/conan_controller.py
- There was a bug in the v2 of the server released in the 1.7.3
The bug only shows up within a client speaking v2 (1.8.0).
- Removed v2 capability from server until v2 is mature to not causing backward compatibilities with modern clients speaking with old servers
=> [CI ONLY] Fixed bug using v2

conans/util/windows.py
it's just much more convenient to use `C:\.conan\2xez1sh5\1` instead of `C:/.conan\2xez1sh5\1`, such paths can be easily copied and opened everywhere on Windows
=> - use forward slashes for short paths

conans/client/tools/oss.py, conans/test/util/detected_architecture_test.py
related to the https://github.com/bincrafters/community/issues/443
properly detects ppc64le architecture and few others
based on python's `platform.machine()`, which actually uses `uname` under the hood
tested on PowerPC VM
see also
1. https://stackoverflow.com/questions/45125516/possible-values-for-uname-m
2. https://en.wikipedia.org/wiki/Uname
3. https://github.com/gcc-mirror/gcc/blob/master/config.guess
=> - fix PowerPC architecture detection

conans/client/command.py, conans/errors.py, conans/test/command/invalid_configuration_test.py
The aim of this PR is to implement a ConanInvalidConfiguration exception that the user can raise from the `configure()` function in ConanFile to tell consumers of the recipe that a given set of settings (and options?) is known to fail (and it is ok).
This exception should be propagated across Conan code up to the command caller, letting the caller know about this specific _error_ and handle it. It will be very useful for tools like `conan-package-tools`.
Feedback is needed from experienced frogarians 🐸 as other use cases may be affected:
- anything related to workspaces?
- anything related to APIs?
- somewhere in the graph model?
Let's talk about this
=> Add ConanInvalidConfiguration exception and handle error codes.

conans/client/build/autotools_environment.py, conans/client/tools/oss.py, conans/test/build_helpers/autotools_configure_test.py, conans/test/util/tools_test.py
=> Not muted exception and added new archs for triplet detection

conans/client/tools/files.py, conans/test/util/tools_test.py
=> Use self.cpp_info.libdirs as folders for tools.collect_libs()

conans/client/graph/python_requires.py, conans/test/integration/python_build_test.py
Could close #3619
Changelog: BugFix: Fixes ``python_requires`` overwritten when using more than one of them in a recipe
=> fixing multiple python requires collission

conans/client/conf/detect.py, conans/client/tools/win.py, conans/test/util/vcvars_clangcl_test.py
related to the:
#1839 
https://github.com/conan-community/community/issues/43
Changelog: Feature: Allow ``vcvars`` to run if ``clang-cl`` compiler is detected.
=> - allow vcvars for clang-cl

conans/client/tools/win.py, conans/test/util/tools_test.py
To clarify, there was no bug in Conan. **vcvars** prepends new variables to the PATH, but without looking if the entries in the path are or not already set with the same value there. With some recipes manipulating the environment, sometimes the max chars for PATHS is reached. So with this PR, the `vcvars_dict` will remove repeated entries in the PATH.
Changelog: Feature: Clean repeated entries in the ``PATH`` when ``vcvars`` is run, mitigating the max size of the env var issues.
=> Clean repeated entries in PATH after vcvars call

conans/client/build/cmake_flags.py, conans/test/build_helpers/cmake_test.py
Changelog: Feature:  Added definition ``CMAKE_OSX_DEPLOYMENT_TARGET`` to the ``CMake`` build helper following the ``os.version`` setting for ``Macos``.
=> Add cmake flag 'CMAKE_OSX_DEPLOYMENT_TARGET' according to settings.os.version

conans/client/rest/conan_requester.py, conans/client/rest/rest_client_common.py, conans/test/functional/conan_trace_file_test.py, conans/util/tracer.py
Close #3612
Changelog: Bugfix: All API calls are now logged into the ``CONAN_TRACE_FILE`` log file.
=> Fix trace all api calls

conans/requirements_dev.txt
After running some test from a clean python environment I realized bottle was not installed.
Changelog: Fix: Included ``bottle`` package in the development requirements
=> Add bottle as dev requirement

conans/client/installer.py, conans/test/integration/system_reqs_test.py
Changelog: Fix: Apply ``system_requirements()`` always on install, in case the folder was removed.
Close #3616
Close #2262
=> system_requirements checked always on installer

conans/client/output.py, conans/client/remote_manager.py, conans/requirements.txt, conans/util/executor_helper.py, conans/util/progress_bar.py
I've tried to introduce it in the less invasive way possible.
Example output doing a `conan install boost/1.68.0@conan/stable`:
Changelog: Feature: Progress bars for files unzipping.
=> Unzip progress bars

conans/client/conf/__init__.py, conans/test/functional/default_profile_test.py
Changelog: Feature: The environment variable CONAN_DEFAULT_PROFILE_PATH allows the user to define the path (existing) to the default profile that will be used by Conan.
=> allow relative paths (from conan.conf) in env variable

conans/client/conf/detect.py, conans/client/tools/win.py, conans/test/util/vcvars_clangcl_test.py
Removes output param in `latest_visual_studio_version_installed()`
@SSE4 we realized after merge that there is no need to force users to set the ``output`` parameter in this function
=> Removed output parameter from latest visual public function

conans/test/integration/cmake_targets_test.py
Closes #3394, to demonstrate how a `package_info()` should look when packaging an Apple framework.
- Docs modified here:
https://github.com/conan-io/docs/pull/839/files
=> Added test of how to package an Apple Framework

README.rst, conans/client/command.py, conans/client/conf/config_installer.py, conans/test/command/config_install_test.py
Changelog: Feature: Allow `conan config install` to install configuration from a folder and not only from compressed files.
Fixes #3670
=> Install config from folder

conans/client/cmd/uploader.py, conans/client/remote_manager.py, conans/client/rest/auth_manager.py, conans/client/rest/rest_client.py, conans/client/rest/rest_client_v1.py, conans/client/rest/uploader_downloader.py, conans/test/remote/rest_api_test.py
Close #3550
To be checked and discussed.
Changelog: Fix: Avoid downloading the manifest of the recipe twice for uploads. Making this download quiet, without output.
=> fixed duplicated download of manifest and manifest download output

conans/model/options.py, conans/test/model/options_test.py
Changelog: Fix: ``None`` option value was not being propagated upstream in the dependency graph
=> Fix: propagation of options with value None upstream

.ci/jenkins/Jenkinsfile, conans/client/rest/rest_client.py
Changelog: Disabled apiv2 until the new protocol become stable.
Only allow the client to speak v2 when we are ready.
=> Disable v2 for 1.8 release

conans/client/cmd/export_linter.py, conans/client/graph/python_requires.py, conans/pylint_plugin.py, conans/test/command/export_linter_test.py
Changelog: Fix: Remove warnings related to python_requires(), both in linter and due to Python2.
Close #3704
=> remove warnings related to python_requires

conans/client/tools/files.py, conans/model/conan_file.py, conans/test/util/tools_test.py
Changelog: Fix: Fix misleading warning message in ``tools.collect_libs()``
=> Fix misleading warning message in tools.collect_libs()

conans/client/tools/system_pm.py, conans/test/util/tools_test.py
Changelog: (Bugfix):  `yum update` needs user's confirmation, which breaks system update in Centos non-interactive terminal.
=> yum update without confirmation.

conans/client/runner.py, conans/client/tools/system_pm.py, conans/test/util/tools_test.py
Changelog: Fix: Add ``--askpass`` argument to ``sudo`` if it is not an interactive terminal
I'm supposing that everywhere ``sudo`` is used, the argument ``--askpassp`` is available. I hope this statement to be true 🤞
=> Add --askpass argument to 'sudo' if it is not an interactive terminal

conans/model/conan_file.py, conans/test/integration/same_userchannel_test.py
Changelog: Feature: New attributes `default_user` and `default_channel` that can be declared in a conanfile to specify the `user` and `channel` for conan local methods when neither `CONAN_USERNAME` and `CONAN_CHANNEL` environment variables exist.
=> Enable "unhack" user and channel

conans/requirements.txt
Changelog: Fix: Upgrade dependency of tqdm to >=4.27: solves issue with weakref assertion.
* Unlocks tqdm==4.20.0 that was fixed here: https://github.com/conan-io/conan/pull/3545#issuecomment-421068377
* Could avoid issues like #3728 because now we have an open dependency and it won't fail if the installed one satisfies our requirement.
=> Up tqdm to 4.27: fix weakref warning

conans/client/installer.py, conans/client/recorder/action_recorder.py, conans/test/command/json_output_test.py
Changelog: Feature: Add cpp_info data to json output of ``install`` and``create`` commands at package level.
Output looks like this:
```json
{
"error": false,
"installed": [
{
"recipe": {
"id": "zlib/1.2.11@conan/stable",
"name": "zlib",
"version": "1.2.11",
"user": "conan",
"channel": "stable",
"downloaded": false,
"cache": true,
"error": null,
"remote": null,
"time": "2018-10-10T10:28:28.351753",
"dependency": true
},
"packages": [
{
"id": "0eaf3bfbc94fb6d2c8f230d052d75c6c1a57a4ce",
"downloaded": false,
"cache": true,
"error": null,
"remote": null,
"time": "2018-10-10T10:28:28.356103",
"built": false,
"cpp_info": {
"includedirs": [
"include"
],
"libdirs": [
"lib"
],
"resdirs": [
"res"
],
"bindirs": [
"bin"
],
"builddirs": [
""
],
"libs": [
"z"
],
"rootpath": …
```
=> Show cpp_info in output from install and create commands

conans/client/conan_api.py, conans/client/packager.py, conans/test/command/export_pkg_test.py
Changelog: Fix: Allow providing ``--profile`` argument (and settings, options, env, too) to ``conan export-pkg``, so it is able to correctly compute the binary package_id in case the information captured in the installed conaninfo.txt in previous ``conan install`` does not contain all information to reconstruct the graph.
Close #3367
Docs in https://github.com/conan-io/docs/pull/898
There is no information enough in conaninfo.txt to recover all cases, and compute the whole dependency graph, which is necessary for correctly computing the package_id of the binary being exported. So this PR allows to specify the profile (or settings, options, env) that define the binary, instead of trying to recover it from the installed conaninfo.txt
=> using profile or settings in export-pkg allowed

conans/client/tools/scm.py, conans/test/util/tools_test.py, conans/test/utils/tools.py
Changelog: Fix: Use XML output to retrieve information from SVN command line if its client version is less than 1.8 (command ``--show-item`` is not available).
Changelog: Fix: SVN v1.7 does not have ``-r`` argument in ``svn status``, so functionality ``SVN::is_pristine`` won't be available. 
Here it is a PR to handle interface changes (detected up to now) between SVN 1.7.x and newer versions:
It should work for the use-cases reported up to now, but new issues will raise and we are not running CI tests with old SVN versions so we may break something in the future 😰
=> Handle old versions (<1.8) of SVN

conans/client/generators/__init__.py, conans/client/generators/premake.py, conans/paths.py, conans/test/generators/premake_test.py
closes #3693 
uses premake generator from https://github.com/memsharded/conan-premake
Changelog: Feature: New `premake` generator incorporated to the Conan code base from the external generator at https://github.com/memsharded/conan-premake.
=> Feature: Premake generator

conans/client/command.py
See #3700
Changelog: fixes typo in `conan new`
=> Fix a typo in "CircleCI"

conans/client/graph/graph_binaries.py, conans/client/installer.py
Changelog: Fix: Implement download concurrency checks, to allow simultaneous download of the same package (as header-only) while installing different configurations that depend on that package.
Fix https://github.com/conan-io/conan/issues/2219
To discuss: tests, other concurrency cases.
=> implement download concurrency checks

conans/client/build/cmake.py, conans/test/build_helpers/cmake_test.py
follow up on https://github.com/conan-io/conan/pull/2803
when using `ninja_installer/1.8.2@bincrafters/stable`, right now the following code is required:
```
if self.settings.compiler == 'Visual Studio':
with tools.vcvars(self.settings, force=True, filter_known_paths=False):
self.build_cmake()
else:
self.build_cmake()
```
I tried to simplify it in our `zmq/4.2.2@bincrafters/stable` recipe, but it currently fails, because there are places in `CMake` helper which use `self._conanfile.run` directly instead of `self._run`:
https://github.com/conan-io/conan/blob/1.8.3/conans/client/build/cmake.py#L183
https://github.com/conan-io/conan/blob/1.8.3/conans/client/build/cmake.py#L185
Changelog: (Feature | Fix | Bugfix): Describe here your pull request
=> Fix: use self._run instead of self._conanfile.run to ensure vcvars apply for Ninja/NMake generators

conans/client/loader.py
Changelog: Fix: Internal improvements of the ConanFile loader
Instead of load the conanfile using the file path as the module name, use directly the uuid.
Warning: This change makes sense for me but I feel like it could be other reasons for the previous code.
=> Fix loader

conans/client/remover.py, conans/test/command/remote_test.py
Changelog: Fix: The registry won't remove a reference to a remote removed recipe or package.
=> Don't touch registry when deleted from a remote

conans/client/cmd/new.py, conans/client/conan_api.py, conans/client/graph/grapher.py, conans/client/printer.py, conans/model/conan_file.py, conans/test/command/info_test.py, conans/test/command/inspect_test.py, conans/test/command/new_test.py
Changelog: Feature
This PR is related to #3671 
Also, I added `author` as default attribute when running `conan new`
Docs PR: https://github.com/conan-io/docs/pull/875
=> #3671 Add attribute tags

conans/util/locks.py
Changelog: Fix: Handling corrupted lock files in cache
Fix #3815
=> Check for UnicodeEncodeError when reading .count-file

conans/client/tools/oss.py, conans/test/util/tools_test.py
Changelog: Fix: Add ``neon`` as linux distro for SystemPackageTools
=> Add neon as linux distro for SystemPackageTools

conans/test/integration/alias_test.py
Test was failing due to a warning introduced here: https://github.com/conan-io/conan/blame/79146da40b349b3f6edff922762725d22fcf21e3/conans/util/locks.py#L64
=> Fix develop tests

conans/client/installer.py, conans/test/integration/build_id_test.py
Changelog: Fix: Implement dirty checks in the cache build folder, so failed builds are not packaged when there is a ``build_id()`` method.
Fix #2879
=> failed builds dirty checks

conans/client/build/cmake.py, conans/test/build_helpers/cmake_test.py
follow up on #3803 
clang-cl also requires vcvars to be set, otherwise CMake generation fails (it will fail to find `rc.exe`)
Changelog: (Feature | Fix | Bugfix): Describe here your pull request
=> Fix: call vcvars for clang-cl as well

conans/client/cmd/export.py, conans/client/source.py, conans/test/functional/scm_test.py, conans/test/utils/tools.py
This reverts commit d07097fa8bc715d8d24fee01797df4d34dd15e67.
After discussion with the team we think changing permissions is something too risky and our vision of the problematic is still not clear.
=> Revert "Test and fix for read only files from `svn:needs-lock`attribute"

conans/client/build/msbuild.py, conans/client/build/visual_environment.py, conans/test/build_helpers/msbuild_test.py, conans/test/util/build_sln_command_test.py
Changelog:  Fix: The `MSBuild()` build helper doesn't adjust the compiler flags for the build_type anymore because they are adjusted by the project itself.
Closes #3548
Docs here: https://github.com/conan-io/docs/pull/914/files
=> Excluded build type flags for MSBuild()

conans/__init__.py, conans/client/rest/rest_client_v1.py, conans/test/integration/install_update_test.py, conans/test/remote/broken_download_test.py
Changelog: Fix: Hidden confusing messages `download conaninfo.txt` when requesting the server to check package manifests.
Closes #3707
=> Hide conaninfo download for manifest checks

conans/client/migrations.py, conans/test/test_migrations.py
Fix plugins->hooks migration with an already existing hooks folder
=> Test plugins->hooks migration with an already hooks folder

conans/test/command/download_test.py, conans/test/command/search_test.py, conans/test/command/user_test.py, conans/test/integration/install_update_test.py, conans/test/integration/test_build_info_extraction.py, conans/test/integration/version_ranges_diamond_test.py, conans/test/remote_checks_test.py, conans/test/utils/tools.py
Only tests changes to guarantee that the servers are ordered and we do not introduce bugs because of that.
=> Servers with order guaranteed in testing

.travis.yml
Travis CI: fix conditional builds on release and master; add Python 3.7 Xenial to the matrix.
=> Travis CI fixes

conans/client/cmd/download.py, conans/client/conan_api.py, conans/client/store/localdb.py, conans/client/userio.py, conans/test/integration/install_selected_packages_test.py
Changelog: Fix: ``conan download`` of packages that require auth to read them has been fixed.
Removing search in download command, it doesn't work properly when remote packages read is not anonymous, as Artifactory search is returning nothing found, so the credentials are not requested at all.
Also, as suggested by @puetzk, doing a ``vacuum`` of the DB when cleaning, to ensure info is totally removed.
=> remove search from download call

conans/client/graph/grapher.py, conans/test/command/info_test.py, conans/test/command/inspect_test.py
Changelog: Fix: ``topics`` attribute in conanfile breaking info graph html generation
=> Fix topics breaking info graph html

conans/client/tools/win.py, conans/test/util/vcvars_arch_test.py
Changelog: Fix: Fix regression introduced in 1.7, setting ``amd64_x86`` when no ``arch_build`` is defined.
Close #3917 
To pass CI, maybe a specific test that covers it is needed.
=> vcvars regression

conans/client/tools/scm.py
Changelog: Bugfix: SVN API changes are relevant since version 1.9
=> SVN api changes happended in version 1.9

conans/client/build/compiler_flags.py, conans/test/generators/compiler_args_test.py
Changelog: Bugfix: compiler_args generated "mytool.lib.lib" for Visual Studio libraries that were defined with the ``.lib`` extension in the ``self.cpp_info.libs`` field of ``package_info()``.
=> fix compiler args

conans/client/generators/qbs.py
Changelog: (Feature | Fix | Bugfix): Describe here your pull request
- qbs generator unites sharedlinkflags and exelinkflags as `...framework OpenGL""-framework Cocoa...`
- fix separates these flags by `,`
=> Fixed linker flags

conans/util/files.py
Changelog:  Bugfix: A `conan install` with a reference failed when running in the operating system root folder because python tried to create the directory even when nothing is going to be written.
Closes #4002 
The real issue happen if you try to run `os.makedirs("c:")` python will fail with a different error than `EEXIST`, note that the directory `c:\` of course, exists, and we are able to write it even! But we cannot create it.
=> mkdir fails when the directory exists

conans/client/generators/__init__.py, conans/client/generators/make.py, conans/client/generators/premake.py, conans/paths.py, conans/test/generators/make_test.py
Changelog: Feature: Added new ``make`` generator.
=> Adds Make generator

conans/client/tools/win.py
Changelog: Bugfix: Running Windows subsystem scripts crashed when the PATH environment variable passed as a list.
Spotted in preflight develop.
=> Subsystems PATH as a list failing

conans/client/tools/net.py, conans/test/util/tools_test.py
Changelog: Fix: The `tools.get` tool (download + unzip) now supports all the arguments of the `download` tool. e.g: `verify`, `retry`,  `retry_wait` etc.
Closes #4028
Docs at:  https://github.com/conan-io/docs/pull/961
=> Propagate all download args to get

conans/requirements.txt
Changelog: Fix: Updated Colorama to allow 0.4.0 in pip requirements
=> Updated Colorama to allow 0.4.0 in pip requirements

conans/client/build/meson.py, conans/test/build_helpers/meson_test.py
Changelog:  Feature
Add missing methods to Meson helper (compared to CMake one). Fix #3935
- add `meson.test()` which execute a `ninja test`
- add `meson.install()` which execute a `ninja install`
- `meson.options` attribute equivalent to `cmake.definitions`
- set by default `meson.options["prefix"]` to `conanfile.package_folder`
- set accordingly to package's options `fPIC` and `shared` Meson's options `b_staticpic` and `default-library`
- set `cpp_std` accordingly to `conanfile.settings.cppstd`
- add a static method `get_version()` to get Meson version
- fix unit tests to take into account the new parameters
=> Meson build helper: add test() and install() methods

conans/client/cmd/export.py, conans/client/source.py, conans/client/tools/scm.py, conans/model/scm.py
Changelog: Fix: Using the `scm` feature when Conan is not able to read the gitignored files (local optimization mechanism) print a warning to improve the debug information but not crash.  
Closes #4027
=> Print warning but ignore gitignored files optimization

conans/search/search.py, conans/test/command/search_test.py
Changelog: Bugfix: Take into account ``os_build`` and ``arch_build`` for search queries.
Accoding to issue https://github.com/conan-io/conan/issues/4060 os_build and arch_build are not handled as options. This tries to fix it, but maybe further things are needed?
Close #4060
=> Assuming os_build and arch_build as settings

conans/client/conan_api.py, conans/client/graph/graph_builder.py, conans/client/graph/graph_manager.py, conans/client/graph/range_resolver.py, conans/test/integration/version_ranges_diamond_test.py, conans/test/model/version_ranges_test.py, conans/test/unittests/client/graph/test_range_resolver.py
Changelog: Feature: Display the version-ranges resolutions in a cleaner way.
Need it for graph-lock
=> range resolver don't output directly

.ci/jenkins/conf.py, .ci/jenkins/runner.py
Try to specify a known folder for MSBuild to put the crash logs. Currently, I can't find them where they are supposed to be.
=> MSBuild crash logs

conans/client/tools/net.py, conans/test/client/tools/net_test.py
Changelog: Bugfix: In ftp_download function there is extra call to ftp.login() with empty args. This causes ftp lib to login again with empty credentials and throwing exception because authentication is required by server.
It's a small fix so I did not create any issue about it.
=> Fixes ftp download when authentication is required

conans/client/conf/__init__.py, conans/test/command/config_test.py
Changelog: Fix: Recent updates in python break ConfigParser with % in values, like in path names containing % (jenkins)
Close #4110
=> fixing config parser escape % in py3

conans/test/integration/diamond_test.py, conans/test/utils/tools.py
Try to avoid random CI failures: 
```
msbuild : error msb4166: child node exited prematurely. shutting down.
```
They only appear in CI jenkins, couldn't reproduce locally.
Couldn't reproduce in Jenkins Windows slave, even with 5 concurrent test suites in parallel.
=> limit cpu_count=1 for diamond test

conans/client/conf/config_installer.py, conans/test/functional/command/config_install_test.py, conans/test/unittests/client/conf/config_installer_test.py
Changelog: Feature: Store verify_ssl argument in `conan config install`
=>  Store verify_ssl argument in config install

conans/client/conan_api.py, conans/test/functional/command/config_install_test.py, conans/test/utils/tools.py
Changelog: BugFix: Fix `conan config install` requester for zip file download
Docs: omit
=>  Fix config install requester for download

conans/test/utils/tools.py
Docs: omit
The nightly CI testsuite was failing because of this util using a port already in use: https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanNightly/detail/ConanNightly/349/pipeline/
I have changed the class to use a random less likely in use port number
=> Less likely already in use ports for StoppableThreadBottle

conans/client/generators/b2.py, conans/test/unittests/client/generators/b2_test.py
Using settings.get_safe more actively. Conversion of Nones to strings.
Fixes #4201
Changelog: Bugfix: b2 generator was failing when package recipe didn't use compiler setting
Docs: omit
=> cautious treatment of compiler in b2 generator

conans/client/cmd/export.py, conans/client/tools/scm.py, conans/model/scm.py, conans/test/functional/scm/test_url_auto.py, conans/test/unittests/client/tools/scm/test_git.py, conans/test/unittests/client/tools/scm/test_scm_base.py, conans/test/unittests/client/tools/scm/test_svn.py
Changelog: Fix: Credentials are removed from SCM `url` attribute if Conan is automatically resolving it. 
Docs: https://github.com/conan-io/docs/pull/996
=> Remove credentials from 'url' for SCM replacement

.ci/jenkins/Jenkinsfile
Docs: omit
Try to solve the random errors running the rest API test:
Hypothesis: When a different Linux slave runs the rest API the checkout is not there.
```
+ python .ci/jenkins/runner.py conans.test.functional.remote.rest_api_test py36 /home/jenkins_ci/workspace/ConanTestSuite_PR-4172 /tmp/761f
python: can't open file '.ci/jenkins/runner.py': [Errno 2] No such file or directory
script returned exit code 2
```
=> CI Fixes: rest api failures

conans/client/build/cmake_flags.py
Changelog: Fix how cmake flags are appended
Docs: omit
The description of the add_cmake_flags function does not correspond to the actual behavior.
=> Fix add_cmake_flag in cmake helper

conans/conan_server.py, conans/server/launcher.py, conans/server/migrate.py, conans/server/migrations.py, conans/server/server_launcher.py, conans/server/store/server_store.py
Changelog: Bugfix: The migrated data in the server from a version previous to Conan `1.10.0` was not migrated creating the needed indexes. This fixes the migration and creates the index on the fly for fixing broken migrations. Also the server doesn't try to migrate while running but warns the user to run `conan server --migrate` after doing a backup of the data, avoiding issues when running the production servers like gunicorn where the process doesn't accept input from the user.
Docs: omit
Closes #4219
=> Fix migrations

conans/client/client_cache.py, conans/test/functional/conan_api/settings_preprocessor_test.py, conans/test/functional/conan_api/two_conan_creates_test.py
Changelog: Bugfix: When running consecutively Conan python API calls to `create` the default profile object became modified and cached between calls.
Docs: omit
Close #4246
=> Fixed bug with cached default profile

conans/model/ref.py, conans/test/functional/graph/version_ranges_diamond_test.py, conans/test/functional/old/paths_test.py, conans/test/unittests/model/ref_test.py, conans/test/unittests/model/version_ranges_test.py
Changelog: Bugfix: Fix version ranges containing spaces and not separated by commas.
Docs: Omit
Close #4270
I think it doesn't make sense to replace whitespace in the middle of a <ref>. That should be an error, not "magically" fixed.
=> fixing version ranges with spaces

conans/model/editable_cpp_info.py
=> Import configparser from six for Python2 compatiblity

conans/client/build/cmake.py, conans/test/unittests/client/build/cmake_test.py
closes #3511 
Changelog: Feature: define environment variables for CTest
Docs: https://github.com/conan-io/docs/pull/1018
/cc @cjdb
=> Feature: define environment variables for CTest

conans/client/rest/uploader_downloader.py
Changelog: Fix: Conan client now always include the `X-Checksum-Sha1` header in the file uploads, not only when checking if the file is already there with a remote supporting checksum deploy (Artifactory)
Docs: omit
Closes #3544
=> Added sha1 header always

conans/test/functional/build_helpers/msbuild_test.py
Docs: omit
Seems all the test affected by MSBuild verbosity level were not run in #4251 due to skipping "slow" tagged ones.
@TAGS: slow
=> Fix develop testsuite: MSBuild verbosity level

conans/client/graph/build_mode.py, conans/client/source.py, conans/test/functional/scm/test_local_modified.py
Changelog: Fix: SCM optimization related to `scm_folder.txt` is taken into account only for packages under development.
Docs: Omit
closes #4218
=> Consider scm_folder.txt only for developing packages

conans/client/tools/env.py, conans/test/unittests/client/tools/test_env.py
closes #4323 
Changelog: Fix: ensure tools.environment_append doesn't raise trying to unset variables
Docs: https://github.com/conan-io/docs/pull/1023
=> Fix: ensure tools.environment_append doesn't raise trying to unset variables

conans/client/tools/scm.py, conans/test/unittests/util/tools_test.py
Changelog: Feature: Added ``get_tag()`` methods to ``tools.Git()`` and ``tools.SVN()`` helpers.
Changelog: Fix: ``get_branch()`` method of ``tools.SVN()`` helper now returns only the branch name, not the tag when present.
Docs: https://github.com/conan-io/docs/pull/1020
=> Add git.get_tag() and svn.get_tag()

conans/client/graph/build_mode.py, conans/client/graph/graph_binaries.py, conans/test/functional/command/build_test.py, conans/test/unittests/client/graph/build_mode_test.py
Related issue #3799 
Changelog: Package reference is now accepted as --build pattern
Docs: https://github.com/conan-io/docs/pull/1017
=> #3799 Accept full reference for --build

conans/server/revision_list.py, conans/server/store/server_store.py
Changelog: Fixed a bug in the migration of the server storage to the revisions layout.
Docs: omit
It failed once in my conan_server. Couldn't reproduce it later. Not sure how to test it.
@revisions: 1
=> Fix bug in server revisions

.github/CONTRIBUTING.md
Changelog: Feature: Updated *CONTRIBUTING.md* with code style
Docs: Omit
/cc @uilianries
=> Feature: Update CONTRIBUTING.md with code style

conans/client/command.py, conans/client/conan_api.py, conans/client/profile_loader.py, conans/test/functional/configuration/profile_test.py
Changelog: Feature: The commands `conan install`, `conan info`, `conan create` and `conan export-pkg` now can receive multiple profile arguments. The applied profile will be the composition of them, prioritizing the latest applied.
Docs: https://github.com/conan-io/docs/pull/1036
Closes #4141
=> Composable profiles

conans/test/functional/generators/cmake_generator_test.py, conans/test/unittests/client/build/cmake_flags.py
I think the best we can do now is exclude the temporary profile from CMake generator tests
closes #4339 
Docs: Omit
/cc @jgsogo 
=> #4339 Remove profile from cmake gen tests

conans/client/conan_api.py, conans/client/graph/python_requires.py, conans/client/loader.py, conans/test/functional/conan_api/two_conan_creates_test.py
Changelog: Bugfix: Caching of several internal loaders broke the conan_api usage
Docs: Omit
This probably means that the api should be reconsidered, to create fresh instances of everything for every call. I will open an engineering issue for this.
Closes #4363
=> fix caching api

conans/client/output.py, conans/test/unittests/client/conan_output_test.py, conans/util/progress_bar.py
Changelog: Fix: Implemented retrial of output to stdout stream when the OS (Windows) is holding it and producing IOError for output
Docs: Omit
Close #4277
=> Fix output stream failures (Windows)

conans/client/build/meson.py, conans/test/unittests/client/build/meson_test.py
closes: #4351 
Changelog: BugFix: Meson generator was failing in case of package_folder == None (test_package using Meson)
Docs: Omit
=> Fix: Meson in case of package_folder == None

conans/client/cmd/export.py, conans/test/functional/hooks/test_post_export.py, conans/util/files.py
Changelog: Fix: `post_export` hooks are called before computing the digest
closes #4425 
After computing (and storing) the digest for all the exported files of a package, it doesn't make sense to call any hook that could potentially change those sources. This PR modifies this behavior so the digest is computed and stored after calling all the `post_export` hooks.
=> Post export function of hooks is called before computing the digest

conans/client/hook_manager.py
Docs: omit
If we don't use named arguments here, we are forcing the hooks to have `output` as the first one.
=> Use named arguments when calling to hook functions

conans/model/graph_info.py, conans/test/functional/command/info_test.py
Changelog: Bugfix: GraphInfo parsing of existing graph_info.json files raises KeyError over "root".
Docs: omit
Close #4443
Close #4447
=> fixing regression of graph_info not having root

conans/client/file_copier.py, conans/client/packager.py, conans/test/functional/command/create_test.py, conans/test/functional/command/export_pkg_test.py, conans/test/functional/command/package_test.py, conans/test/functional/conanfile/imports_tests.py, conans/test/functional/old/conan_trace_file_test.py, conans/test/integration/complete_test.py
Hi!
Do not display the warning "No files copied from build folder!" when actually there are files in the package folder. I've changed past tests to accept the new behavior, now some tests contain a file in the package folder, so it should not show any warning.
Add new test using cmake install instead of self.copy, the same scenario represented on issue #4438
Changelog: Fix: Do not display the warning when there are files in the package folder (#4438).
Docs: Omit
fixes #4438 
=> Fix warning message for package folder (#4438)

conans/client/build/msbuild.py, conans/test/unittests/client/build/msbuild_test.py
Changelog: Bugfix: Regression in ``MSBuild`` helper, incorrectly ignoring the ``conan_build.props`` file because of using a relative path instead of absolute one.
Docs: omit
Close #4472
Close #4471
=> fixed abs-path in conanbuild.props

conans/client/build/meson.py, conans/test/unittests/client/build/meson_test.py
Meson's documentation currently mentions default-library option,
but it is a typo, the proper option is default_library
Changelog: Bugfix: meson build type actually reflects recipe shared option
Docs: omit
=> fix meson build_type

conans/client/build/meson.py, conans/test/unittests/client/build/meson_test.py
Reverts conan-io/conan#4489, changes should go through `develop`. My fault 😓
=> Revert "fix meson build_type"

conans/client/build/meson.py, conans/test/unittests/client/build/meson_test.py
Replicates @ericLemanissier PR #4489, I merged it to `master` (reverted in #4503). 
> Meson's documentation currently mentions default-library option,
but it is a typo, the proper option is default_library
Changelog: Bugfix: meson build type actually reflects recipe shared option
Docs: omit
=> fix meson build_type (#4489)

conans/client/graph/graph_manager.py, conans/test/functional/build_requires/profile_build_requires_test.py
Docs: Omit
This doesn't change behavior, just make it more explicit that actually the build requires defined in profiles do not recurse overthemselves (that would produce an infinite recursion)
@tags: slow
=> profile defined build requires do not recurse

conans/client/build/cmake.py, conans/client/build/cmake_flags.py, conans/test/functional/build_helpers/cmake_flags_test.py, conans/test/functional/generators/cmake_generator_test.py, conans/test/unittests/client/build/cmake_test.py
Changelog: Fix: Revert default cmake generator on Windows (#4265)
Docs: https://github.com/conan-io/docs/pull/1072
Related comment: https://github.com/conan-io/docs/pull/1026#issuecomment-462334623
Since this change is related to CMake, all platforms should be tested, including slow tests
@TAGS: slow
Hi!
As @danimtb commented before, the feature #4265 solved a problem on Windows, but now it causes a new problem when mingw is not installed. This PR reverts the previous change and show an warning message when a generator is not detected.
<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how …
=> Revert CMake default generator on Windows

conans/client/loader_txt.py, conans/test/functional/conanfile/imports_tests.py
Changelog: Bugfix: Fixed problem with conanfile.txt [imports] sections using the '@' character.
Docs: https://github.com/conan-io/docs/pull/1078
Close #4524
There was a problem with folders using "@" and not extra arguments being specified, it failed because the ``rsplit(, 1)`` was splitting it. Possibilities:
- Use  spaces ``<blank>@<blank>`` to split path<->args. Could break some users if they put ``@folders=True``. But simple, will work without needing a trailing ``@``.
- Force users with ``@`` in their pathnames to define a trailing ``@``, even if empty (implemented solution).
- Do a full fledged parser that regexs over the ``folders=True``, etc. patterns (too complex for the value).
=> fix for using @ in conanfile.txt imports

conans/client/cmd/search.py, conans/test/functional/command/search_test.py
Changelog: Bugfix: Fix search packages function when remote is called `all`
Docs: omit
It looks like users do not name their remotes as `all`...
=> bugfix: Wrong param in function `search_packages`

conans/client/build/msbuild.py, conans/client/generators/virtualbuildenv.py, conans/test/functional/build_helpers/msbuild_test.py
Changelog: Fix: Remove output warnings in MSBuild helper.
Docs: Omit
=> remove output warning in MSBuild

conans/client/tools/oss.py, conans/test/unittests/client/conf/detect/detected_os_test.py, conans/test/unittests/client/tools/os_info/osinfo_test.py
closes: #4540
Docs: Omit
tags: @slow, @svn
=> Fix: ensure tools.OSInfo doesn't raise in MSYS/Cygwin environment

.ci/jenkins/Jenkinsfile
Docs: omit
The diff is very weird, I only added `lock('restApiTestsLock') {` to the stage of the `RestApi` test.
This should lock between Jenkins builds of ConanTestSuite so no concurrent conan servers are launched causing the same port to be in use etc. As the tests are very quick I don't see a real problem locking them.
=> Add lock to rest_api tests

conans/errors.py, conans/server/service/v1/service.py, conans/test/functional/command/conan_get_test.py
Docs: omit
@revisions: 1
This is fixing the tests broken in https://github.com/conan-io/conan/pull/4494: https://github.com/conan-io/conan/pull/4494/commits/9cd4dde30f55bae18a355c4bf30f84e2251d6c89, that do not take into account revisions.
This could be a symptom that conan_server might return in v1 ``RecipeNotFoundException`` when a ``pref`` has a ``pref.ref`` that doesn't exist at all (that is the behavior implemented in v2), instead of the ``PackageNotFoundException`` that is returning. But that has to be discussed and fixed in a different PR, this is to fix develop
=> fix develop

conans/client/cmd/user.py, conans/client/conan_api.py, conans/client/store/localdb.py, conans/test/unittests/util/local_db_test.py
Changelog: Fix: Close the sqlite3 database after each usage
Docs: omit
The objective of this PR is to close the database object after its usage. With this change we should be able to remove the temporal folders created during testing that were failing because `cannot delete XXX, it is being used by another process` (affects to the testsuite in the hooks repository).
I'm not sure if the fine-grained visibility implemented in this PR is too fine-grained, but let's approach this issue taking this PR as the starting point.
closes #4400
=> Close the sqlite3 database after each usage

conans/test/integration/revisions_test.py, conans/test/unittests/client/util/time_test.py, conans/util/dates.py
Docs: omit
The `ISO8601` format is too open, I needed to improve the parsing to support the format used in Artifactory.
@REVISIONS: 1
=> Parsing from Artifactory ISO8601

conans/test/unittests/util/env_reader.py, conans/util/env_reader.py
Changelog: Fix: Return empty list if env variable is an empty string
Docs: omit
closes #4451
=> Return empty list if env variable is empty

conans/client/cache/remote_registry.py, conans/test/functional/command/upload_test.py
Changelog: Fix: Remove package references associated to a remote in *registry.json* when that remote is deleted
Docs: omit
=> Remove package references associated to a remote in *registry.json* when that remote is deleted

conans/model/settings.py, conans/test/unittests/model/settings_test.py
Changelog: Bugfix: Avoid ``str(self.settings.xxx)`` crash when the value is None.
Docs: https://github.com/conan-io/docs/pull/1089
Testing https://github.com/conan-io/conan/issues/4562
=> check SettingsItem return type

conans/tools.py
Docs: omit
Tool `vcvars` requires an output argument.
=> Fix: pass argument 'global_output' to tool

conans/client/tools/oss.py, conans/test/unittests/client/tools/os_info/osinfo_test.py
Changelog: Bugfix: `tool.detect_windows_subsystem` know recognizes WSL correctly.
Docs: omit
related to the #2817
detection based on suggestion from MSFT developer: https://github.com/Microsoft/WSL/issues/844
```
sse4@DESKTOP-E3NFU1V:~$ cat /proc/version
Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014
sse4@DESKTOP-E3NFU1V:~$ cat /proc/sys/kernel/osrelease
4.4.0-43-Microsoft
```
/cc @db4
=> Feature: detect_windows_subsystem recognizes WSL

conans/client/cmd/export.py, conans/test/unittests/client/cmd/ast_replacement_scm_test.py
Changelog: Fix: SCM replacement with comments below it
Docs: omit
closes #4531 
Parser and substitution succeed, but there are two pending tasks (failing tests):
=> Fix SCM replacement with comments below it

conans/model/build_info.py
Changelog: Fix: Deprecate 'cppflags' in favor of 'cxxflags' in class CppInfo
Docs: https://github.com/conan-io/docs/pull/1091
closes #4337
----
In order to remove all the usages of the deprecated member in our codebase, I find one problem: the files written by the generators...
For example, the `conanbuildinfo.txt` file now contains
```ini
[cppflags_Hello]
FLAG
```
and the expected (for Conan v2.0) should be:
```ini
[cxxflags_Hello]
FLAG
```
During the transition, we can output something like the following one, to keep compatibility:
```ini
[cppflags_Hello]
FLAG
[cxxflags_Hello]
FLAG
```
So, our reader should be able to deal with the first option and the last one until Conan V2 (checking that both sections contain the same information). This is easy for the `txt` generator, but it might …
=> Deprecate 'cppflags' in favor of 'cxxflags' in class CppInfo

conans/client/cmd/profile.py, conans/test/functional/command/profile_test.py
This fixes #4589
Changelog: Fix: `conan profile list` will now recursively list profiles.
Docs: omit
I am not sure this warrants a documentation change.
=> Command 'conan profile list' will now list profiles recursively

conans/requirements.txt
Docs: omit
With the new version of Pylint (2.3.0), the JSON output contains escaped characters:
```json
[
{
"type": "convention",
"module": "conanfile",
"obj": "TestConan.build",
"line": 9,
"column": 15,
"path": "conanfile.py",
"symbol": "invalid-name",
"message": "Variable name &quot;v&quot; doesn&#x27;t conform to snake_case naming style",
"message-id": "C0103"
}
]
```
I've opened an issue in their repo (https://github.com/PyCQA/pylint/issues/2769), probably it is a regression so I'm blocking just that version
=> Exclude pylint==2.3.0 (html-escaped chars in json output)

conans/pylint_plugin.py, conans/test/functional/command/export_linter_test.py
Changelog: Fix: `Instance of 'TestConan' has no 'install_folder' member` when exporting recipe
=> Added install_folder to dynamic fields list.

conans/client/conf/__init__.py
Docs: omit
I don't know why finally this PR didn't include the archs in the default settings file:
https://github.com/conan-io/conan/pull/4260/
=> Adding armv5 archs to the settings.yml file

conans/__init__.py, conans/client/conan_api.py, conans/client/rest/rest_client.py, conans/errors.py, conans/test/integration/revisions_test.py, conans/test/utils/tools.py
Docs: omit
Closes #4607
Tested also manually with Artifactory.
@revisions: 1
Team, allow me to introduce here the changelog for the installers and there is no PR to open for that:
Changelog: Feature: The `deb` and `windows` Conan installers now use Python 3.
=> Fail nicely without revisions and only_v2

conans/client/build/cmake_flags.py, conans/client/conf/__init__.py, conans/client/migrations.py, conans/client/tools/win.py, conans/test/unittests/client/build/msbuild_test.py, conans/test/unittests/model/info/vs_toolset_compatible_test.py, conans/test/unittests/util/msvs_toolset_test.py
Changelog: Feature: Conan is ready for the release of Visual Studio 2019 (16). Still not working for the pre-release.
Docs: omit
closes #4146 
closes #2822
- add Visual Studio 2019 (16) to the default `settings.yml`
- allow to detect pre-release Visual Studio versions
- detect Visual Studio 2019 (16) as well
- by default, Visual Studio 2019 uses the same toolset as previous - v141
- no changes to C++ standard (no support for C++20 added as for Preview 1)
- add support for upcoming `Visual Studio 16 2019` CMake generator (https://gitlab.kitware.com/cmake/cmake/merge_requests/2711)
Q: should we modify code at `cmake_common.py` line 353 to handle Visual Studio 2017 and 2019?
=> Feature: initial Visual Studio 2019 (16) support

conans/client/conf/__init__.py, conans/client/graph/graph_binaries.py, conans/model/info.py, conans/test/functional/graph/graph_manager_base.py, conans/test/functional/graph/package_id_modes_test.py, conans/test/integration/build_id_test.py, conans/test/unittests/model/transitive_reqs_test.py
Changelog: Feature: Allow configuring in *conan.conf* a different default ``package_id`` mode. 
Close #4071
=> config of package_id default mode

conans/client/cmd/export.py, conans/client/conan_api.py, conans/client/recorder/action_recorder.py, conans/model/ref.py, conans/test/functional/command/export_pkg_test.py, conans/test/functional/command/json_output_test.py, conans/test/integration/revisions_test.py, conans/test/unittests/client/recorder/action_recorder_test.py
Changelog: Fix: When revisions enabled, add the revision to the json output of the info/install commands.
Docs: omit
Close #4623 
Probably the recorder would need a refactor but this change fixes the issue.
@revisions: 1
=> Add revision to ref in the install json output

conans/client/tools/win.py, conans/model/conan_file.py, conans/test/unittests/util/tools_test.py
Changelog: Feature: Added with_login parameter to tools.run_in_windows_bash()
Docs: https://github.com/conan-io/docs/pull/1103
=>  Added with_login parameter to tools.run_in_windows_bash()

conans/client/hook_manager.py, conans/client/loader.py, conans/test/unittests/client/conanfile_loader_test.py
Changelog: Bugfix: Solve problem with loading recipe python files in Python 3.7 because of ``module.__file__ = None``
Docs: omit
closes #4636
close #4641
=> fixing module.__file__ is None in py3

conans/model/manifest.py
Docs: omit
To be prepared for the future, in case we want to skip the upload of known files and/or the computation in the manifest.
=> Exclude known pattern files from the upload

setup.py
Changelog: Fix: Do not distribute the tests in the python package nor in the installers.
Docs: omit.
Closes https://github.com/conan-io/conan/issues/4563
=> Exclude tests from distribution

conans/client/tools/files.py, conans/test/unittests/util/tools_test.py
Changelog: Feature: Sort library list name when calling tools.collect_libs (#4542)
Docs: https://github.com/conan-io/docs/pull/1124
=> Collect libs uses sorted list (#4542)

conans/client/cmd/export.py, conans/test/unittests/client/cmd/export/test_update_revision_in_metadata.py
Changelog: Fix: Show warning if repo is not pristine and using SCM mode to set the revisions
Docs: omit
closes #4681
=> Show warning if repo is not pristine when using SCM for revision

conans/client/installer.py, conans/client/tools/files.py, conans/test/functional/old/path_limit_test.py, conans/util/windows.py
Changelog:  Bugfix: Raise an error if source files cannot be correctly copied to build folder because of long paths in Windows.
Docs: omit
Close #4484
=> raise error instead of skipping files if short_paths

conans/client/tools/system_pm.py, conans/test/unittests/util/tools_test.py
When CONAN_SYSREQUIRES_SUDO is not specified and sudo is not listed by `tool.which`, SystemPackageTools should not set sudo as prefix.
Changelog: Fix: SystemPackageTools doesn't run sudo when it's not found (#4470)
Docs: https://github.com/conan-io/docs/pull/1127
fixes: #4770
=> #4770 Do not force sudo when it is not found

conans/client/build/meson.py
Docs: omit
Add `output` argument to `vcvars_command` call to avoid warning (and error in CI, [preflight is broken](https://conan-ci.jfrog.info/blue/organizations/jenkins/Preflight_develop/detail/Preflight_develop/143/pipeline))
=> Add output argument to 'vcvars_command' call from Meson helper

conans/client/graph/graph_binaries.py, conans/test/integration/install_outdated_test.py
Changelog: Bugfix: Installing a reference with "update" and "build outdated" options raised an exception.
Docs: omit
@REVISIONS: 1
Close #4789
=> Bug with install update with build mode outdated

conans/client/graph/graph.py, conans/client/graph/graph_builder.py, conans/client/graph/graph_manager.py, conans/model/workspace.py, conans/test/functional/graph/graph_manager_base.py, conans/test/functional/graph/graph_manager_test.py, conans/test/functional/workspace/workspace_test.py, conans/test/utils/conanfile.py
Changelog: Bugfix: Solved bug with build-requires transitive build-requires 
Changelog: Bugfix: Fixed workspace crash when no layout was specified
Changelog: Bugfix: Do not generate multiple ``add_subdirectories()`` for workspaces build-requires
Docs: omit
Close #4752
@tags: slow
=> fix recursive build requires

conans/client/tools/win.py, conans/test/unittests/util/tools_test.py
Changelog: Fix: Look for ``vswhere`` in ``PATH`` when using ``tools.vswhere()``
Docs: omit
=> Look for vswhere in PATH when using tools.vswhere()

conans/client/graph/grapher.py, conans/test/functional/configuration/client_certs_test.py
Docs: omit
If a package has several licenses like [rapidxml](https://github.com/bincrafters/conan-rapidxml/blob/stable/1.13/conanfile.py#L15), graph code fails in the `data.replace`.
```python
class RapiXMLConan(ConanFile):
name = "rapidxml"
version = "1.13"
description = "RapidXml is an attempt to create the fastest XML parser possible"
url = "https://github.com/bincrafters/conan-rapidxml"
homepage = "http://rapidxml.sourceforge.net"
author = "Bincrafters <bincrafters@gmail.com>"
license = ("BSL-1.0", "MIT")
exports = ["LICENSE.md"]
exports_sources = ["CMakeLists.txt"]
source_subfolder = "source_subfolder"
no_copy_source = True
```
=> hotfix: graph fails if a package has several licenses

conans/client/conf/__init__.py, conans/model/requires.py, conans/test/functional/graph/conflict_diamond_test.py
Changelog: Feature: Add config variable `general.error_on_override` and environment variable `CONAN_ERROR_ON_OVERRIDE` (defaulting to `False`) to configure if an overridden requirement should raise an error when overridden from downstream consumers.
Docs: https://github.com/conan-io/docs/pull/1128
closes #4473 
closes https://github.com/conan-io/conan/issues/2800
If a consumer wants to depend on a package (`self.requires("package")`) and declare ALSO that it is overriding a dependency (`self.requires("package", override=True)`) to avoid the _error on override_ exception (implemented here), Conan will raise a `Duplicated requirement error`. That use case is not handled in this PR. <- Issue opened: https://github.com/conan-io/conan/issues/4779
=> Add config variable 'general.error_on_override' (CONAN_ERROR_ON_OVERRIDE)

conans/test/functional/workspace/workspace_test.py, conans/util/templates.py
Changelog: Fix: Allow using ``reference`` object in workspaces in templates for out of source builds
Close #4800
The key is allowing:
```
[build_folder]
../build/{{reference.name}}/{{settings.build_type}}
```
@tags: slow
=> workspaces templates change to allow out-of-source builds

conans/client/cmd/export_pkg.py, conans/test/functional/command/alias_test.py, conans/test/functional/command/upload_test.py
Changelog: Bugfix:  Fix metadata not being updated for ``conan export-pkg`` when using  ``--package-folder``
Docs: omit
=>  Fix metadata not being updated for export-pkg --package-folder

conans/client/source.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Fix: Do not run `export_sources` automatically for python_requires
Docs: omit
Removes the automatic export of the files listed in python_requires::exports_sources. This was an undocumented behavior that was not being executed in the local workflow, and we have thought that it can lead the user to unexpected results.
Implement part of https://github.com/conan-io/conan/pull/4340
=> Do not run 'export_sources' automatically for python_requires

conans/client/cache/cache.py, conans/client/conf/__init__.py, conans/client/rest/conan_requester.py, conans/paths/__init__.py, conans/test/functional/configuration/requester_test.py
Changelog: Feature: Allow the user to configure the path to the CACERT file used in requests
Docs: https://github.com/conan-io/docs/pull/1136
closes #3668 
This PR implements a configuration variable `general.cacert_path` together with the corresponding environment variable `CONAN_CACERT_PATH` to allow the user to set a different path for the CACERT file that will be used in requests:
* If nothing is set, Conan will use the default one: `${CONAN_USER_HOME}/.conan/cacert.pem`. This file will be created if it doesn't exists.
* If some of the configuration variables are set, then **the file must exist** and it will be used for the requests.
=> Add env-var and config-var to explicitly set the cacert_path

conans/client/cache/cache.py, conans/client/cmd/profile.py, conans/client/conf/detect.py, conans/test/functional/command/profile_test.py, conans/test/integration/conf_default_settings_test.py, conans/test/unittests/util/detect_test.py
The warning message will show the correct profile name instead of printing only "default".
Changelog: Fix: Show the correct profile name when detect a new one (#4818)
Docs: Omit
fixes #4818
=> Show profile name when detect a new one (#4818)

conans/client/cmd/export_pkg.py, conans/test/functional/command/export_pkg_test.py, conans/test/functional/generators/cmake_paths_test.py
Changelog: Fix: Apply environment variables from profile and from requirements to ``conan export-pkg``
Docs: omit
Close #4832
@tags: slow
=> apply environment to export-pkg

.ci/jenkins/Jenkinsfile
Docs: omit
Build time in CI goes from 14 mins => 16 mins, but the overall usage should be more efficient, specially in releases when many builds are awaiting until slow Win and MacOS builds, that are most of the times going to fail if the Linux builds failed.
=> CI run linux first

conans/client/cmd/uploader.py, conans/client/remote_manager.py, conans/client/rest/auth_manager.py, conans/client/rest/rest_client_common.py, conans/test/functional/command/install_test.py, conans/test/functional/old/conan_trace_file_test.py
Changelog: Bugfix: Client does not require credentials for anonymous downloads from remotes.
Docs: omit
Close #4871
@tags: slow
cc/ @fschoenm
=> fix credentials necessary for install

conans/client/graph/graph_binaries.py, conans/test/integration/install_update_test.py
Changelog: Fix: More meaningful error message when a remote communication fails to try to download a binary package.
Docs: omit
Closes #2924
=> More meaningfull error when remote failure

conans/client/migrations.py, conans/test/functional/old/test_migrations.py
Changelog: Bugfix: Run a full metadata migration in the cache to avoid old ``null`` revisions in package metadata
Docs: omit
Close #4898
Close #4913
=> new full metadata revision migration

conans/client/command.py, conans/model/workspace.py, conans/test/functional/workspace/workspace_test.py
Changelog: Feature: Default filename for workspaces: `conanws.yml` (used in install command)
Docs: https://github.com/conan-io/docs/pull/1243
closes #4778
=> Default filename for workspaces: conanws.yml (used in install command)

conans/client/command.py, conans/client/printer.py, conans/test/functional/command/inspect_test.py
Changelog: Feature: Add a `--raw` argument to `conan inspect` command to get an output only with the value of the requested attributes
Docs: https://github.com/conan-io/docs/pull/1240
closes #3913
=> Add argument '--raw' to command inspect, more machine friendly

conans/client/command.py, conans/test/functional/command/config_test.py, conans/test/functional/command/profile_test.py, conans/test/functional/command/remote_test.py, conans/test/functional/editable/editable_add_test.py, conans/test/functional/workspace/workspace_test.py
Changelog: Fix. Adding `subparsers.required = True` makes both Py2 and Py3 print an error when no arguments are entered in commands that have subarguments
Docs: omit
Fixes #4816 
Bug in python: https://bugs.python.org/issue9253#msg186387
=> Print an error in both Py2 and Py3 when no params are entered for commands with subarguments

conans/test/functional/command/inspect_test.py
Docs: omit
@PYVERS: Linux@py34
=> Output is dict as string, no order guaranteed, so convert to dict and compare

conans/client/command.py
Docs: omit
Closes https://github.com/conan-io/conan/issues/4829 (although it is more about docs)
I've reorganized/rewritten docs related to `export-pkg`: https://github.com/conan-io/docs/pull/1232
=> Improve export-pkg message, add a notice about provided package-folder

conans/requirements.txt
Docs: omit
@tags: slow
@PYVERS: py27, py36, py34
Comes from https://github.com/conan-io/docs/issues/1244
=> testing updated Pyyaml

conans/client/conan_api.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Bugfix: Fix broken local development flow (``conan source``, ``conan build``, ``conan package``, ``conan export-pkg``) with recipes with ``python-requires``
Docs: omit
@tags: slow
=> fix local flow with python requires

conans/test/unittests/client/build/cmake_test.py
Docs: omit
- [x ] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x ] I've followed the PEP8 style guides for Python code.
As a follow up of the small discussion in #4823 I tested the behavior of conan for WindowsStore (using cmake 1.13.0, Visual Studio 2015 and 2017) for Win64 and ARM and it's correct. Therefore I would like to add two additional tests.
=> [Tests] add test cases for WindowsStore Win64 and ARM

conans/client/generators/cmake_find_package.py, conans/client/generators/cmake_find_package_multi.py, conans/test/functional/generators/cmake_find_package_multi_test.py
Changelog: Bugfix: Bug in `cmake_find_package_multi` caused `CMake` to find incorrect modules in `CMake` modules paths when only `Config` files should be taken into account.
Docs: omit
=> do not find modules for cmake_find_package_multi

conans/client/conf/__init__.py, conans/test/functional/command/config_install_test.py, conans/test/functional/graph/package_id_modes_test.py
- Add default_package_id_mode into default conan.conf
- Add env var CONAN_DEFAULT_PACKAGE_ID_MODE
- Set default value to semver_direct_mode
- Update Functional tests to validate the env var
fixes #4974
Changelog: Fix: Add default_package_id_mode in the default conan.conf (#4947)
Docs: https://github.com/conan-io/docs/pull/1248
=> Add default_package_id_mode in the default conan.conf (#4974)

conans/client/conf/__init__.py, conans/model/manifest.py, conans/test/functional/configuration/skip_broken_symlinks.py, conans/util/files.py
Changelog: Feature: You can disable broken symlinks checks when packaging using `CONAN_SKIP_BROKEN_SYMLINKS_CHECK` env var or `config.skip_broken_symlinks_check=1`
Docs: PENDING!
Closes #4990
=> Skip symlink checks

conans/client/cmd/export.py, conans/client/conan_api.py, conans/test/integration/devflow_test.py
Docs: omit
This should be a pure refactor, no functionality change.
Moving common code into ``cmd_export`` instead of being in *conan_api.py*
=> refactor export for locks

conans/client/cmd/uploader.py, conans/test/functional/command/upload_test.py
Changelog: Bugfix: Solved errors in concurrent uploads of same recipe
Docs: omit
Branched from https://github.com/conan-io/conan/pull/5012, but:
- Delayed _check_recipe_date AFTER compressing the zip, so it is closer to snapshot
- Avoiding loading local manifest twice
- If remote_manifest not there, try to get it in a later attempt
- New test with a patch to simulate exactly the concurrent behavior
@tags: slow
=> concurrent uploads checks and tests

conans/client/graph/graph.py, conans/client/graph/graph_binaries.py, conans/client/graph/graph_builder.py, conans/test/functional/graph/graph_manager_base.py, conans/test/functional/graph/graph_manager_test.py, conans/test/functional/graph/private_deps_test.py, conans/test/utils/conanfile.py
Changelog: Bugfix: Fix skipping binaries because of transitive ``private`` requirements
Docs: omit
@tags: slow
Close: #4970
=> fixing transitive order of privates

conans/client/tools/version.py, conans/test/unittests/client/tools/test_version.py, conans/tools.py
Changelog: Feature: Create `tools.Version` with _limited_ capabilities
Docs: https://github.com/conan-io/docs/pull/1253
* I'm using `loose=True` to allow incomplete versions like `1.2` (no _patch_ component) or "2" (no _minor_ nor _patch_)
closes https://github.com/conan-io/conan/issues/4875
_Note.- Supersedes https://github.com/conan-io/conan/pull/4949_
=> Implement tools.Version (based on SemVer)

conans/client/conf/__init__.py, conans/client/tools/files.py, conans/client/tools/oss.py, conans/test/unittests/model/other_settings_test.py, conans/test/unittests/model/transitive_reqs_test.py, conans/test/unittests/util/tools_test.py
docs: https://github.com/conan-io/docs/pull/1249
closes #4366
related:
- https://github.com/conan-io/cmake-conan/issues/72
- https://github.com/conan-io/conan/pull/1565
- https://github.com/bincrafters/community/issues/599
additions:
- add `Emscripten` OS
- add `asm.js` and `wasm` (Web Assembly) architectures
- add `asmjs-local-emscripten` and `wasm32-local-emscripten` GNU triplets (see http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob;f=config.sub;h=3b4c7624b68d2d7f84618e1b5fa2badd43a48325;hb=HEAD#l1248 and http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob;f=config.sub;h=3b4c7624b68d2d7f84618e1b5fa2badd43a48325;hb=HEAD#l1170)
I've did some testing with the following profile:
```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang …
```
=> Feature: add support for Emscripten (asm.js & wasm)

conans/client/generators/visualstudio.py, conans/test/functional/generators/xcode_gcc_vs_test.py, conans/test/unittests/client/generators/visual_studio_test.py
Changelog: Fix: Use back slashes for ``visual_studio`` generator instead of forward slashes
Docs: omit
NOTE: This might be a bit risky, as visual_studio is not that thoroughly tested. Might need extra manual check.
@tags: slow
Close #4969
=> try visual_studio generator with backslashes

conans/client/generators/cmake_find_package.py
Changelog: Bugfix: Made compatible the `cmake_find_package_multi` generator with `CMake < 3.9`
Docs: omit
Close #5040
=> Fix find_dependency NO_MODULE for cmake < 3.9

conans/client/generators/premake.py, conans/test/unittests/client/generators/premake_test.py
Changelog: Fix: Handle quoted path and libraries in the premake generator
Fix #5050
=> Fix premake quoted path or names

conans/test/unittests/util/files/tar_extract_test.py, conans/util/files.py
Changelog: Bugfix: 'tar_extract' function was failing if there was a linked folder in the working dir that matches one inside the tar file. Now we use the `destination_dir` as base directory to check this condition.
Docs: omit
closes #4959
=> 'tar_extract' function fails if there is a linked folder in workingdir that matches one in the tar file

conans/client/installer.py, conans/test/functional/command/create_test.py
Changelog: Bugfix: Remove package folder in ``conan create`` even when using ``--keep-build``
Docs: omit
=> Always remove package folder in conan create

conans/client/build/msbuild.py, conans/test/unittests/client/build/msbuild_test.py
Changelog: Feature: The `MSBuild` build helper allows the parameter `toolset` with `False` value to skip the toolset adjustment.
Docs: https://github.com/conan-io/docs/pull/1260
Closes #4975
=> MSBuild. parameter to skip toolset adjustement

conans/client/conf/__init__.py
Changelog: Feature: Add GCC 9 to default settings.yml
Docs: conan-io/docs#1257
I'm assuming that no separated issue is required for such a small change. Please correct me if I'm wrong with that assumption
=> Add GCC 9 to default settings.yml

conans/client/build/cmake_flags.py, conans/test/unittests/client/generators/cmake_test.py
cmake_flags.py add also CMAKE_MODULE_PATH when using that generator. Looks like the find_dependency needs it.
closes #4956
Changelog: Fix: Include CMAKE_MODULE_PATH for CMake find_dependency (#4956)
Docs: Omit
=> #4956 cmake_find_package_multi might need also CMAKE_MODULE_PATH

conans/client/graph/graph_builder.py, conans/test/functional/build_requires/build_requires_test.py, conans/test/functional/graph/graph_manager_test.py
Changelog: Bugfix: Fixing exception of transitive build-requires mixed with normal requires
Docs: omit
Close #5043
Address https://github.com/conan-io/conan/pull/4987#issuecomment-487179864
@tags: slow
=> fixed problem with transitive build_requires

conans/util/files.py
Changelog: Bugfix: Uncompressing a `tgz` package with a broken symlink failed while touching the destination file.
Docs: omit
Already at develop!
=> Not fail touching

conans/client/cmd/uploader.py, conans/test/functional/configuration/compressed_symlinks_test.py
Changelog: Bugfix: The symlinks compressed in a `tgz` had invalid nonzero size.
Docs: omit
Close #4050
=> Fixed 0 size and test

conans/client/tools/oss.py, conans/test/unittests/client/tools/os_info/osinfo_test.py
Changelog: Fix: MSYS 3.x detection
Docs: omit
https://github.com/conan-io/conan/issues/5071
=> Fix: MSYS 3.x detection

conans/client/installer.py, conans/client/manager.py, conans/test/functional/editable/layouts_test.py, conans/test/utils/tools.py
Changelog: Bugfix: Don't crash when an editable declare a ``build_folder`` in the layout, but not used in a workspace
Docs: omit
Close #4819
=> fix for editable declaring build_folder

conans/client/cmd/new_ci.py
- sudo is no longer required to run Docker
- Update Python version to 3.7
Changelog: Fix: Remove sudo from Travis CI template
Docs: https://github.com/conan-io/docs/pull/1270
=> Remove sudo from Travis template

conans/client/cmd/new.py, conans/test/integration/devflow_test.py
Changelog: Feature: Updated the generated *conanfile.py* in ``conan new`` to the new [conan-io/hello].(https://github.com/conan-io/hello) repository
Docs: https://github.com/conan-io/docs/pull/1269
=> Use conan-io/hello example for the new command

conans/client/cmd/uploader.py, conans/test/functional/command/upload_test.py, conans/test/integration/revisions_test.py, conans/test/utils/tools.py
Changelog: Bugfix: ``conan upload --force`` force also the upload of package binaries, not only recipes
Docs: omit
Close #5083
At least, the Conan client side. Not sure what would happen with Artifactory de-duplication if that is the case, but lets at least see if CI passes
=> upload --force uploads package always

conans/client/cache/remote_registry.py, conans/client/migrations_settings.py, conans/test/functional/configuration/registry_test.py
Changelog: Fix: Fix migration of *registry.json|txt* file including reference to non existing remotes.
Docs: omit
@lasote it is necessary to find a way to fix the migrations settings.yml before closing the release, otherwise both develop and all patch releases are broken initially,
=> fix migration

conans/client/conf/__init__.py
Changelog: Feature: Add gcc 8.3 and 9.1 new versions to default *settings.yml*
Docs: omit
Close #5111
=> add gcc versions 8.3, 9.1

conans/client/cache/remote_registry.py, conans/test/functional/command/remote_test.py
Changelog: Fix: Fix regression of ``conan remote update --insert`` using the same URL it had before
Docs: omit
Close #5107
=> fix remote update --insert with same url

conans/client/conan_api.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Bugfix: Avoid crash of commands copy, imports, editable-add for packages using python_requires
Docs: omit
Close #https://github.com/conan-io/conan/issues/5140
=> fixing python_requires remotes commands

conans/client/cmd/export.py, conans/test/unittests/client/cmd/export_test.py
Changelog: Bugfix: Using `scm` declared in a superclass failed exporting the recipe with the error `ERROR: The conanfile.py defines more than one class level 'scm' attribute`.
Docs: omit
Closes #5181
=> Inherit scm from superclass

conans/client/rest/uploader_downloader.py, conans/test/functional/remote/retry_test.py, conans/test/utils/tools.py
Change-Id: Ic1c1814b6e5f46dec8b7e1ffd0661ae619a01ca1
Changelog: Feature: Retry upload or download for error in response message (e.g. status is '500')
Close #4907
I added a first fix for the issue in https://github.com/conan-io/conan/issues/4907.
=> Retry upload or download for error in response message

conans/client/tools/scm.py, conans/test/functional/scm/issues/test_svn_tag.py
Changelog: Fix: Use `revision` as the SVN's `peg_revision` (broken for an edge case)
Docs: omit
closes #5017 
=> Use 'revision' as the SVN's 'peg_revision' (broken for an edge case)

conans/client/cmd/new.py, conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/new_test.py
Changelog: Feature: New ``conan new --template=mytemplate`` to initialize recipes with your own templates
Docs: https://github.com/conan-io/docs/pull/1286
Close #5192
=> templates for conan new

conans/test/unittests/client/conf/detect/detected_os_test.py, conans/tools.py
Add alias for tools.oss.detected_os
Changelog: Fix: Export detected_os from tools.oss (#5101)
Docs: https://github.com/conan-io/docs/pull/1276
fixes #5101
=> #5101 Export detected_os from OSS Tools

conans/model/workspace.py, conans/test/functional/workspace/workspace_test.py
This pull-request closes #5155
=> Feature: Support yaml list as workspace root.

conans/client/loader.py, conans/model/conan_file.py, conans/test/functional/command/invalid_configuration_test.py
Changelog: Bugfix: Conan command returns 6 (Invalid configuration) also when the settings are restricted in the recipe
Docs: PENDING
Closes #5163
=> Raise invalid configuration when restricted

conans/client/file_copier.py, conans/test/functional/old/file_copier_test.py
Changelog: Fix: self.copy with symlinks=True does not copy symlink if the .conan directory is a symlink #5114
Docs: omit
=> Fix missing symlink copy if src folder is a symlink (#5114)

conans/client/cmd/download.py, conans/test/functional/command/download_test.py
Changelog: Bugfix: ``conan download`` always retrieve the sources, also with ``--recipe`` argument, which should only skip download binaries, not the sources.
Docs: omit
Close #5193
=> conan download always fetch sources

conans/client/command.py, conans/client/conan_api.py, conans/client/graph/graph_binaries.py, conans/client/output.py, conans/client/tools/files.py, conans/client/userio.py, conans/test/functional/command/build_test.py, conans/test/functional/command/create_test.py, conans/test/functional/command/install_test.py, conans/test/functional/command/test_package_test.py, conans/test/functional/conan_api/two_conan_creates_test.py, conans/test/integration/install_outdated_test.py, conans/test/integration/only_source_test.py, conans/tools.py
Changelog: Feature: Print errors and warnings to `stderr`
Docs: omit
Close #5207
=> Exception errors to stderr

conans/client/conf/config_installer.py, conans/test/unittests/client/conf/config_installer/test_process_folder.py
Changelog: Bugfix: Check that registry file exists before removing it
Docs: omit
closes #5214
=> Check that registry file exists before removing it

conans/client/generators/cmake_common.py, conans/test/functional/generators/cmake_multi_test.py, conans/test/utils/multi_config.py
Changelog: Bugfix: The `cmake_multi` generator was not managing correctly the `RelWithDebInfo` and `MinSizeRel` build types.
Docs: omit
Closes #5131 
@tags: slow
=> RelWithDebInfo and MinSizeRel (cmake_multi)

conans/client/build/cmake.py, conans/test/unittests/client/build/cmake_test.py
Changelog: Fix: Add the ability to avoid the `/verbosity` argument in CMake command line for MSBuild
Docs: https://github.com/conan-io/docs/pull/1292
closes #5216 
The user can avoid the `/verbosity` argument by using `msbuild_verbosity=None` in the `CMake` constructor. Previously this value was setting `/verbosity:minimal`.
----
⚠️  This PR only _breaks_ the use case where the recipe is creating `CMake` helper with an explicit `None` value for the MSBuild verbosity: `CMake(... msbuild_verbosity=None)`
* before, it will translate to the argument `/verbosity:minimal`.
* now it will remove the argument `/verbosity`
=> Cmake::msbuild_verbosity can be avoided in the command line

conans/client/build/cmake.py, conans/client/build/cmake_flags.py, conans/test/unittests/client/build/cmake_test.py
closes: #5133 
Bugfix: do not append "-T <toolset>" if generator doesn't support it
Docs: omit
=> Bugfix: do not append "-T <toolset>" if generator doesn't support it

conans/client/graph/build_mode.py, conans/client/graph/graph_binaries.py, conans/test/integration/install_cascade_test.py, conans/test/unittests/client/graph/build_mode_test.py
Changelog: Feature: New build mode `--build cascade` that forces building from sources any node with dependencies also built from sources. 
Docs: https://github.com/conan-io/docs/pull/1296
Closes #5121 
@TAGS: slow
=> Build mode cascade

conans/requirements.txt, conans/server/revision_list.py, conans/test/unittests/client/util/time_test.py, conans/util/dates.py
Changelog: Bugfix: Fix `conan search` command showing revisions timestamps in a different time offset than UTC.
Docs:omit
Previously I tried to avoid introducing a new dep (python-dateutil) for that but if we need to manage offsets, it is worth it.
Closes #5230 
@REVISIONS: 1
=> Use dateutil for managing ISO8601

conans/client/build/autotools_environment.py, conans/client/build/meson.py, conans/test/unittests/client/build/autotools_environment_test.py, conans/test/unittests/client/build/compiler_flags_test.py, conans/test/unittests/client/build/meson_test.py
closes: https://github.com/conan-io/conan/issues/4573
tags: @slow, @svn
Changelog: Bugfix: Meson build-helper gets correct compiler flags, AutoTools build environment adds compiler.runtime flags
Docs: omit
short story: currently meson build helper doesn't propagate required compiler flags, like `AutoToolsBuildEnvironment`, `CMake` or `MSBuild` do. it requires ugly workarounds in each recipe:
```
if str(self.settings.compiler) in ["gcc", "clang"]:
if self.settings.arch == "x86":
defs["c_args"] = "-m32"
defs["cpp_args"] = "-m32"
defs["c_link_args"] = "-m32"
defs["cpp_link_args"] = "-m32"
elif self.settings.arch == "x86_64":
defs["c_args"] = "-m64"
defs["cpp_args"] = "-m64"
defs["c_link_args"] = "-m64"
defs["cpp_link_args"] = "-m64"
elif self.settings.compiler == "Visual Studio": …
```
=> Bugfix: ensure meson gets correct compiler flags

conans/client/build/visual_environment.py, conans/client/generators/visualstudio.py, conans/test/functional/generators/visual_studio.py
Changelog: Bugfix: ``visual_studio`` generator only adds ".lib" extension for lib names without extension, otherwise (like ".a") respect it.
Docs: omit
@tags: slow
=> allow other extensions to visual generator

conans/client/cmd/new.py
Docs: omit
There is a problem if the template contains dicts or any braces in general { } as it was using the python format string to replace them. Changed for full substituion of the ``{name}`` string, but please tell if you prefer ``%name%`` placeholders instead.
=> fix new template

conans/client/graph/python_requires.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Bugfix: Fix bug with python-requires not being updated with ``--update`` if using version-ranges.
Docs: omit
Close #5264
=> fixing python-require version-range update

conans/client/rest/uploader_downloader.py, conans/test/functional/remote/auth_test.py, conans/test/functional/remote/retry_test.py
Changelog: Fix: Do not retry file transfer operations for 401 and 403 auth and permissions errors.
Docs: omit
Comes from https://github.com/conan-io/conan/issues/5271 (but is not the fix to that issue)
@tags: slow
=> don't retry auth

conans/client/conf/detect.py, conans/test/unittests/util/detect_test.py
A simple usability and quality of life improvement. It is better to copy and paste a command given to you, rather than manual editing of a file.
Code change for #5273
=> Better message for GCC OLD ABI COMPATIBILITY

conans/client/tools/files.py
Changelog: Bugfix: Use case insensitive comparison for SHA256 checksums
Docs: Omit
Fixes mismatches for the same signature with different case sensitivity e.g.:
```
Provided signature: C75203EF4759E4D7BC38E686B156C54C43B78EDC73123C0B25DB5224758BD1FC  
Computed signature: c75203ef4759e4d7bc38e686b156c54c43b78edc73123c0b25db5224758bd1fc
```
@SSE4
=> Compare sha256 case insensitive

conans/client/generators/cmake_common.py
fixes #5318 
Changelog: Fix: Accept v140 and VS 15.0 for CMake generator (#5318)
Docs: Omit
=> Accept v140 and VS 15.0 for CMake generator (#5318)

conans/client/rest/__init__.py, conans/client/rest/rest_client_common.py, conans/client/rest/rest_client_v1.py, conans/client/rest/rest_client_v2.py, conans/client/rest/uploader_downloader.py
Changelog: Bugfix: Conan was retrying the upload when failed with error 400 (request error).
Changelog: Feature: Print nicer error messages when receive an error from Artifactory.
Docs: omit
Raised by Artifactory QA team, when trying to upload to a virtual repository (without configured deploy repo) we were retrying and not printing anymore the server error in the output:
**At 1.15**:
```
Error uploading file: conanfile.py, 'b'{\n  "errors" : [ {\n    "status" : 400,\n    "message" : "Unable to upload into a virtual Conan repository without default local deployment repository configured."\n  } ]\n}''
```
**At 1.16**:
```
Error uploading file: conanfile.py, '400 Client Error: Bad Request for url: http://artifactory:8081/artifactory/api/conan/conan-virtual/v2/conans/simple/1.0/user/channel/r …
```
=> Do not retry 400 and print better error messages

conans/requirements.txt
Docs: omit
Version 1.4.0 released June 5th brokes our CI trying to install the dependency: `error: Microsoft Visual C++ 10.0 is required`.
@PYVERS: py34
Waiting for https://github.com/PyCQA/astroid/issues/676 and/or https://github.com/python/typed_ast/issues/122, the alternative is to maintain a fork of `astroid` and freeze `typed-ast` dependency (LOC: https://github.com/PyCQA/astroid/blob/01a25f31962dd5017a141a6450859a7c1c82722d/astroid/__pkginfo__.py#L33)
=> Fix requirement: typed-ast less that 1.4.x

conans/client/generators/cmake_common.py, conans/requirements.txt
Changelog: Fix: Accept v140 and VS 15.0 for CMake generator (#5318)
Changelog: Fix: Constraint transitive dependency typed-ast (required by astroid) in python3.4, as they stopped releasing wheels, and it fails to build in some Windows platforms with older SDKs.
Docs:omit
=> Ported #5318 and #5324 to 1.15

conans/test/functional/generators/virtualbuildenv_test.py, conans/test/unittests/util/files/tar_extract_test.py
Sort retrieved and expected folder content list to ensure determinism.
Closes #5299
=> UT util/files/tar_extract : added sorting on expected and retrieved

conans/client/cmd/export_linter.py, conans/pylint_plugin.py, conans/test/functional/command/export_linter_test.py
Since Conan 1.16.0 we are able to add a data file called conandata.yml, which can be retrieved by `self.conan_data` in our recipe. However, that member is lazy and Conan's linter detects it as non-member before exporting.
Changelog: Fix: Make conan_data visible to pylint (#5327)
Docs: Omit
fixes #5327 
=> Make conan_data visible to pylint

conans/client/generators/cmake_common.py, conans/test/functional/generators/cmake_test.py
Changelog: Fix: Skipped the compiler version check in the cmake generator when a `-s compiler.toolset` is specified (Visual Studio).
Docs:  omit
Close #5343 
Reverted https://github.com/conan-io/conan/pull/5321
=> Skip cmake compiler checks when toolset declared

conans/client/conan_api.py, conans/client/conf/__init__.py, conans/test/functional/command/config_test.py
Changelog: Fix: Make ``conan config get storage.path`` return an absolute, resolved path
Docs: omit
Close #5338
=> fix storage path

conans/client/source.py, conans/test/functional/configuration/skip_broken_symlinks.py, conans/test/integration/symlinks_test.py, conans/test/unittests/client/source/test_run_scm.py
Changelog: Bugfix: Do not copy directories inside a symlinked one
Docs: omit
closes #5329 
In #5237 we fixed an issue, but also introduced a wrong behavior that was failing for some use cases (see new test: folders inside symlinked folders with more than one level of indirection). The folders inside the symlinked one were being copied (so the symlink folder was generated) and the final function creating the symlinked folder failed because the folder to create was already there (it has already been created due to the previous recursion).
Just for quick reference, this is the layout of the source folder for the new test (`SymlinkExportSources::test_create_source`):
The intention of test (`test_broken_in_local_sources`) is just to prove that broken symlinks are detected before reaching the …
=> Fix regression related to merge_directories with symlinked folders

conans/client/conf/__init__.py, conans/test/unittests/client/build/cpp_std_flags_test.py
Changelog: Feature: Add apple-clang 11.0 to settings.yml (#5328)
Docs: https://github.com/conan-io/docs/pull/1327
closes #5328 
=> Add apple-clang 11 to settings.yml (#5328)

conans/client/remover.py, conans/test/functional/command/remove_test.py
When removing a pattern like _hello/*@conan/testing_, Conan doesn't remove all patterns because all fields (name, version, channel, user) are validated by ConanFileReference. However, when using a pattern like _hello*/*@conan/testing_, the ConanFileReference won't match the name and will search for recipes.
Changelog: Fix: Remove packages when version is asterisk (#5297)
Docs: Omit
fixes #5297 
=> Remove packages when version is asterisk

conans/model/conan_file.py, conans/test/integration/conan_test_test.py, conans/test/integration/order_libs_test.py, conans/test/unittests/model/conan_file/create_requirements_test.py
Changelog: Fix: Accept a list for the requires attribute
Docs: https://github.com/conan-io/docs/pull/1332
closes https://github.com/conan-io/conan/issues/5313
Accept a list for the requires attribute, now any of these formats will get the same result:
* `requires = "req/1.0@user/version", "req2/1.0@user/version"`
* `requires = ("req/1.0@user/version", "req2/1.0@user/version")`
* `requires = ["req/1.0@user/version", "req2/1.0@user/version"]`
And also, if you specify the visibility of the requires:
* `requires = (("req/1.0@user/version", "private"), )`
* `requires = [("req/1.0@user/version", "private"), ]`
=> Accept a list for the requires attribute

conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/copy_packages_test.py, conans/test/functional/command/download_test.py, conans/test/functional/command/upload_test.py
Changelog: Deprecated ``conan copy|download|upload <ref> -p=ID``, use ``conan .... <pref>`` instead
Docs: conan-io/docs#1317
Fixes #5250
Closes #5225
=> P argument deprecation

.codeclimate.yml, .pycodestyle, README.rst, setup.cfg
This PR introduces Code climate badge on README, but Code Climate generates dynamic badges, which means one of Conan admins will need to access https://codeclimate.com/github/conan-io/conan/badges and get the badge url
Also, it would nice enabling some extra features to scan bad smells:
Repo Settings -> Analysis -> Maintainability:
[*] Identical blocks of code
The default branch to be analyzed can be changed at:
Repo Settings -> General -> Danger zone -> Default Branch
By default it's running pep8
Docs: Omit
closes #3558
<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some tags …
=> #3558 Add Code climate badge

conans/client/tools/system_pm.py, conans/test/unittests/client/tools/system_pm_test.py
SystemPackageTool.update() must update only the local cache, but it shouldn't upgrade package. However, Yum uses `update` as a command to update all packages.
Changelog: Fix: Update Yum cache (#5370)
Docs: Omit
fixes #5370
=> Update Yum cache only (#5370)

conans/client/profile_loader.py, conans/test/unittests/client/profile_loader/profile_loader_test.py
Changelog: Fix: Force forward slashes in the variable `$PROFILE_DIR`
Docs: https://github.com/conan-io/docs/pull/1333
closes #5349
=> Use forward slashes for PROFILE_DIR

conans/client/build/autotools_environment.py, conans/test/unittests/client/build/autotools_environment_test.py
Changelog: Fix: `AutoToolsBuildEnvironment` is now aware of `os_target` and `arch_target` to calculate the gnu triplet when declared.
Docs: omit
Closes #5274. 
I've added a simple unittest which runs and passes.
=> Fix AutoToolsBuildEnvironment target triple

conans/client/rest/conan_requester.py
Changelog: Bugfix: enable retry for requests
Docs: omit
closes https://github.com/conan-io/conan/issues/5398
=> Bugfix: enable retry for requests

conans/client/conf/config_installer.py, conans/test/unittests/client/conf/config_installer/test_install_folder.py
- Run rmdir before creating a new temp folder
Changelog: Fix: Remove old folder for conan install (#5376)
Docs: Omit
fixes #5376
=> Remove old folder for conan install  (#5376)

conans/client/conan_api.py, conans/test/functional/command/inspect_test.py
When an attribute inspected by Conan is missing, is will be returned as empty
Changelog: Fix: Inspect missing attribute is not an error (#3953)
Docs: Omit
fixes #3953
=> #3953 Inspect -a shouln't raise AttributeError

conans/client/tools/system_pm.py, conans/test/unittests/client/tools/system_pm_test.py
Changelog: Feature: SystemPackageTool platform detection (#5026)
Docs: https://github.com/conan-io/docs/pull/1291
closes #5026
=> Detect System package name by recipe settings (#5026)

conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/info_test.py
Retrieve dependencies graph from Conan API to generate html.
Changelog: Fix: Allow --build-order and --graph together for conan info (#3447)
Docs: Omit
fixes #3447
=> #3447 Support info build-order and graph

conans/client/graph/range_resolver.py, conans/test/unittests/client/graph/version_ranges_graph_test.py
Changelog: Fix: Improve resolution of version ranges for remotes
Docs: omit
Partially address, in the client side #5432
Separate work must be done in Artifactory
=> Improve resolution speed of version ranges in remotes using the name as pattern

conans/client/cmd/download.py, conans/client/cmd/uploader.py, conans/client/rest/uploader_downloader.py, conans/util/progress_bar.py
Docs: omit
Fix #5422
With these changes a few things happen:
- Using ascii output, always. It eliminates possible encoding errors in different systems. I'd trade prettiness for robustness. It also produces less "glitches" in the output, those that we needed to capture the exception and retry several times or to ignore the output
- The dynamic_ncols is = False. Filling the whole terminal was a bit weird when full screen. It also had a few glitches, when the output failed, old characters were remained to the right, unrefreshed
- The ``leave=True`` removes the need to update the line with a [done] message. I think it is nicer to leave the transfer details there, otherwise for most quick transfers it seems that nothing was done. It might help to troubleshoot some issues.
This …
=> changes to tqdm

conans/model/scm.py, conans/test/functional/scm/scm_test.py
Changelog: Bugfix: `verify_ssl` field in SCM being discarded when used with `False` value.
Docs: omit
=> Fix verify_ssl field in SCM discarded when used with False value

conans/client/generators/qbs.py
The cpp_info.cxxFlags must be exported to the cpp.cxxFlags in Qbs.
The cpp.cppFlags property has a different meaning  (C preprocessor
flags).
Changelog: Bugfix: Use cxxFlags instead of cppFlags in ``qbs`` generator.
Docs: https://github.com/conan-io/docs/pull/1354
Close #4730
- [*] Refer to the issue that supports this Pull Request.
- [*] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [*] I've read the [Contributing guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [*] I've followed the PEP8 style guides for Python code.
=> The Qbs generator must export cxxFlags to cpp.cxxFlags (#4730)

conans/client/conan_api.py, conans/test/functional/command/info_test.py
Changelog: Bugfix: Solve regression in ``conan info <ref>`` command, incorrectly reading the graph_info.json and lockfiles
Docs: omit
Close #5479
@tags: slow
=> solving regression in conan info

conans/test/functional/command/info_test.py, conans/test/functional/command/install_test.py, conans/util/locks.py
Changelog: Bugfix: Trailing files left when packages are not found in conan info and install, restricted further installs with different case in Windows, without ``rm -rf ~/.conan/data/pkg_name``
Docs: omit
This hasn't been reported by users, so maybe not urgent, I could rebase it to develop for next 1.18
@tags: slow
=> trailing locks bug when packages not found

conans/client/tools/scm.py, conans/test/unittests/client/tools/scm/test_git.py
Changelog: Bugfix: apply http.sslVerify to the current Git command only
Docs: omit
closes: https://github.com/conan-io/conan/issues/5462
=> Bugfix: apply http.sslVerify to the current Git command only

conans/requirements.txt
Changelog: Bugfix: Update python-dateutil dependency to ensure availability of `dateutil.parser.isoparse`
Docs: Omit
- Closes: #5484.
Do you want a docs PR for this one? I feel like this one will be very rarely hit.
=> python-dateutil>=2.7.0 is required for dateutil.parser.isoparse

conans/client/cache/cache.py, conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/config_install_test.py, conans/test/functional/command/config_test.py, conans/test/functional/command/export_test.py, conans/test/functional/command/info_folders_test.py, conans/test/functional/command/info_test.py, conans/test/functional/command/install_test.py, conans/test/functional/command/new_test.py, conans/test/functional/configuration/default_profile_test.py, conans/test/functional/configuration/registry_test.py, conans/test/functional/cppstd/compiler_cppstd_test.py, conans/test/functional/editable/consume_header_only_test.py, conans/test/functional/editable/consume_settings_and_options_test.py, conans/test/functional/editable/layouts_test.py, conans/test/functional/editable/transitive_editable_test.py, conans/test/functional/graph/full_revision_mode_test.py, conans/test/functional/graph_lock/graph_lock_ci_test.py, conans/test/functional/old/conanfile_extend_test.py, conans/test/functional/old/test_migrations.py, conans/test/functional/scm/test_local_modified.py, conans/test/integration/manifest_validation_test.py, conans/test/integration/run_envronment_test.py, conans/test/unittests/model/other_settings_test.py, conans/test/utils/tools.py
Docs: Omit
Pure refactor:
- Use self._out in Command instead of self._user_io.out
- Use ``cache_folder`` instead of ``base_folder`` in TestClient
- Use ``client.cache_folder`` access directly, instead of ``client.cache.cache_folder``
=> base_folder => cache_folder

conans/client/conf/detect.py, conans/test/functional/command/profile_test.py
Changelog: Bugfix: When a profile was detected, for GCC 5.X the warning message about the default `libcxx` was not shown.
Docs: omit
When GCC == 5.X, the comparison ` if Version(version) >= Version("5.1"):` was never true, because `version` had always the major version only. In CI the GCC version is `5.3`, so the tests were never doing the assert because the warning was never printed.
=> Fixed GCC 5 warn about libcxx and tests

conans/client/graph/graph_manager.py, conans/client/loader.py, conans/model/profile.py, conans/test/unittests/client/conanfile_loader_test.py, conans/test/unittests/client/loader_test.py, conans/test/unittests/model/profile_test.py, conans/test/utils/tools.py
Docs: Omit
this was a pending refactor to remove the ProcessedProfile class that reads a bit artificial. @jgsogo did a try to remove it, but without implementing the caching, this PR is doing that.
Please @lasote check if the code is more clear this way or not:
- Removed some ugly access of private members
- Doing caching directly in Profile
- Did NOT do a rename ``processed_profile`` => ``profile`` variables, to avoid excessive noise in the PR, can be done later
=> remove ProcessedProfile class

conans/model/graph_lock.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Bugfix: Lock transitive python-requires in lockfiles, not only direct ones.
Docs: omit
Close #5529 
@tags: slow
=> locking transitive python-requires

conans/client/build/cmake_flags.py, conans/test/functional/build_helpers/cmake_flags_test.py, conans/test/unittests/client/build/cmake_test.py
Docs: omit
@tags: slow
------
Related to #5289 comments made by @memsharded 
Pure refactor of CMake related stuff at #5289:
- Renamed `conan_file` to `conanfile`.
- Renamed `ret` to `defintions` in `CMakeDefintionsBuilder` class.
- Moved `cmake_minimum_required()` to the top of *CMakeLists.txt* files in tests.
----------------
=> Pure refactor from PR #5289

conans/client/cmd/uploader.py, conans/client/installer.py, conans/client/source.py, conans/test/unittests/util/files/test_dirty.py, conans/util/files.py
I've preferred add a new method with context manager supported, otherwise `set_dirty` would execute different behaviors, which is not good in terms simplicity.
Changelog: Feature: Add context manager for set_dirty (#3835)
Docs: https://github.com/conan-io/docs/issues/1231
closes #3835
=> Add context manager for set_dirty (#3835)

conans/client/source.py, conans/model/scm.py
Changelog: Fix: Discard empty string values in SCM including `subfolder`
Docs: omit
@tags: SVN
Related to https://github.com/conan-io/conan/pull/5441
Discard the empty string values in the representation of the `SCMData` class.
=> [engineering] SCM discard empty string values

conans/search/search.py, conans/test/functional/command/search_test.py
- Search sub-settings for common settings
Changelog: Feature: Search custom settings (#5378)
Docs: https://github.com/conan-io/docs/pull/1371
closes #5378 
=> #5378 Search custom settings

conans/client/command.py, conans/client/conan_api.py, conans/client/installer.py, conans/model/graph_lock.py, conans/test/functional/graph_lock/graph_lock_ci_test.py
Changelog: Fix: Remove ``conan graph clean-modified`` command, it is automatic and no longer necessary.
Docs: https://github.com/conan-io/docs/pull/1378
=> remove clean modified command

conans/client/cmd/user.py, conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/user_test.py
Changelog: Feature: New parameter ``--skip-auth`` for the ``conan user`` command to avoid trying to authenticate when the client already has credentials stored. 
Docs: https://github.com/conan-io/docs/pull/1377
Close https://github.com/conan-io/conan/issues/5443
=> Flag to skip auth if already authenticated

conans/client/tools/oss.py, conans/errors.py
Changelog: Bugfix: The `stderr` was not printed when a command failed running the `tools.check_output` function.
Docs: omit
@TAGS: svn
=> Fix print stderr on failure at `check_output` tool.

conans/client/tools/scm.py, conans/model/scm.py, conans/test/unittests/client/tools/scm/test_git.py, conans/test/unittests/client/tools/scm/test_svn.py, conans/test/utils/tools.py
Changelog: Feature: shallow git clone
Docs: https://github.com/conan-io/docs/pull/1380
closes: https://github.com/conan-io/conan/issues/3770
@tags: svn, slow
@revisions: 1
=> Feature: shallow git clone

conans/client/tools/scm.py, conans/model/scm.py, conans/test/functional/scm/scm_test.py
Changelog: Bugfix: The `scm` feature was trying to run a checkout after a shallow clone.
Docs: omit
Closes #5570 
@REVISIONS: 1
=> Fix shallow copy: 1.18.1

conans/client/installer.py, conans/model/build_info.py, conans/test/integration/package_info_test.py, conans/test/unittests/model/build_info_test.py
Changelog: Feature: Adds `name` attribute to `CppInfo`
=> Adds name attribute to CppInfo

conans/client/manager.py, conans/test/functional/generators/custom_generator_test.py
Changelog: BugFix: Fix crash with custom generators using ``install_folder``
Docs: Omit
Close #5568
@tags: slow
=> define install_folder to be usable by custom generators

conans/client/tools/scm.py
Changelog: Bugfix: `SVN` uses `username` and `password` if provided
Docs: omig
closes https://github.com/conan-io/conan/issues/5599
@tags: svn, slow
=> Pass username and password as extra options to SVN commands

conans/client/cache/cache.py, conans/test/functional/command/remote_test.py
Changelog: Bugfix: Broken cache package collection for packages without user/channel
Docs: omit
Close #5606
=> fixing remote clean without user/channel

conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/config_test.py, conans/test/functional/conan_api/config.py
- Add `config home` command to retrieve Conan home dir
- Add functional tests to validate `config home`
Changelog: Feature: Retrieve Conan home directory
Docs: https://github.com/conan-io/docs/pull/1387
closes https://github.com/conan-io/conan/issues/5572
=> #5572 Retrieve Conan home directory

conans/client/tools/oss.py, conans/test/unittests/util/detected_architecture_test.py
Changelog: (Bugfix): Fix support for building on the Solaris OS
Docs: Omit
Issue:  https://github.com/conan-io/conan/issues/5629
Under Solaris, ```platform.machine()``` returns strings that Conan was not expecting.  In this PR code is added to handle Solaris OS first, as on Intel Solaris the string returned is "i86pc" this would return "x86" rather than the 64-bit architecture "x86_64".
=> Add support for Solaris sparc and x86.

conans/client/packager.py
Changelog: Bugfix: Use the final package folder as the `conanfile.package_folder` attribute for the `pre_package` hook.
Docs: omit
This is a bugfix for the experimental `hooks` feature.
The `package_folder` assigned to the `conanfile` object (to use its value in the `pre_package` hook) uses a different value for the `export-pkg` workflow and for the `create_package` one. (The current value was introduced here https://github.com/conan-io/conan/pull/3555/files#diff-94888d4df1b14d7fdea15cb92ad304ecR17)
IMO, it makes sense to use always the `package_folder` there (the folder where the package will be stored).
=> Use the final package folder as the 'conanfile.package_folder' attribute for the 'pre_package' hook

conans/client/packager.py, conans/paths/package_layouts/package_cache_layout.py, conans/test/functional/hooks/test_post_package.py, conans/test/utils/tools.py
Changelog: Fix: Call `post_package` hook before computing the manifest
Docs: omit
With this PR the hook `post_package` runs before computing the manifest, so example [here](https://docs.conan.io/en/latest/extending/hooks.html#id3) would work as documented:
```python
import os
from conans import tools
SIGNATURE = "this is my signature"
def post_package(output, conanfile, conanfile_path, **kwargs):
sign_path = os.path.join(conanfile.package_folder, ".sign")
tools.save(sign_path, SIGNATURE)
output.success("Package signed successfully")
```
closes #5588
=> Call post_package hook before computing the manifest

conans/test/functional/build_requires/build_requires_test.py, conans/test/functional/command/export_pkg_test.py, conans/test/functional/command/info_test.py, conans/test/functional/command/install_test.py, conans/test/functional/command/upload_test.py, conans/test/functional/editable/layouts_test.py, conans/test/functional/editable/transitive_editable_test.py, conans/test/functional/graph/full_revision_mode_test.py, conans/test/functional/graph/graph_manager_base.py, conans/test/functional/graph/graph_manager_test.py, conans/test/functional/graph/half_diamond_test.py, conans/test/functional/graph/package_id_modes_test.py, conans/test/functional/graph/private_deps_test.py, conans/test/functional/graph/transitive_deps_test.py, conans/test/functional/graph/version_range_error_test.py, conans/test/functional/graph_lock/graph_lock_test.py, conans/test/functional/old/package_integrity_test.py, conans/test/functional/old/test_migrations.py, conans/test/functional/python_requires/python_requires_test.py, conans/test/integration/package_id_test.py, conans/test/unittests/client/graph/version_ranges_graph_test.py, conans/test/unittests/model/transitive_reqs_test.py, conans/test/utils/conanfile.py, conans/test/utils/tools.py
Docs: omit
Unifying test code: `TestConanFile` is deprecated in favor of `GenConanfile`
closes #5525 
@tags: slow
=> [refactor] Remove TestConanFile in favor of GenConanFile

conans/client/graph/range_resolver.py, conans/test/unittests/client/graph/version_ranges_graph_test.py
Changelog: Bugfix: Using the version ranges mechanism Conan wasn't able to resolve the correct reference if a library with the same name but different user/channel was found in an earlier remote.
Docs: omit
Closes #5649
=> Fix range resolver with different user/channel

conans/test/unittests/client/tools/net_test.py
Docs: omit
Commented test (`test_ftp_anonymous`) **is failing only in Macos** ([[1](https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-5667/4/pipeline)], [[2](https://conan-ci.jfrog.info/blue/organizations/jenkins/ConanTestSuite/detail/PR-5668/7/pipeline)]), although it is run for all platforms (see commit _"running ftp anon test"_ in this PR).
=> running ftp anon test

conans/client/build/msbuild.py, conans/test/unittests/util/build_sln_command_test.py, conans/test/unittests/util/tools_test.py
Changelog: Fix: Use the value of argument `useEnv` provided by the user to the `MSBuild` helper also to adjust `/p:UseEnv=false` when the arg is `False`.
Docs: omit
`VisualStudioBuildEnvironment` defaults `useEnv=True`, then if the user calls with `MSBuild.build(...., use_env=False,...)` the input was not taken into account. This PR complements the functionality introduced in https://github.com/conan-io/conan/pull/4655
@tags: slow
=> MSBuild::build - Take into account 'useEnv' argument from user input

conans/client/rest/rest_client.py, conans/client/rest/rest_client_common.py, conans/test/functional/old/conan_trace_file_test.py, conans/test/functional/remote/server_error_test.py
Changelog: Bugfix: When Artifactory doesn't have the anonymous access activated, the conan client wasn't able to capture the server capabilities and therefore never used the `revisions` mechanism.
Docs: omit
Closes #5687 
@REVISIONS: 1
=> Fixed anonymous access with Artifactory

conans/client/source.py, conans/model/scm.py, conans/test/functional/scm/scm_test.py, conans/test/functional/scm/test_fields_validation.py, conans/test/functional/scm/test_git_shallow.py, conans/test/functional/scm/test_verify_ssl.py, conans/test/unittests/model/scm/detect_repo_test.py, conans/test/unittests/model/scm/scm_data_test.py
Changelog: Feature: Add opt-out for Git shallow clone in `SCM` feature
Docs: https://github.com/conan-io/docs/pull/1400
closes https://github.com/conan-io/conan/issues/5631
---
This PR introduces also:
* validation of SCM data values
* prevent bug using `scm::verify_ssl` and scm `auto` values
=> Opt-out for Git shallow clone in SCM feature

conans/client/generators/visualstudio.py, conans/test/functional/generators/xcode_gcc_vs_test.py, conans/test/unittests/client/generators/visual_studio_test.py
Changelog: Feature: Enhanced vs-generator by providing more properties that can be referenced by other projects; added library paths also to <Lib> so it's possible to compile static libraries that reference other libs
Docs: Omit
Close #5561
=> Enhance vs-generator

conans/search/search.py, conans/test/functional/graph/version_range_no_userchannel_test.py
Changelog: Fix: Version ranges resolution using references without user/channel
Docs: omit
It was using `str` for the references from the folders and the pattern (`libB/*@_/_`) was not able to match them.
=> Fix: Version ranges resolution using references without user/channel

conans/requirements.txt
Changelog: Fix: Relax restriction on the future python dependency
Docs: omit
Fixes #5637 
@pyvers: py27, py34, py36
=> Relax restriction on the future python dependency

conans/client/cmd/search.py, conans/search/search.py, conans/server/service/common/search.py, conans/test/functional/command/download_test.py, conans/test/functional/command/search_test.py, conans/test/unittests/server/service/service_test.py, conans/test/utils/tools.py
Changelog: Fix: Output  search result for remotes in order by version, as local search
Docs: omit
Fix #5720
@tags: slow
=> order search

conans/client/command.py, conans/test/functional/command/help_test.py
Changelog: UX: Make the error on incorrect command input more helpful
Docs: omit
Closes #5724
=> Print similar commands on the unknown command error

conans/client/rest/conan_requester.py
Changelog: Fix: Excluded also `ftp_proxy` and `all_proxy` variables from the environment when proxy configuration is specified in the `conan.conf` file.
Docs: Omit
Fixes #5683
=> Add ftp_proxy and all_proxy proxy variables to fix #5683

conans/model/info.py, conans/test/unittests/model/info_test.py
Changelog: Fix: ``package_id`` should be used for ``recipe_revision_mode``
Docs: https://github.com/conan-io/docs/pull/1410
@TAGS: slow
@REVISIONS: 1
=> [Fix] package_id should be used for 'recipe_revision_mode'

conans/client/generators/__init__.py, conans/client/generators/virtualenv_python.py, conans/test/functional/generators/virtualenv_python_test.py, conans/test/unittests/client/generators/virtualenv_python_test.py
Changelog: Feature: Virtual environment generator for gathering only the PYTHONPATH.
Docs: https://github.com/conan-io/docs/pull/1369
This pull-request closes #5157
=> Feature: Generator for python environment

conans/client/cmd/new.py
Changelog: Fix: Make `conan new` generate default options as a dictionary
Docs: omit
Closes #5766
=> Make conan new use dict in default options

conans/test/functional/generators/make_test.py
Docs: omit
Develop was broken after merging #5767
#TAGS: slow
=> FIX DEVELOP: fix default options replace in file

conans/client/conf/__init__.py
Changelog: (Feature): Add clang 9 to default list of compilers
Docs: https://github.com/conan-io/docs/pull/1420
Closes #5785
=> Add clang 9

conans/client/conf/__init__.py
Changelog: (Feature): Add GCC  9.2 to default settings.yml file
Docs: https://github.com/conan-io/docs/pull/1394
Closes #5787
=> Add GCC version 9.2

conans/requirements.txt
Docs: omit
Closes #5802 
urllib3 version 1.25.6 has been released and doesn't contain the bug, so forbid the two buggy versions but unlock the version
---
From the `urllib3` changelog:
>1.25.6 (2019-09-24)
>Fix issue where tilde (~) characters were incorrectly percent-encoded in the path. (Pull https://github.com/urllib3/urllib3/pull/1692)
=>  Lock buggy urllib3 versions only

conans/client/graph/graph_builder.py, conans/model/requires.py, conans/test/functional/graph/conflict_diamond_test.py, conans/test/functional/graph_lock/graph_lock_test.py, conans/test/unittests/model/transitive_reqs_test.py
Changelog: Fix: Apply lockfile to the node before updating with downstream requirements
Docs: omit
If we apply the graphlock to the requires declared in the recipe, they will be populated with some data (recipe revisions) and will match the requirements downstream that already contains graphlock information.
I'm using a version range ``harfbuzz/[>=1.0]`` in the requirement because it is resolved to a fixed version with the graphlock. With a regular requires ``harfbuzz/1.0`` the behavior would be the same.
Fix https://github.com/conan-io/conan/issues/5754
--- 
**Not fixed here:** 
* ⚠️ If we require a specific revision, like ``harfbuzz/1.0#12345`` then the diamond will be resolved and the requirement overridden with a misleading message:
```
WARN: ffmpeg/1.0 requirement harfbuzz/1.0 …
```
=> Apply lockfile before updating downstream requires

conans/model/conan_file.py, conans/test/integration/same_userchannel_test.py
Docs: omit
if CONAN_USERNAME and CONAN_CHANNEL are deprecated, the error shouldn't talk about them.
Taken from https://github.com/conan-io/conan/pull/5750
=> Deprecation of CONAN_USERNAME and CONAN_CHANNEL: fix error message

.travis.yml, appveyor.yml
Changelog: Fix: Dropped support for python 3.4.  That version is widely being dropped by the python community. Since Conan 1.19, the tests won't be run with python 3.4 and we won't be aware if something is not working correctly.
Docs: https://github.com/conan-io/docs/pull/1424
Note: The files in this PR are not really affecting the conan CI that runs an external library where the python 3.4 has been deactivated already.
=> Remove py34

conans/client/cmd/uploader.py, conans/test/functional/command/remove_test.py, conans/test/functional/command/upload_test.py
Changelog: Fix: ``conan upload`` with a reference without user and channel and package id ``name/version:package_id`` should work
Docs: omit
Fix #5822
#tags: slow
=> fix upload package id

conans/client/command.py, conans/test/functional/configuration/python_version_test.py
- Add new warning message for python 3.4 which is no longer supported
- Added funcional tests to validate both python 3.4 and 2.x
Changelog: Feature: Show warning message for Python 3.4 
Docs: https://github.com/conan-io/docs/pull/1424
=> #5819 Show warning message for Python 3.4

conans/client/installer.py, conans/test/functional/python_requires/python_requires_test.py
Changelog: Bugfix: Use imported python requires' `short_path` value instead of the defined in the `conanfile` that imports it. 
Docs: omit
Closes #5814
=> backport fix for issue 5814 to release 1.19.1

conans/client/generators/visualstudio.py, conans/test/functional/generators/visual_studio_test.py, conans/test/functional/generators/xcode_gcc_vs_test.py, conans/test/unittests/client/generators/visual_studio_multi_test.py, conans/test/unittests/client/generators/visual_studio_test.py
Changelog: Bugfix: Fix regression in ``visual_studio`` generator adding a ``<Lib>`` task.
Docs: https://github.com/conan-io/docs/pull/1430
Close #5844
Close #5848
#tags: slow
=> proposed fix

conans/client/file_copier.py, conans/test/unittests/client/file_copier_test.py
Changelog: Bugfix: avoid repeated copies of absolute paths when using self.copy().
Docs: Omit
No. I tried creating an issue but the "Submit new issue" button stayed greyed-out. However, hopefully this change is minor enough that creating an issue for it isn't necessary.
My team have occasionally written conanfiles that do this:
`def imports(self):
self.copy('foo', src=os.path.join(self.deps_cpp_info['bar'].rootpath, 'baz'))`
What isn't obvious to developers is that self.copy() will iterate over all dependencies and repeat the copy for each one. This is suboptimal. We've ended up using functions from distutils but we'd prefer to be able to use self.copy().
No. This change shouldn't be observable other than speeding things up in some cases.
=> FileCopier: avoid repeated copies of absolute paths.

conans/client/graph/graph.py, conans/client/rest/client_routes.py, conans/model/ref.py, conans/test/functional/graph_lock/graph_lock_ci_test.py, conans/test/integration/revisions_test.py
Changelog: Bugfix: Fix `conan graph build-order` output so it uses references including its recipe revision
Docs: omit
#REVISIONS: 1
If this fix is right, then https://github.com/conan-io/examples/pull/35 should be closed
=> Use reference with recipe revision for build order

conans/client/rest/rest_client.py, conans/test/functional/command/upload_test.py
Changelog: Bugfix: Artifactory was returning an error on the first login attempt because the server capabilities were not assigned correctly.
Docs: omit
Closes #5878
=> Fix setting of server cached capabilities

conans/client/generators/b2.py, conans/test/unittests/client/generators/b2_test.py
Consuming project might not have compiler in its settings. In such case
b2 generator creates files that put None-None toolset into usage
requirements of dependencies, which leads to build error, as such
toolset does not exist. This commit fixes that error.
Changelog: Fix: #5809
=> fixes None-None toolset referenced by b2 generator

conans/client/command.py
Changelog: (Feature | Fix | Bugfix): 
Fix  #5495 
=> Improve help for conan remove command

conans/model/requires.py, conans/model/version.py, conans/test/functional/command/create_test.py, conans/test/unittests/model/version_test.py
Changelog: Bugfix: The dependency overriding mechanism was not working properly when using the same version with different build metadata (`1.2.0+xyz` vs `1.2.0+abc`). 
Docs: omit
Closes #5900
#REVISIONS: 1
=> Requirement override using build metadata

conans/model/info.py, conans/model/options.py, conans/test/integration/options_test.py
Changelog: Feature: Implement ``self.info.shared_library_package_id()`` to better manage shared libraries package-ID, specially when they depend on static libraries
Docs: https://github.com/conan-io/docs/pull/1442
#tags: slow
=> optional management of package-id for shared libraries

conans/model/graph_lock.py, conans/test/functional/graph_lock/graph_lock_test.py
Changelog: Bugfix: Don't crash when apply a lockfile to a ``conanfile.txt``
Docs: Omit
Close #5499
=> fixed bug in lockfiles for conanfile.txt

conans/client/command.py, conans/client/remover.py, conans/model/ref.py, conans/test/functional/command/install_test.py, conans/test/unittests/model/ref_test.py
Changelog: Bugfix: Allow ``conan install pkg/[*]@user/channel`` resolving to a reference, not a path.
Docs: Omit
Fix #5905
=> allow conan install pkg/[*]@user/channel

conans/client/hook_manager.py
Changelog: Fix: remove traceback from exception message raised by execute method of HookManager.
Docs: Omit
Close #5019
=> Remove traceback from ConanException message rasing in executing hooks

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Remove automatic tags when creating a new issue
Docs: Omit
=> Remove autmotic tags for issues

conans/client/installer.py, conans/test/functional/graph/require_override_test.py
Changelog: Bugfix: Fixed bug when overriden dependencies that don't exist and make the CMake generated code crash
Docs: Omit
Close #5680
=> Bugfix: Don't use override dependencies as public dependency for CMake

conans/client/graph/graph.py, conans/client/graph/graph_binaries.py, conans/client/graph/graph_manager.py, conans/client/installer.py
Docs: Omit
Follow up of https://github.com/conan-io/conan/pull/4958. The model for "unknown" binary package-ID was "Missing", which is not true. I have added a explicit one (an internal refactor, doesn't affect behavior)
=> make the unknown binaries explicit

conans/test/utils/tools.py
Docs: omit
I needed to change the order of `TurboTestClient` and `GenConanFile` in the source file, so the diff is crap 😞 , but the only change here is the way argument `conanfile` is handled in `GenConanFile` methods:
This PR sets (for `create`, `export`, `export_pkg`:
```python
def create(self, ref, conanfile=GenConanfile(), args=None, assert_error=False):
if conanfile:
self.save({"conanfile.py": conanfile})
```
It was:
```python
def create(self, ref, conanfile=None, args=None, assert_error=False):
conanfile = str(conanfile) if conanfile else GenConanfile()
self.save({"conanfile.py": conanfile})
```
The new way allows the user to use `TurboTestClient` with existing `conanfile.py` file using `client.create(conanfile=None,...)`
=> Minor improvement to TurboTestClient

conans/client/command.py, conans/test/functional/command/profile_test.py
Changelog: Feature: Saving profile list as a json file
Docs: Omit
issue #5937
=> Saving profile list as a json file

conans/client/rest/rest_client.py, conans/test/functional/old/conan_trace_file_test.py
Changelog: Fix: Avoid doing complex ``conan search --query`` in the server, do them always in the client.
Docs: omit
Fix: #4951
#tags: slow
=> avoiding complex search in servers

conans/client/tools/files.py, conans/test/unittests/client/util/files/decode_text_test.py, conans/util/files.py
closes: #5840 
Changelog: Feature: Allow to specify encoding for `tools.load`, `tools.save` and `tools.replace_in_files`
Docs: https://github.com/conan-io/docs/pull/1446
add encoding argument to the:
- `tools.load`
- `tools.save`
- `tools.save_append`
- `tools.save_files`
- `tools.replace_in_file`
- `tools.replace_path_in_file`
- `tools.to_file_bytes`
the `auto` encoding is for auto-detect
Q: Should I touch `replace_prefix_in_pc_file` and `dos2unix`/`unix2dos` as well?
=> Feature: allow to specify encoding for load, save, replace_in_files

conans/client/cmd/test.py, conans/client/conan_api.py, conans/client/graph/graph_builder.py, conans/client/graph/graph_manager.py, conans/client/installer.py, conans/client/loader.py, conans/client/manager.py, conans/model/graph_info.py, conans/model/graph_lock.py, conans/test/functional/old/create_package_test.py, conans/test/unittests/client/conanfile_loader_test.py, conans/test/unittests/client/graph/version_ranges_graph_test.py, conans/test/unittests/model/fake_retriever.py, conans/test/unittests/model/transitive_reqs_test.py, conans/test/unittests/tools/files_patch_test.py, conans/test/utils/tools.py
Docs: omit
* Remove `processed_profile`
* Rename `profile` to `profile_host` in the places where it will make sense to have a `profile_build` too
=> [refactor] Rename 'profile' to 'profile_host'

conans/client/installer.py, conans/test/functional/graph/require_override_test.py
Changelog: Bugfix: Fixed bug when overriden dependencies that don't exist and make the CMake generated code crash
Docs: omit
Backport of https://github.com/conan-io/conan/pull/5945
Close #5680
=> do not use overrides in public_deps in cmake

conans/client/command.py, conans/test/functional/command/info_test.py
Changelog: Fix: Deprecate argument `--build-order` in `conan info` command.
Docs: https://github.com/conan-io/docs/pull/1451
Add deprecation notice to `conan info --build-order`. It will keep working as it is now, but some related issues might not be fixed (https://github.com/conan-io/conan/issues/5474)
close https://github.com/conan-io/conan/issues/5474
=> Add deprecation notice to 'conan info --build-order'

conans/client/generators/cmake_find_package.py, conans/client/generators/cmake_find_package_multi.py, conans/test/functional/generators/cmake_find_package_multi_test.py, conans/test/functional/generators/cmake_find_package_test.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Bugfix: Fix ``cpp_info.name`` not used in cmake find generators for dependencies
Docs: omit
#TAGS: slow
=> Fix cpp_info.name not used in cmake find generators for dependencies

conans/client/command.py, conans/test/functional/command/config_test.py
Changelog: Feature: JSON output to the "config home" subcommand with ``--json`` argument.
Docs: omit
As the issue referred to making command output more future-proof it can be written to file in JSON format (with the actual path contained in the `home` attribute).
Tests have been extended to make sure that the expected output is contained in the JSON file created.
Fixes #5943
=> Add JSON output option to the "config home" subcommand

conans/client/cmd/export.py, conans/test/functional/command/export_test.py
Changelog: Bugfix: Avoid erroneous case-sensitive conflict for packages without user/channel.
Docs: omit
Close #5985
=> fixing export conflict when no user channel

conans/client/generators/pkg_config.py, conans/test/unittests/client/generators/pkg_config_test.py
Changelog: Bugfix: Use cpp_info.name lower case in pkg-config generator when defined
Docs: omit
=> Use cpp_info.name lower case in pkg-config generator when defined

conans/requirements.txt
Docs: omit
the downgrade of pylint breaks linux py37. Introduced condition.
=> Fixed pylint requirements, py37

conans/client/rest/rest_client.py, conans/test/functional/remote/auth_test.py
Changelog: Bugfix: Fixed authentication with an Artifactory repository with anonymous access disabled.
Docs: omit
Close #6020
Close #6023
It might deserve a test with something mocked.
=> Fix auth error during capabilities fetch

conans/client/build/autotools_environment.py
Changelog: Bugfix: The `AutoToolsBuildEnvironment` build helper now uses the `win_bash` parameter of the constructor when calling to `configure()`.
Docs: omit
=> use win_bash in configure --help

conans/requirements.txt
This is another alternative for #6029. If you don't want to wait for Astroid release, we can force Six version.
Changelog: Bugfix: Fix Six package version to be compatible with Astroid
Docs: Omit
fixes #6029
=> #6029 Force Six version to 1.12.0

conans/client/conf/__init__.py, conans/test/unittests/util/client_conf_test.py, conans/util/log.py
Now any user can set Conan logging level using common names as debug, info, critical ...
Related Issue: #5765 
Changelog: Feature: Accept logging level as logging names
Docs: https://github.com/conan-io/docs/pull/1419
=> Accept logging level names (#5765)

conans/client/cmd/export.py, conans/test/functional/scm/scm_test.py
Changelog: Bugfix: Using the `scm` feature with `auto` fields was not using correctly the freeze sources from the local user directory from the second call to `conan create`.
Docs: omit
Closes #5195 again
=> Remove sources when new scm changes are copied

conans/build_info/build_info.py, conans/test/integration/test_build_info_creation.py
Changelog: Bugfix: Fix fail when conan_sources.tgz not present in remote.
Docs: Omit
Closes #6080
=> Build info issue/6080

conans/client/cmd/export.py, conans/test/functional/scm/scm_test.py
Changelog: Bugfix: Using `scm` with `auto` values with a `conanfile.py` not being in the root scm folder it failed to export the right source code directory if not using `--ignore-dirty` and the repo was not pristine.
Docs: omit
Closes #6070
#TAGS: svn, slow
=> Fix scm base dir without ignore dirty

conans/client/command.py
If an additional option gets set with True|False, it needs to be applied
case sensitive, i.e. with capital letter. In any other case this will
lead to an error during Conan's configure step.
Changelog: Bugfix: Fix the help message for `conan export-pkg` command for the --options parameter.
Docs: omit
=> Fix doc string for --options parameter

conans/client/conan_api.py, conans/client/remote_manager.py, conans/client/remover.py, conans/client/rest/auth_manager.py, conans/client/rest/rest_client.py, conans/test/functional/command/remote_verify_ssl_test.py, conans/test/functional/remote/rest_api_test.py, conans/test/functional/remote/token_refresh_test.py, conans/test/utils/tools.py
Docs: omit
Closes #5957 
Unlock #5856 
- The `conan_api` now uses `RestApiClientFactory` instead of a `RestApiClient`. The factory receives the "immutable" collaborators: `self.out`, `self.requester`,  `revisions_enabled` and `artifacts_properties`. On the other hand, a new `RestApiClient` is created for every request to be made, passing at that moment the `remote`, the `username`, `token` and `refresh_token`. 
- The capabilities cache is shared, on the `RestApiClientFactory`.
- The `ConanApiAuthManager` has been simplified:
- It is not a decorator anymore.
- All the rest methods are called from the `remote_manager` using `call_rest_api_method` (not need to declare the interface of the rest_api in this module anymore).
- Renamed "remove" and "remove_conanfile" methods to …
=> Refactor auth/rest layer: Concurrency

conans/client/build/cmake.py, conans/client/build/cmake_flags.py, conans/test/functional/build_helpers/cmake_flags_test.py, conans/test/unittests/client/build/cmake_test.py
Docs: omit
This is a refactor around the `CMakeDefinitionsBuilder` class to make it easier to work with the toolchains (they will use the same class to generate the CMake variables). Changes:
* `CONAN_EXPORTED` is moved to the build helper
* minor refactor around `CMAKE_BUILD_TYPE` to reuse code
#TAGS: slow
=> Move outside cmake_flags definitions of CONAN_EXPORTED

conans/client/command.py
Changelog: Fix: Fix create command build policy help message to reflect correct behavior. 
Docs: https://github.com/conan-io/docs/pull/1483
The `--build` policy help message was the same for the commands `create`, `test`, `install` and `workspace` but the behavior for `create` command by default was not to behave as `--build=never` but as `--build=package name` which could be misleading.
=> Change help message for --build policy for create command

conans/client/command.py, conans/client/conan_api.py, conans/test/functional/command/download_test.py, conans/test/utils/tools.py
Changelog: Bugfix: Fix different problems when using `conan download` with revisions. 
Docs: Omit
This PR fixes the following problems when using revisions with `conan download` command:
- If you had revisions disabled and added a revision to download command it did not fail but even create the revision in the cache.
- With revisions enabled but without user and channel the command failed.
- When revisions enabled and specifying a recipe revision it did not download the correct recipe revision but the last one.
- When revisions enabled and specifying a package revision it did not download the correct package revision.
It also fixes that when using `create` in the `TurboTestClient` without user and channel the command failed.
Closes #6106 
<sup>**Note:** By default this PR will skip the …
=> Fix several issues with download command and revisions

conans/client/cmd/uploader.py, conans/client/command.py, conans/test/functional/command/upload_test.py
Changelog: Bugfix: Upload correct packages when specifying revisions and fail with incorrect ones. 
Docs: Omit
When uploading using recipe revisions or package revisions all that information was obviated. You could even upload a package with a fake revision or specify the revision even with revisions disabled and the command did not fail. This PR fixes that behaviour so doing something like:
`conan upload pkg/0.1@user/channel#rrev:pkgid#prev` 
will check those fields to upload the correct package that must match with the one that's stored in the cache
<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by …
=> Fix upload behaviour when using revisions for packages

conans/client/tools/win.py
Changelog: Fix: Fix SyntaxWarning when comparing a literal with for identity in Python 3.8
Docs: None
Since version 3.8 CPython emits a `SyntaxWarning` when one tries to compare a literal with `is` or `is not` (it is mentioned [int eh changelog](https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior)). I run into such a warning when installing the Conan from its `develop` branch on Windows:
```
d:\morwenn\projets\conan\conans\client\tools\win.py:283: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if len(version) is not 0:
d:\morwenn\projets\conan\conans\client\tools\win.py:293: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if len(property_) is not 0:
```
Like most `SyntaxWarning` it is likely to become an error in the future, so it is better to fix …
=> Fix SyntaxWarning when comparing a literal with for identity in Python 3.8

conans/client/generators/cmake_find_package_multi.py, conans/test/functional/generators/cmake_find_package_multi_test.py, conans/test/unittests/client/generators/cmake_test.py
closes: #5888 
Changelog: Feature: The generator `cmake_find_package_multi` generates a `PackageConfigVersion.cmake` file that allows using `find_package` with the `VERSION` argument.
Docs: https://github.com/conan-io/docs/pull/1484
=> Feature: generate ConfigVersion.cmake file

conans/client/generators/cmake_find_package_common.py
Changelog: Fix: Add the RES_DIRS as variable to the variables when using the ``cmake_find_package`` generator. 
Docs: Omit
Fix #3722 .
=> Add res dir to the variables when using cmake_find_package. (issue 3722)

conans/build_info/build_info.py, conans/build_info/command.py, conans/test/integration/test_build_info_creation.py
Changelog: Bugfix: Removing `--skip-env`  and `--multi-module` arguments  for `conan_build_info --v2`. Now the environment is not captured (will be handled by the Artifactory plugin) and recipes and packages are saved as different modules in build info.
Docs: https://github.com/conan-io/docs/pull/1486
This PR simplifies Conan build info creation by always saving the information in different modules for recipes and packages (removes the old `--multi-module` argument).  Also, it will not capture environment information by default (removes the old `--skip-env` argument because the environment information will be handled by the Jenkins Artifactory plugin once this command is integrated into the plugin).
Closes #6144 by removing the arguments.
<sup>**Note:** By default this PR will skip the …
=> Simplify conan_build_info --v2 arguments

conans/client/tools/__init__.py, conans/client/tools/settings.py, conans/test/functional/tools/cppstd_minimum_version_test.py, conans/test/unittests/client/tools/cppstd_required_test.py, conans/tools.py
Add a new tool: `cppstd_minimum_version`:
- Receive a ConanFile instance and handle its settings to detect the current cppstd, from profile or from arguments.
- If it is not able to detect by settings, then it will extract from current compiler (from profile) and compare if such compiler version is able to manipulate the required cppstd.
- Any failure will result in an InvalidConfiguration error.
- Why not only returning False and the user take care about the exception? 
Because the error can be caused by compiler or settings, so we would need to return 2 elements (result + message) and the user will (probably) forward the message as an InvalidConfiguration.
NOTE: This feature should be affected by https://github.com/conan-io/conan/pull/5440
Changelog: Feature: Detect if cppstd version …
=> #5958 New tool: cppstd minimum version required

conans/build_info/build_info.py
Changelog: Bugfix: Remove carriage returns from build info `.json` file to avoid Artifactory errors in some cases when publishing the build info to the remote.
Docs: Omit
It looks like in some cases the build info publishing failed with an `ERROR: 400: Bad Request` if the file contained carriage returns.
Closes #6103
=> Remove carriage returns from build info json file

conans/client/tools/system_pm.py, conans/test/unittests/client/tools/system_pm_test.py
Changelog: Bugfix: Implement ``SystemPackageTool.installed(package_name)`` as described in the documentation.
Docs: Omit
Close #6196
=> SystemPackageTool.installed()

conans/client/generators/virtualenv.py
Docs: omit
https://github.com/conan-io/conan/pull/5989#discussion_r354673933
I would say everything on there are standard shell commands, nothing bash specifics, right? @jgsogo 
It might happen that bash is not in the system.
=> Use `sh` instead of `bash`

conans/client/conan_api.py, conans/test/functional/command/inspect_test.py
Changelog: Bugfix: ``conan inspect`` now is able to properly show name and version coming from ``set_name()`` and ``set_version()`` methods.
Docs: Omit
Close #6213
=> fix inspect with set_name() set_version()

conans/client/generators/cmake.py, conans/client/generators/cmake_common.py, conans/client/generators/cmake_multi.py
Docs: omit
Store each macro/function definition in a different variable so I can use the ones I need in the PR of the toolchains (https://github.com/conan-io/conan/pull/5919#discussion_r348399679)
#TAGS: slow
=> [refactor] Make macros/functions in 'cmake_common' available to reuse

conans/client/command.py, conans/client/conan_command_output.py, conans/client/printer.py, conans/test/functional/command/search_test.py
Changelog: Bugfix: --raw argument is ignored when searching for a specific reference
Docs: Omit
The `--raw` argument is ignored when searching for a specific reference with or without `--revisions` regardless if there's `user/channel` present or not.
Closes #6077 
=> raw argument is ignored when searching for a specific reference

conans/client/rest/rest_client.py, conans/client/rest/rest_client_common.py, conans/test/functional/remote/auth_test.py
Changelog: Fix: When the token is empty, and ``conan user myuser -p=mypass -r=remote`` is used, the user-password are send in HttpBasic so it can be used for completely protected servers that do not expose the ping endpoint.
Docs: Omit
Investigation PR, to see if it makes sense to send HttpBasic over ping instead of empty JWT
Maybe close #6240
#tags: slow
=> Use HttpBasic auth in the ping API endpoint for the "conan user" command.

conans/client/generators/cmake_find_package.py, conans/client/generators/cmake_find_package_multi.py, conans/client/generators/cmake_multi.py, conans/test/functional/generators/cmake_find_package_multi_test.py, conans/test/functional/generators/cmake_find_package_test.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Fix: Add `cpp_info.<config>` information to `cmake_find_package_multi` and `cmake_find_package` generators
Docs: https://github.com/conan-io/docs/pull/1508
Closes https://github.com/conan-io/conan/issues/6136
---
When a recipe contains information specific per configuration:
```python
class Requirement(ConanFile):
name = "requirement"
version = "version"
settings = "os", "arch", "compiler", "build_type"
def package_info(self):
self.cpp_info.libs = ["lib_both"]
self.cpp_info.debug.libs = ["lib_debug"]
self.cpp_info.release.libs = ["lib_release"]
self.cpp_info.cxxflags = ["-req_both"]
self.cpp_info.debug.cxxflags = ["-req_debug"]
self.cpp_info.release.cxxflags = ["-req_release"]
```
this information is now propagated to the corresponding build-type file (see tests)
=> Add 'cpp_info.<config>' information to 'cmake_find_package[_multi]' generators

conans/client/generators/cmake_find_package_multi.py, conans/client/generators/visualstudio_multi.py, conans/test/functional/generators/cmake_find_package_multi_test.py, conans/test/functional/generators/multi_generators_test.py
Changelog: Fix: Multi-generators cannot be used without `build_type` setting. A failure is forced to `cmake_find_package_multi` and `visual_studio_multi` as it was in `cmake_multi`.
Docs: omit
closes https://github.com/conan-io/conan/issues/6135
This PR forces in all the _multi-generators_ the same failure that we were triggering for the `cmake_multi` one.
Currently, the full error shown to the user that runs the `conan install` is:
```bash
[...]
conanfile.py: ERROR: Generator cmake_multi(file:None) failed
'settings.build_type' doesn't exist
'settings' possible configurations are ['arch', 'compiler', 'os']
ERROR: 'settings.build_type' doesn't exist
'settings' possible configurations are ['arch', 'compiler', 'os']
```
Let me know if we want to improve it to add a more meaningful message. …
=> Multi-generators cannot be used without 'build_type' setting

conans/client/conan_api.py, conans/client/rest/conan_requester.py, conans/client/rest/rest_client.py, conans/client/rest/rest_client_common.py, conans/client/rest/rest_client_v1.py, conans/client/rest/rest_client_v2.py, conans/client/rest/uploader_downloader.py, conans/client/tools/net.py, conans/test/functional/command/config_install_test.py, conans/test/functional/remote/rest_api_test.py, conans/test/functional/remote/retry_test.py, conans/test/functional/remote/token_refresh_test.py, conans/test/unittests/client/rest/rest_client_v1/test_get_package_manifest.py, conans/test/unittests/client/rest/rest_client_v2/test_get_package_manifest.py, conans/test/unittests/client/rest/uploader_test.py, conans/test/unittests/util/tools_test.py, conans/tools.py
Docs: Omit
The rest HTTP layer never had direct access to config. We want to give it, for example to be able to cache file downloads as defined by the configuration "download_cache" path. It makes sense to pass the whole config object (if not the whole app, but at the moment at least the config).
This is just a refactor to pass the config object to the HttpClients v1 and v2 (and common), so they could use it, and also moving the "retry" configuration out of the ``ConanRequester`` and to the config, where it belongs.
#revisions: 1
#tags: slow
=> refactor to give access to config to Rest layer

conans/client/build/autotools_environment.py, conans/client/build/cmake.py, conans/client/tools/env.py, conans/client/tools/win.py
Changelog: Bugfix: The ``environment_append()`` helper does not modify the argument anymore, which caused problems if the argument was reused.
Docs: omit
The ``environment_append()`` was destroying the argument, which is dangerous, because this context is called for every recipe method. I have tracked the uses and calls, and it seems that it is always getting a temporary copy as argument, so shouldn't be really causing bugs, but it seems it is worth fixing it.
=> non destroy environment_append

conans/client/generators/cmake_common.py
Changelog: Fix: Fix minor issues in `cmake` and `cmake_multi` generators: wrong variable used in `conan_find_apple_frameworks` macro.
Docs: omit
=> fix issue in 'cmake|cmake_multi' generators

conans/client/conf/__init__.py, conans/test/functional/command/config_test.py
This PR is a clean copy of [this one](https://github.com/conan-io/conan/pull/6276) pointing to the correct branch.
Changelog: Bugfix: Enhance validation of the `short_paths_home` property to correctly handle the scenarios where it is set to a path that contains the value of the Conan cache path, but is not a subdirectory of it.
Docs: Omit
Fixes: #6273 
- NA I've opened another PR in the Conan docs repo to the ``develop`` branch, documenting this one. 
=> Fix short_paths_home validation

conans/client/generators/pkg_config.py, conans/test/unittests/client/generators/pkg_config_test.py
Changelog: Bugfix: Fixes `cpp_info.name` vs. `cpp_info.names` issue in `pkg_config` generator
Docs: omit
**TARGET THIS TO NEW RELEASE BRANCH** Done!
=> Fixes cpp_info.name vs. cpp_info.names issue in pkg_config generator

conans/client/tools/win.py, conans/test/unittests/util/tools_test.py
Changelog: Fix: Avoid WindowsStore ``tools.vcvars()`` management when the environment is already set.
Docs: Omit
=> fix bug in windows_store vcvars

conans/client/generators/cmake.py, conans/client/generators/cmake_common.py, conans/client/generators/cmake_multi.py, conans/client/generators/cmake_paths.py, conans/model/build_info.py, conans/test/unittests/client/generators/cmake_paths_test.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Fix: Generators `cmake` and `cmake_multi` use the name of the package instead of `cpp_info.name` (this change is to be reverted in 1.22)
Docs: omit
closes https://github.com/conan-io/conan/issues/6269
This PR is a patch to keep previous behavior (and future one) related to the name used by the generators. In this PR the `cmake` generator will use the value in `cpp_info.names["cmake"]` or the package name (**it won't use `cpp_info.name`**). With this workaround we don't need to change any recipe in `conan-center-index` right now to match the desired behavior, we can wait until Conan v1.22.
Read the rationale in this comment: https://github.com/conan-io/conan/issues/6269#issuecomment-570182130
=> 'cmake' generator use the package name for target 'CONAN_PKG::'

conans/client/rest/uploader_downloader.py, conans/test/unittests/client/rest/uploader_test.py, conans/test/unittests/util/tools_test.py
Changelog: Bugfix: Fix uninformative crash when ``tools.download()`` gets a 403 and it is not providing an ``auth`` field.
Docs: Omit
Close #6316
#tags: slow
=> fix unathorized transfers

conans/model/conan_file.py, conans/test/integration/options_test.py
Changelog: Fix: use `six.string_types` to check if _default options_ are strings
Docs: omit
I'm not able to reproduce the issue in our CI, but I think that it is safe to merge this change.
closes #6321
=> Use 'six.string_types' to check if default options are strings

conans/client/generators/virtualenv.py, conans/test/functional/generators/virtualenv_windows_bash_test.py
Changelog: Bugfix: Fixing readout of backslashes (#6301)
Docs: omit
closes #6301 
closes #6323
=> Fixing readout of backslashes (#6301)

conans/client/conf/detect.py
Changelog: Fix: Avoid warning in "detect" process with Python 3.8, due to Popen with ``bufsize=1``
Docs: omit
Closes #6332
This is a possible solution to the issue, the other one is to remove the bufsize argument but seeing that the code parses line by line this seems more appropriate.
From the commit message:
Python 3.8 started reporting warnings when binary files are opened with
bufsize > 0, see https://bugs.python.org/issue32236 for the change and
https://github.com/benoitc/gunicorn/issues/2091 for a similar issue.
The error message was:
py.warnings: WARNING: /usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
----
- [x I've opened another PR in the Conan docs repo to the ``develop`` …
=> Bugfix: Request text mode to Popen to avoid buffering warning (python 3.8)

conans/client/file_copier.py
Changelog: Fix: Raise error for symlinks in Windows pointing to a different unit.
Docs: Omit
Close #6197
Note this is almost impossible to test: it requires Administrator permissions to create a unit X: and then mklink to it to reproduce
=> Raise when symlinks use different drive in Windows

conans/client/cmd/export.py, conans/client/conan_api.py, conans/client/conf/__init__.py, conans/client/loader.py, conans/model/scm.py, conans/test/functional/scm/test_scm_to_conandata.py, conans/test/unittests/client/cmd/export/test_capture_export_scm_data.py
Changelog: Feature: Add opt-in `scm_to_conandata` for the SCM feature: Conan will store the data from the SCM attribute in the `conandata.yml` file (except the fields `username` and `password`)
Docs: https://github.com/conan-io/docs/pull/1522
Add an opt-in to store the fields evaluated from the `scm` attribute into the `conandata.yml` file (all fields except `username` and `password`). This way the recipe itself, the `conanfile.py` is not modified by Conan. Note.- This could be the default behavior for Conan 2.0 and remove the previous implementation.
closes #6275
```yml
.conan:
scm:
url: ....
revision: ...
```
=> Opt-in to store SCM evaluated data into 'conandata.yml' file

conans/client/command.py, conans/test/functional/configuration/python_version_test.py, conans/test/functional/graph_lock/graph_lock_test.py
Changelog: Feature: Force the user to read that Python 2 has been deprecated
Docs: https://github.com/conan-io/docs/pull/1523
closes https://github.com/conan-io/conan/issues/6170
=> Require user input to continue working with Python 2

conans/test/unittests/client/tools/net_test.py
Remove FTP test in 'master' for MacOS (avoid false positives)
The proposed changes match exactly the file currently in `develop`
=> Remove FTP test in 'master' for MacOS (avoid false positives)

conans/client/cmd/export.py, conans/client/conf/detect.py, conans/test/functional/conanfile/conan_data_test.py, conans/test/utils/test_files.py
Changelog: Bugfix: Fix broken compression of .tgz files due to Python 3.8 changing tar default schema.
Changelog: Fix: Recipe substitution for `scm` (old behavior) fixed for multiline comments in Python 3.8
Docs: https://github.com/conan-io/docs/pull/1526
#PYVERS: py38
#revisions: 1
=> [ci] Python 3.8

conans/client/build/autotools_environment.py, conans/test/unittests/client/build/autotools_environment_test.py, conans/test/utils/conanfile.py
Changelog: Bugfix: Include MacOS frameworks definitions in autotools LDFLAGS (also Meson). 
Changelog: Bugfix: Apply ``system_libs`` information in autotools build helper.
Docs: Omit
=> include macos frameworks in autotools LDFLAGS

conans/client/build/msbuild.py, conans/test/functional/build_helpers/msbuild_test.py
Changelog: Feature: Allow defining an extra user-defined properties .props file in ``MSBuild`` build helper.
Docs: https://github.com/conan-io/conan/pull/6374
Close https://github.com/conan-io/conan/issues/6053
#tags: slow
=> extra .props file in MSBuild helper

conans/client/build/cmake.py, conans/client/build/meson.py, conans/client/build/msbuild.py, conans/client/conf/detect.py, conans/client/runner.py, conans/client/tools/apple.py, conans/client/tools/oss.py, conans/client/tools/pkg_config.py, conans/client/tools/scm.py, conans/client/tools/win.py, conans/test/functional/command/info_folders_test.py, conans/test/functional/environment/run_environment_test.py, conans/test/functional/generators/virtualbuildenv_test.py, conans/test/unittests/client/tools/os_info/osinfo_test.py, conans/test/unittests/util/detect_test.py, conans/test/unittests/util/tools_test.py, conans/test/utils/tools.py, conans/util/runners.py
Changelog: Fix: Cleaning ``LD_LIBRARY_PATH`` environment in ``SCM`` commands for "pyinstaller" installations, as SSL can fail due to using old SSL stuff from Conan instead from git/svn
Docs: Omit
It contains mostly a refactor, centralizing executions and subprocess stuff (not all of it, but most of it from production code). The only functional change is to introduce the pyinstaller fix in the SCM run() method.
Close #6161
#tags: slow
=> refactoring runners and pyinstaller SCM fix

conans/client/settings_preprocessor.py, conans/test/unittests/client/settings_preprocessor_test.py
Changelog: Feature: Deduce `compiler.base.runtime` for Intel compiler settings when using Visual Studio as the base compiler
Docs: omit
=> Set runtime for intel compiler with visual

conans/client/settings_preprocessor.py
Docs: omit
Realized after merging https://github.com/conan-io/conan/pull/6424/files that it is ``logger.info()`` incorrect information, saying that it did change the default runtime, even when it didnt.
=> logger error

conans/client/generators/cmake.py, conans/client/generators/cmake_common.py, conans/client/generators/cmake_multi.py, conans/client/generators/cmake_paths.py, conans/model/build_info.py, conans/test/unittests/client/generators/cmake_paths_test.py, conans/test/unittests/client/generators/cmake_test.py
This reverts commit 1bdbf183bb7ed48d2ee4ec87b10b34afb69bdbe6.
Changelog: Fix: Generators `cmake` and `cmake_multi` use the name defined in `cpp_info.name` (reverts change from 1.21.1 as stated)
Docs: omit
=> Revert PR #6288 

conans/client/profile_loader.py, conans/test/unittests/client/profile_loader/profile_loader_test.py
Changelog: Fix: Included profiles could overwrite variables in the current profile
Fix profile include order variable overwriting
If you had a setup like this:
*myinclude*
```
MYVAR=foo
```
*myprofile*
```
include(myinclude)
MYVAR=bar
```
The end result would be MYVAR=foo which is *very* confusing behavior. I think most users would expect MYVAR to be bar.
This was caused by inherited_vars being a reference and not a copy. Explicity copying the profile_parser.vars fixes the problem which leads me to think this is the original intent of this function since it matches what my expection would be as well.
=> Profile include order

conans/client/cmd/export.py, conans/client/conf/detect.py, conans/server/service/v2/service_v2.py, conans/test/functional/conanfile/conan_data_test.py, conans/test/functional/remote/multi_remote_test.py, conans/test/utils/test_files.py, conans/util/files.py
Cherry-pick changesets:
* #6355
* #6341
---
Changelog: Bugfix: Fix broken compression of .tgz files due to Python 3.8 changing tar default schema.
Changelog: Fix: Recipe substitution for scm (old behavior) fixed for multiline comments in Python 3.8
Docs: omit
I omit the docs, with this release we don't want to remove python 3.8 warnings from the docs
#revisions: 1
=> Add support for Python3.8

conans/client/generators/cmake_common.py, conans/client/generators/cmake_find_package.py, conans/client/generators/cmake_find_package_common.py, conans/client/generators/cmake_find_package_multi.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Feature: Set conan generated CMake targets as `GLOBAL` so that they can be used with an `ALIAS` for consumers.
Docs: https://github.com/conan-io/docs/pull/1534
Making an `ALIAS` of an `IMPORTED` target is possible in CMake for versions `>v3.10.3` (`>v3.14 `in case they are `UNKNOWN` too) but they have to be set as `GLOBAL`. 
This PR sets those targets defined by Conan as `GLOBAL` so they can take advantage of this for consumers with modern CMake versions.
fixes: #3482
#tags: slow
=> Add GLOBAL to conan targets so they can be used with ALIAS in CMake

conans/client/command.py
Changelog: Fix: Use CCI package reference for command example
Docs: Omit
=> Update Poco reference for command new

conans/client/generators/cmake_common.py, conans/client/generators/cmake_find_package.py, conans/client/generators/cmake_find_package_common.py, conans/client/generators/cmake_find_package_multi.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Fix: remove `GLOBAL` from targets to avoid conflicts when using `add_subdirectory`.
Docs: Omit
Fixes: #6480
=> Remove GLOBAL from targets to avoid conflict when using add_subdirectory

conans/requirements.txt
Changelog: (Feature): Update python six dependency to 1.14.0
See #6506
=> Upgrade python six to allow 1.14.0

conans/requirements.txt
Changelog: Fix: Increase ``six`` version to allow more modern releases.
Docs: Omit
From https://github.com/conan-io/conan/pull/6507
=> Upgrade python six to allow 1.14.0 (#6507)

conans/client/generators/premake.py, conans/test/unittests/client/generators/premake_test.py
Changelog: BugFix: Add ``system_libs`` to ``premake`` generator
Docs: Omit
Backport of https://github.com/conan-io/conan/pull/6495 (from release 1.22.1)
cc/ @Enhex
=> fix system libs in premake

conans/model/graph_lock.py, conans/test/functional/graph_lock/graph_lock_test.py
Changelog: Bugfix: Do not re-evaluate lockfiles nodes, only update the package reference, otherwise the build-requires are broken.
Docs: Omit
Fix https://github.com/conan-io/conan/issues/6484
#tags: slow
#revisions: 1
=> fix build order with build=missing with lockfiles

conans/client/cmd/uploader.py, conans/paths/package_layouts/package_cache_layout.py
Changelog: Bugfix: Fixing locking system for metadata file so it can be accessed concurrently.
Docs: omit
Fixes: #6521
#TAGS: slow
#REVISIONS: 1
=> avoiding concurrent modification of package metadata

conans/client/cmd/export_pkg.py, conans/test/functional/command/export_pkg_test.py
Changelog: Bugfix: Manage the dirty state of the cache package folder with conan export-pkg.
Docs: Omit
Backport of https://github.com/conan-io/conan/pull/6498
=> Manage the dirty state in "conan export-pkg" command

conans/client/cmd/uploader.py, conans/paths/package_layouts/package_cache_layout.py
Changelog: Bugfix: Fixing locking system for metadata file so it can be accessed concurrently.
Docs: omit
Backport of #6524
#TAGS: slow
#REVISIONS: 1
=> avoiding concurrent modification of package metadata (#6524)

conans/client/conf/detect.py, conans/test/unittests/client/conf/detect/test_gcc_compiler.py
Changelog: Bugfix: Parse function of GCC version from command line now works with versions `>=10`
Docs: omit
closes #6538 
closes #6539
=> Fix: parse GCC 10 version from command line

conans/client/generators/cmake_common.py, conans/client/generators/cmake_find_package_common.py
Docs: omit
The CMake variable `CONAN_FOUND_LIBRARY` is currently displayed when opening the generated build directory in `cmake-gui`.
Current content of `CMakeCache.txt`:
```
[...]
//Path to a library.
CONAN_FOUND_LIBRARY:FILEPATH=C:/Users/myuser/.conan/data/gtest/1.10.0/leica/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gtest.lib
[...]
```
=> cmake_find_package - CONAN_FOUND_LIBRARY shouldn't be visible in cmake-gui

conans/client/build/msbuild.py, conans/test/unittests/client/build/msbuild_test.py
Changelog: Fix: Raise an error if ``MSBuild`` argument ``targets`` is not a list, instead of splitting a string passed as argument instead of a list.
Docs: omit
Close https://github.com/conan-io/conan/issues/6553
=> raise if targets is not a list

conans/client/command.py, conans/client/conan_api.py, conans/model/graph_lock.py, conans/test/functional/graph_lock/graph_lock_ci_test.py
Changelog: Implement ``conan graph clean-modified`` subcommand to be able to clean the modified state of a lockfile and re-use it later for more operations.
Docs: https://github.com/conan-io/docs/pull/1542
This reverts commit 9f3e486f98c72c1aaec16c0692ec711d0bae2cd6.
Seen with @memsharded, there is a use-case for reintroducing this subcommand: when sharing lockfiles with devs and further CI jobs (especially needed when one does not want to use latest recipe revisions, thus regenerating locks from scratch is not acceptable).
Closes #6436
=> Put back graph clean-modified subcommand

conans/client/conan_api.py, conans/test/functional/command/inspect_test.py
Changelog: Fix: inspect command can be executed without remote.json (#6558)
Docs: Omit
fixes #6558
=> Fix Conan inspect when remote.json is not created

conans/client/build/cmake_flags.py, conans/test/unittests/client/build/cmake_test.py
closes: #6542
Changelog: Bugfix: set CMAKE_OSX_DEPLOYMENT_TARGET for iOS, watchOS, tvOS
Docs: omit
=> Bugfix: set CMAKE_OSX_DEPLOYMENT_TARGET for iOS, watchOS, tvOS

.ci/jenkins/Jenkinsfile, conans/test/utils/tools.py
Docs: omit
Modify the value of the config flag `general.revisions_enabled` only if it is set explicitly by the user or by the testing environment variable. 
This change will let us initialize with a different value the `TestClient` for Conan v1 and Conan v2 (depending on the `CONAN_V2_MODE`, the file `conan.conf` will be created with different values)
There is also a PR to the CI to be merged with this one: https://github.com/conan-io/conan_ci_jenkins/pull/13
#REVISIONS: 1
=> [ci] Set the value of 'general.revisions_enabled' only if given

conans/client/generators/cmake_common.py, conans/client/generators/text.py, conans/test/functional/generators/cmake_apple_frameworks_test.py, conans/test/unittests/client/generators/cmake_test.py
Changelog: Bugfix: improve Apple frameworks lookups with CMake integration
Docs: omit
updated version of #6499
closes: #6416
code from https://github.com/Paultergeist/conan_apple_framework
=> new apple frameworks test #6499

conans/model/info.py, conans/test/functional/py_requires/python_requires_test.py
Changelog: Bugfix: Fixed crashing of recipes using both ``python_requires`` and ``build_id()``.
Docs: Omit
Close https://github.com/conan-io/conan/issues/6562
=> fixing python_requires with build_id

conans/client/build/build.py, conans/client/cmd/build.py, conans/client/installer.py, conans/test/functional/options/options_test.py, conans/test/unittests/tools/files_patch_test.py
Docs: omit
A refact to call the function `conanfile::build()` in a single place (easy to see the environment applied)
This changes the order of some outputs related to the hooks and a message (all of them commented in the PR), but I'd think it is not breaking, is it?
=> [refact] Run 'conanfile::build()' only once in the sources

conans/client/build/cmake.py, conans/test/unittests/client/build/cmake_test.py
Changelog: Bugfix: Conan should not append generator_platform to the Visual Studio generator if it is already specified by the user.
Docs: omit
Conan should not append generator_platform to the Visual Studio generator if it is already specified by the user - otherwise this breaks builds and means all users must upgrade to use the same version of Conan (there is no way to structure the call to CMake's constructor such that it works with Conan both before and after this change).
=> Only append generator_platform if needed

conans/client/generators/text.py, conans/test/unittests/client/generators/text_test.py
Changelog: Bugfix: Fix error parsing `system_libs` from `conanbuildinfo.txt` file
Docs: omit
Closes https://github.com/conan-io/conan/issues/6610
=> Fix error parsing `system_libs` from `conanbuildinfo.txt` file

conans/model/info.py, conans/test/functional/package_id/compatible_test.py, conans/test/functional/py_requires/python_requires_test.py
Changelog: Bugfix: Fixed crashing of recipes using both ``python_requires`` and ``build_id()``.
Docs: Omit
Cherry-pick https://github.com/conan-io/conan/pull/6563
Closes #6609
=> fixing python_requires with build_id (#6563)

conans/client/cmd/export_pkg.py, conans/client/installer.py, conans/test/functional/command/export_pkg_test.py
Changelog: Bugfix: Environment variables from the profiles are not set in the _conaninfo.txt_ file of the packages exported with the `export-pkg` command.
Docs: Omit
Closes: #6603
=> Set environment variables in conaninfo.txt when using export-pkg

conans/model/info.py
Docs: omit
Misleading exception. It was the origin of https://github.com/conan-io/conan/issues/6609 and https://github.com/conan-io/conan/issues/6562
=> Capture the expected exception

conans/client/build/meson.py, conans/test/unittests/client/build/meson_test.py
Changelog: (Feature | Bugfix):
- Fixed inability to run execute `test` and `install` separately, that is, without `build` step.
- Added `meson_test()` method, which executes `meson test` (compared to `ninja test` in `test()`). `meson test` have multiple options for additional test configuration (https://mesonbuild.com/Unit-tests.html#testing-tool).
- Added `meson_install()` method, which executes `meson install` (compared to `ninja install` in `install()`). `meson install` have multiple options for additional installation configuration (https://mesonbuild.com/Installing.html#custom-install-behaviour).
Docs: https://github.com/conan-io/docs/pull/1568
<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check …
=> [meson] Fixes for `test` and `install` + `meson_test` & `meson_install`

.editorconfig
Docs: omit
From time to time I see some PRs doing some reformat (besides the functionality they try to implement) and I wonder if we all are using the same configuration in our editor.
Most common editors will use it: https://editorconfig.org/
Initial values are taken from https://github.com/django/django/blob/master/.editorconfig and the 101 columns we are already using.
=> Add '.editorconfig'

conans/client/command.py
Changelog: Fix: Add build policy help for `--build` argument when used in `conan graph build-order` command.
Docs: https://github.com/conan-io/docs/pull/1584
=> Add build policy help to graph build-order

conans/client/tools/settings.py, conans/test/unittests/client/tools/cppstd_required_test.py
Changelog: Fix: check_min_cppstd raises an exception for unknown compiler
Docs: https://github.com/conan-io/docs/pull/1559
fixes #6547 
=> #6547 Raise exception for unknown compiler

conans/client/tools/win.py
Changelog: Bugfix: Fix vcvars_arch usage before assignment, that can cause a crash in ``tools.vcvars_command()`` that is also used internally by ``MSBuild`` helper.
Docs:  Omit
Fixes: #6674
=> Fix vcvars_arch usage before assignment.

conans/client/command.py
Changelog: (Fix): Improve the command line help for the `conan install --build` option.
Docs: tbd
Fixes #6655
=> Rephrase build_policy help (install --build)

pyinstaller.py
Changelog: Fix: Added print to stderr and exit into pyinstaller script when it detects python usage of python 3.8 or higher. Currently pyinstaller does not support python 3.8. https://github.com/pyinstaller/pyinstaller/issues/4311
Docs: Omit
fixes #6325
=> pyinstaller will print error on python 3.8 or higher

conans/requirements.txt
Docs: omit
I'm proposing to relax `patch-ng` dependency. A change is needed to get new `1.17.4` (not released yet) that fixes issue https://github.com/conan-io/conan/issues/6676
Probably it is a good idea to _relax this requirement_ so it is not needed to release a new Conan version to have this kind of patches available, even though not all of our users will get the new version if they don't force the update of the requirement. The way to force a new version would be to modify the minor version and then change the requirement in Conan.
=> Relax patch-ng dependency

conans/client/conf/config_installer.py
Changelog: Fix: Remove file before copying in ``conan config install`` to avoid permission issues.
Docs: Omit
Close https://github.com/conan-io/conan/issues/6556
=> possible solution for conan config install

conans/client/conf/__init__.py, conans/client/tools/system_pm.py, conans/test/unittests/client/tools/system_pm_test.py
Changelog: Feature: Set the default `CONAN_SYSREQUIRES_MODE` in `SystemPackageTool` to be able to create a recipe that does not install system requirements by default if the `CONAN_SYSREQUIRES_MODE` is not set.
The purpose of this feature is to have the option to add a recipe for example to c3i where this variable should be set to `enabled` but if someone is requiring this dependency not forcing to install the system requirements if the `CONAN_SYSREQUIRES_MODE` environment variable is not set.
<sup>**Note:** By default this PR will skip the slower tests and will use a limited set of python versions. Check [here](https://github.com/conan-io/conan/blob/develop/.github/PR_INCREASE_TESTING.md) how to increase the testing level by writing some …
=> Possibility to change the default CONAN_SYSREQUIRES_MODE for SystemPackageTool

conans/test/unittests/util/tools_test.py, conans/util/runners.py
Changelog: Bugfix: Fix check_output_runner() to handle dirs with whitespaces. 
Docs: Omit
Close #6694 
If TEMP/TMPDIR envs point to a directory that contains whitespaces, check_output_runner() fails. Generated filename needs to be quoted for it to be passed in into shell properly.
=> Fix temp file handling

conans/client/conan_api.py, conans/client/conf/__init__.py, conans/test/functional/command/config_test.py
Docs: omit
Move the table with environment variable names and _conan.conf_ name to a class attribute (avoid writing the envvar twice)
=> [refact] Reorder table with conan.conf variables

conans/client/installer.py, conans/test/functional/package_id/package_id_requires_modes_test.py
Changelog: Feature: Print more details for missing packages
Docs: https://github.com/conan-io/docs/pull/1616
closes #6364
=> Print more details for missing packages

conans/client/rest/file_uploader.py
Docs: Omit
This is fixing the error introduced in the latest Uploader refactor (https://github.com/conan-io/conan/pull/6690)
=> fix uploader refactor

conans/client/conan_api.py, conans/test/functional/command/export_pkg_test.py
Hi! This PR is related to #6489. 
When the package folder doesn't exist for the command export-pkg, a ConanException must be raised.
Changelog: Fix: Raises ConanException when package folder is invalid for export-pkg
Docs: https://github.com/conan-io/docs/pull/1624
fixes #6489
=> #6489 Raise ConanException for invalid package folder on export-pkg

conans/client/build/msbuild.py, conans/test/unittests/client/build/msbuild_test.py
Changelog: Bugfix: Add values to ``definitions`` passed to ``MSBuild`` build helper which values are not None (0, False...).
Docs: Omit
Fix https://github.com/conan-io/conan/issues/6728
=> fixing MSBuild definitions

conans/client/command.py, conans/client/conan_command_output.py, conans/client/printer.py, conans/test/functional/command/info_test.py
Add the field "description" as valid for the command Conan info.
Changelog: Feature: Conan info command allows description on the output
Docs: https://github.com/conan-io/docs/pull/1627
closes #6693
=> #6693 Check for description in JSON output

conans/test/functional/command/download/download_parallel_test.py, conans/test/functional/command/install/install_parallel_test.py
Docs: Omit
We don't want tests to fail randomly at CI. So better have something consistent until the tests and the output of parallel is correctly implemented.
=> only 1 thread for parallel download tests

conans/client/tools/net.py, conans/test/functional/cache/download_cache_test.py, conans/test/unittests/util/tools_test.py
Docs: Omit
#tags: slow
Several changes:
- Do not alter at all the behavior when len(url) == 1
- Avoid warnings of shadowing parameters
- Avoid useless ``downloader`` parameter, already in closure
- Capture a broader ``Exception``, as the ``requests`` library might throw connection errors that are not ``ConanException``
- Use the ``for-else`` idiom instead of counter.
=> fix download multi-url

conans/model/options.py, conans/model/settings.py, conans/test/unittests/model/options_test.py, conans/test/unittests/model/settings_test.py
Changelog: Feature: `settings.get_safe` and `options.get_safe` accept a default value
Docs: https://github.com/conan-io/docs/pull/1631
closes #6597
=> #6597 Add optional value for get_safe

conans/client/conf/detect.py
This fix the bug where the output of `suncc -V` reads:
```
cc: Studio 12.5 Sun C 5.14 SunOS_sparc 2016/05/31
```
and causes 12.5 rather than 5.14 to be captured as the version number of the C compiler.
Changelog: (Bugfix):
Fix https://github.com/conan-io/conan/issues/6749
=> Fix Sun C/C++ Compiler Version Detection

conans/client/conf/__init__.py
e.g. it allows **-stdlib=libc++**
related: #5699 
reference: 
https://software.intel.com/en-us/get-started-with-cpp-compiler-for-osx-parallel-studio-xe
https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-stdlib
Changelog: Feature: on Mac, Intel C++ is based on Apple Clang
Docs: https://github.com/conan-io/docs/pull/1637
=> Feature: on Mac, Intel C++ is based on Apple Clang

conans/client/generators/__init__.py, conans/client/generators/markdown.py
Changelog: Feature: Add `markdown` generator, it exposes useful information to consume the installed packages.
Docs: https://github.com/conan-io/docs/pull/1638
This PR adds a ``markdown``/``md`` generator to generate a Markdown file for each of the dependencies installed by Conan.
Besides showing useful information about each package and how to use it with different generators (add copy/paste snippet), it is trying to help with a pain some users may be facing right now: with the addition of ``cpp_info.names["<generator>"]]`` we usually need to have a look to the actual ``conanfile.py`` of the recipe or to the generated ``FindXXXX.cmake`` file in order to know the name of the target.
yea or nay? other ideas based on this one?
=> Markdown generator

conans/client/conf/__init__.py
Changelog: Fix: Add Sun C compiler version 5.15 into default settings.yml.
Docs: Omit
Since June 2017, the Oracle Developer Studio 12.6 has Sun C compiler version 5.15. This is missing in the default settings.yml.
=> Update Sun C compiler version in settings.yml

conans/paths/package_layouts/package_cache_layout.py, conans/util/windows.py
Changelog: Feature: Short paths feature is available for Cygwin
Closes https://github.com/conan-io/conan/issues/6660
This enables the **short paths feature for Cygwin** (we don't want to open it for any Windows subsytem checking for `OSInfo().is_windows` unless someone requests it)
=> Allow short_paths usage for Cygwin

conans/client/conf/__init__.py
add new Intel C++ compiler release to the default **settings.yml**
https://software.intel.com/en-us/articles/intel-c-compiler-191-for-windows-release-notes-for-intel-parallel-studio-xe-2020
https://software.intel.com/en-us/articles/intel-c-compiler-191-for-linux-release-notes-for-intel-parallel-studio-xe-2020
related: #5699 
Changelog: Feature: add Intel 19.1 (2020)
Docs: omit
=> Feature: add Intel 19.1 (2020)

conans/client/build/cmake.py, conans/client/tools/__init__.py, conans/client/tools/env.py, conans/client/tools/intel.py, conans/client/tools/win.py, conans/test/unittests/client/build/cmake_test.py, conans/test/unittests/client/tools/intel/compilervars_test.py
/cc @ohanar 
related: #5699 
NOTE: I only have a valid Linux license of Intel C++ compiler (they offer only Linux OSS), so Windows & Mac are untested. if someone can test them locally and report here, it would be nice.
heavily based on https://github.com/ohanar/conan/commit/7a62f3ac35573fdc6aa6a25d44111b87c726cb90
summary:
- added few tools helpers for Intel C++ compiler: **compilervars_command**, **compilervars_dict**, **compiler_vars** (context manager), analogous to **vcvars_command**, **vcvars_dict**, **vcvars**
- added function to locate Intel C++ compiler installation (needed to locate **compilervars.sh**/**compilervars.bat**)
- extracted common part to get environment variables diff: **tools.env.env_diff** (from **vcvars_dict** function)
- extracted **tools.win.is_win64** as it …
=> Feature: call compilervars.sh within CMake helper (Intel C++)

conans/client/build/cppstd_flags.py, conans/test/unittests/client/build/cpp_std_flags_test.py
related: #5699
the PR goes on top of recently merged #6744 
Changelog: Feature: handle C++ standard flag for Intel C++ compiler
Docs:omit
=> Feature: handle C++ standard for Intel C++ compiler

conans/client/build/compiler_id.py, conans/client/conf/detect.py, conans/test/unittests/client/build/autotools_environment_test.py, conans/test/unittests/client/build/compiler_id_test.py, conans/test/unittests/util/tools_test.py
Changelog: Feature: improve compiler detection
Docs: TODO
closes: #4322
things to test:
what else?
=> Feature: improve compiler detection
